// Code generated by ent, DO NOT EDIT.

package publisher

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the publisher type in the database.
	Label = "publisher"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldSlug holds the string denoting the slug field in the database.
	FieldSlug = "slug"
	// FieldLogoURL holds the string denoting the logo_url field in the database.
	FieldLogoURL = "logo_url"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldWebsiteURL holds the string denoting the website_url field in the database.
	FieldWebsiteURL = "website_url"
	// FieldSettings holds the string denoting the settings field in the database.
	FieldSettings = "settings"
	// FieldVerified holds the string denoting the verified field in the database.
	FieldVerified = "verified"
	// FieldActive holds the string denoting the active field in the database.
	FieldActive = "active"
	// FieldStripeConnectID holds the string denoting the stripe_connect_id field in the database.
	FieldStripeConnectID = "stripe_connect_id"
	// FieldStripeOnboardingComplete holds the string denoting the stripe_onboarding_complete field in the database.
	FieldStripeOnboardingComplete = "stripe_onboarding_complete"
	// FieldRevenueSharePercent holds the string denoting the revenue_share_percent field in the database.
	FieldRevenueSharePercent = "revenue_share_percent"
	// EdgeTemplates holds the string denoting the templates edge name in mutations.
	EdgeTemplates = "templates"
	// EdgeListings holds the string denoting the listings edge name in mutations.
	EdgeListings = "listings"
	// Table holds the table name of the publisher in the database.
	Table = "publishers"
	// TemplatesTable is the table that holds the templates relation/edge.
	TemplatesTable = "dashboard_templates"
	// TemplatesInverseTable is the table name for the DashboardTemplate entity.
	// It exists in this package in order to avoid circular dependency with the "dashboardtemplate" package.
	TemplatesInverseTable = "dashboard_templates"
	// TemplatesColumn is the table column denoting the templates relation/edge.
	TemplatesColumn = "publisher_id"
	// ListingsTable is the table that holds the listings relation/edge.
	ListingsTable = "listings"
	// ListingsInverseTable is the table name for the Listing entity.
	// It exists in this package in order to avoid circular dependency with the "listing" package.
	ListingsInverseTable = "listings"
	// ListingsColumn is the table column denoting the listings relation/edge.
	ListingsColumn = "creator_org_id"
)

// Columns holds all SQL columns for publisher fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldName,
	FieldSlug,
	FieldLogoURL,
	FieldDescription,
	FieldWebsiteURL,
	FieldSettings,
	FieldVerified,
	FieldActive,
	FieldStripeConnectID,
	FieldStripeOnboardingComplete,
	FieldRevenueSharePercent,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	SlugValidator func(string) error
	// DefaultVerified holds the default value on creation for the "verified" field.
	DefaultVerified bool
	// DefaultActive holds the default value on creation for the "active" field.
	DefaultActive bool
	// DefaultStripeOnboardingComplete holds the default value on creation for the "stripe_onboarding_complete" field.
	DefaultStripeOnboardingComplete bool
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the Publisher queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// BySlug orders the results by the slug field.
func BySlug(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSlug, opts...).ToFunc()
}

// ByLogoURL orders the results by the logo_url field.
func ByLogoURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLogoURL, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByWebsiteURL orders the results by the website_url field.
func ByWebsiteURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWebsiteURL, opts...).ToFunc()
}

// ByVerified orders the results by the verified field.
func ByVerified(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVerified, opts...).ToFunc()
}

// ByActive orders the results by the active field.
func ByActive(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActive, opts...).ToFunc()
}

// ByStripeConnectID orders the results by the stripe_connect_id field.
func ByStripeConnectID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStripeConnectID, opts...).ToFunc()
}

// ByStripeOnboardingComplete orders the results by the stripe_onboarding_complete field.
func ByStripeOnboardingComplete(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStripeOnboardingComplete, opts...).ToFunc()
}

// ByRevenueSharePercent orders the results by the revenue_share_percent field.
func ByRevenueSharePercent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRevenueSharePercent, opts...).ToFunc()
}

// ByTemplatesCount orders the results by templates count.
func ByTemplatesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTemplatesStep(), opts...)
	}
}

// ByTemplates orders the results by templates terms.
func ByTemplates(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTemplatesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByListingsCount orders the results by listings count.
func ByListingsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newListingsStep(), opts...)
	}
}

// ByListings orders the results by listings terms.
func ByListings(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newListingsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newTemplatesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TemplatesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, TemplatesTable, TemplatesColumn),
	)
}
func newListingsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ListingsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ListingsTable, ListingsColumn),
	)
}
