// Code generated by ent, DO NOT EDIT.

package human

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the human type in the database.
	Label = "human"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldPrincipalID holds the string denoting the principal_id field in the database.
	FieldPrincipalID = "principal_id"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldPasswordHash holds the string denoting the password_hash field in the database.
	FieldPasswordHash = "password_hash"
	// FieldAvatarURL holds the string denoting the avatar_url field in the database.
	FieldAvatarURL = "avatar_url"
	// FieldIsPlatformAdmin holds the string denoting the is_platform_admin field in the database.
	FieldIsPlatformAdmin = "is_platform_admin"
	// FieldLastLoginAt holds the string denoting the last_login_at field in the database.
	FieldLastLoginAt = "last_login_at"
	// FieldEmailVerifiedAt holds the string denoting the email_verified_at field in the database.
	FieldEmailVerifiedAt = "email_verified_at"
	// FieldSlug holds the string denoting the slug field in the database.
	FieldSlug = "slug"
	// FieldHeadline holds the string denoting the headline field in the database.
	FieldHeadline = "headline"
	// FieldBio holds the string denoting the bio field in the database.
	FieldBio = "bio"
	// FieldLinkedinURL holds the string denoting the linkedin_url field in the database.
	FieldLinkedinURL = "linkedin_url"
	// FieldGithubURL holds the string denoting the github_url field in the database.
	FieldGithubURL = "github_url"
	// FieldTwitterURL holds the string denoting the twitter_url field in the database.
	FieldTwitterURL = "twitter_url"
	// FieldWebsiteURL holds the string denoting the website_url field in the database.
	FieldWebsiteURL = "website_url"
	// FieldPublicProfile holds the string denoting the public_profile field in the database.
	FieldPublicProfile = "public_profile"
	// EdgePrincipal holds the string denoting the principal edge name in mutations.
	EdgePrincipal = "principal"
	// Table holds the table name of the human in the database.
	Table = "humen"
	// PrincipalTable is the table that holds the principal relation/edge.
	PrincipalTable = "humen"
	// PrincipalInverseTable is the table name for the Principal entity.
	// It exists in this package in order to avoid circular dependency with the "principal" package.
	PrincipalInverseTable = "principals"
	// PrincipalColumn is the table column denoting the principal relation/edge.
	PrincipalColumn = "principal_id"
)

// Columns holds all SQL columns for human fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldPrincipalID,
	FieldEmail,
	FieldName,
	FieldPasswordHash,
	FieldAvatarURL,
	FieldIsPlatformAdmin,
	FieldLastLoginAt,
	FieldEmailVerifiedAt,
	FieldSlug,
	FieldHeadline,
	FieldBio,
	FieldLinkedinURL,
	FieldGithubURL,
	FieldTwitterURL,
	FieldWebsiteURL,
	FieldPublicProfile,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// EmailValidator is a validator for the "email" field. It is called by the builders before save.
	EmailValidator func(string) error
	// DefaultIsPlatformAdmin holds the default value on creation for the "is_platform_admin" field.
	DefaultIsPlatformAdmin bool
	// SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	SlugValidator func(string) error
	// HeadlineValidator is a validator for the "headline" field. It is called by the builders before save.
	HeadlineValidator func(string) error
	// DefaultPublicProfile holds the default value on creation for the "public_profile" field.
	DefaultPublicProfile bool
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the Human queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByPrincipalID orders the results by the principal_id field.
func ByPrincipalID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrincipalID, opts...).ToFunc()
}

// ByEmail orders the results by the email field.
func ByEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmail, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByPasswordHash orders the results by the password_hash field.
func ByPasswordHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPasswordHash, opts...).ToFunc()
}

// ByAvatarURL orders the results by the avatar_url field.
func ByAvatarURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAvatarURL, opts...).ToFunc()
}

// ByIsPlatformAdmin orders the results by the is_platform_admin field.
func ByIsPlatformAdmin(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsPlatformAdmin, opts...).ToFunc()
}

// ByLastLoginAt orders the results by the last_login_at field.
func ByLastLoginAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastLoginAt, opts...).ToFunc()
}

// ByEmailVerifiedAt orders the results by the email_verified_at field.
func ByEmailVerifiedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmailVerifiedAt, opts...).ToFunc()
}

// BySlug orders the results by the slug field.
func BySlug(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSlug, opts...).ToFunc()
}

// ByHeadline orders the results by the headline field.
func ByHeadline(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHeadline, opts...).ToFunc()
}

// ByBio orders the results by the bio field.
func ByBio(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBio, opts...).ToFunc()
}

// ByLinkedinURL orders the results by the linkedin_url field.
func ByLinkedinURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLinkedinURL, opts...).ToFunc()
}

// ByGithubURL orders the results by the github_url field.
func ByGithubURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGithubURL, opts...).ToFunc()
}

// ByTwitterURL orders the results by the twitter_url field.
func ByTwitterURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTwitterURL, opts...).ToFunc()
}

// ByWebsiteURL orders the results by the website_url field.
func ByWebsiteURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWebsiteURL, opts...).ToFunc()
}

// ByPublicProfile orders the results by the public_profile field.
func ByPublicProfile(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPublicProfile, opts...).ToFunc()
}

// ByPrincipalField orders the results by principal field.
func ByPrincipalField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPrincipalStep(), sql.OrderByField(field, opts...))
	}
}
func newPrincipalStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PrincipalInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, PrincipalTable, PrincipalColumn),
	)
}
