// Code generated by ent, DO NOT EDIT.

package human

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/plexusone/dashforge/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Human {
	return predicate.Human(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Human {
	return predicate.Human(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Human {
	return predicate.Human(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Human {
	return predicate.Human(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Human {
	return predicate.Human(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Human {
	return predicate.Human(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Human {
	return predicate.Human(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Human {
	return predicate.Human(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Human {
	return predicate.Human(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Human {
	return predicate.Human(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Human {
	return predicate.Human(sql.FieldEQ(FieldUpdatedAt, v))
}

// PrincipalID applies equality check predicate on the "principal_id" field. It's identical to PrincipalIDEQ.
func PrincipalID(v uuid.UUID) predicate.Human {
	return predicate.Human(sql.FieldEQ(FieldPrincipalID, v))
}

// Email applies equality check predicate on the "email" field. It's identical to EmailEQ.
func Email(v string) predicate.Human {
	return predicate.Human(sql.FieldEQ(FieldEmail, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Human {
	return predicate.Human(sql.FieldEQ(FieldName, v))
}

// PasswordHash applies equality check predicate on the "password_hash" field. It's identical to PasswordHashEQ.
func PasswordHash(v string) predicate.Human {
	return predicate.Human(sql.FieldEQ(FieldPasswordHash, v))
}

// AvatarURL applies equality check predicate on the "avatar_url" field. It's identical to AvatarURLEQ.
func AvatarURL(v string) predicate.Human {
	return predicate.Human(sql.FieldEQ(FieldAvatarURL, v))
}

// IsPlatformAdmin applies equality check predicate on the "is_platform_admin" field. It's identical to IsPlatformAdminEQ.
func IsPlatformAdmin(v bool) predicate.Human {
	return predicate.Human(sql.FieldEQ(FieldIsPlatformAdmin, v))
}

// LastLoginAt applies equality check predicate on the "last_login_at" field. It's identical to LastLoginAtEQ.
func LastLoginAt(v time.Time) predicate.Human {
	return predicate.Human(sql.FieldEQ(FieldLastLoginAt, v))
}

// EmailVerifiedAt applies equality check predicate on the "email_verified_at" field. It's identical to EmailVerifiedAtEQ.
func EmailVerifiedAt(v time.Time) predicate.Human {
	return predicate.Human(sql.FieldEQ(FieldEmailVerifiedAt, v))
}

// Slug applies equality check predicate on the "slug" field. It's identical to SlugEQ.
func Slug(v string) predicate.Human {
	return predicate.Human(sql.FieldEQ(FieldSlug, v))
}

// Headline applies equality check predicate on the "headline" field. It's identical to HeadlineEQ.
func Headline(v string) predicate.Human {
	return predicate.Human(sql.FieldEQ(FieldHeadline, v))
}

// Bio applies equality check predicate on the "bio" field. It's identical to BioEQ.
func Bio(v string) predicate.Human {
	return predicate.Human(sql.FieldEQ(FieldBio, v))
}

// LinkedinURL applies equality check predicate on the "linkedin_url" field. It's identical to LinkedinURLEQ.
func LinkedinURL(v string) predicate.Human {
	return predicate.Human(sql.FieldEQ(FieldLinkedinURL, v))
}

// GithubURL applies equality check predicate on the "github_url" field. It's identical to GithubURLEQ.
func GithubURL(v string) predicate.Human {
	return predicate.Human(sql.FieldEQ(FieldGithubURL, v))
}

// TwitterURL applies equality check predicate on the "twitter_url" field. It's identical to TwitterURLEQ.
func TwitterURL(v string) predicate.Human {
	return predicate.Human(sql.FieldEQ(FieldTwitterURL, v))
}

// WebsiteURL applies equality check predicate on the "website_url" field. It's identical to WebsiteURLEQ.
func WebsiteURL(v string) predicate.Human {
	return predicate.Human(sql.FieldEQ(FieldWebsiteURL, v))
}

// PublicProfile applies equality check predicate on the "public_profile" field. It's identical to PublicProfileEQ.
func PublicProfile(v bool) predicate.Human {
	return predicate.Human(sql.FieldEQ(FieldPublicProfile, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Human {
	return predicate.Human(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Human {
	return predicate.Human(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Human {
	return predicate.Human(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Human {
	return predicate.Human(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Human {
	return predicate.Human(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Human {
	return predicate.Human(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Human {
	return predicate.Human(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Human {
	return predicate.Human(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Human {
	return predicate.Human(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Human {
	return predicate.Human(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Human {
	return predicate.Human(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Human {
	return predicate.Human(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Human {
	return predicate.Human(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Human {
	return predicate.Human(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Human {
	return predicate.Human(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Human {
	return predicate.Human(sql.FieldLTE(FieldUpdatedAt, v))
}

// PrincipalIDEQ applies the EQ predicate on the "principal_id" field.
func PrincipalIDEQ(v uuid.UUID) predicate.Human {
	return predicate.Human(sql.FieldEQ(FieldPrincipalID, v))
}

// PrincipalIDNEQ applies the NEQ predicate on the "principal_id" field.
func PrincipalIDNEQ(v uuid.UUID) predicate.Human {
	return predicate.Human(sql.FieldNEQ(FieldPrincipalID, v))
}

// PrincipalIDIn applies the In predicate on the "principal_id" field.
func PrincipalIDIn(vs ...uuid.UUID) predicate.Human {
	return predicate.Human(sql.FieldIn(FieldPrincipalID, vs...))
}

// PrincipalIDNotIn applies the NotIn predicate on the "principal_id" field.
func PrincipalIDNotIn(vs ...uuid.UUID) predicate.Human {
	return predicate.Human(sql.FieldNotIn(FieldPrincipalID, vs...))
}

// EmailEQ applies the EQ predicate on the "email" field.
func EmailEQ(v string) predicate.Human {
	return predicate.Human(sql.FieldEQ(FieldEmail, v))
}

// EmailNEQ applies the NEQ predicate on the "email" field.
func EmailNEQ(v string) predicate.Human {
	return predicate.Human(sql.FieldNEQ(FieldEmail, v))
}

// EmailIn applies the In predicate on the "email" field.
func EmailIn(vs ...string) predicate.Human {
	return predicate.Human(sql.FieldIn(FieldEmail, vs...))
}

// EmailNotIn applies the NotIn predicate on the "email" field.
func EmailNotIn(vs ...string) predicate.Human {
	return predicate.Human(sql.FieldNotIn(FieldEmail, vs...))
}

// EmailGT applies the GT predicate on the "email" field.
func EmailGT(v string) predicate.Human {
	return predicate.Human(sql.FieldGT(FieldEmail, v))
}

// EmailGTE applies the GTE predicate on the "email" field.
func EmailGTE(v string) predicate.Human {
	return predicate.Human(sql.FieldGTE(FieldEmail, v))
}

// EmailLT applies the LT predicate on the "email" field.
func EmailLT(v string) predicate.Human {
	return predicate.Human(sql.FieldLT(FieldEmail, v))
}

// EmailLTE applies the LTE predicate on the "email" field.
func EmailLTE(v string) predicate.Human {
	return predicate.Human(sql.FieldLTE(FieldEmail, v))
}

// EmailContains applies the Contains predicate on the "email" field.
func EmailContains(v string) predicate.Human {
	return predicate.Human(sql.FieldContains(FieldEmail, v))
}

// EmailHasPrefix applies the HasPrefix predicate on the "email" field.
func EmailHasPrefix(v string) predicate.Human {
	return predicate.Human(sql.FieldHasPrefix(FieldEmail, v))
}

// EmailHasSuffix applies the HasSuffix predicate on the "email" field.
func EmailHasSuffix(v string) predicate.Human {
	return predicate.Human(sql.FieldHasSuffix(FieldEmail, v))
}

// EmailEqualFold applies the EqualFold predicate on the "email" field.
func EmailEqualFold(v string) predicate.Human {
	return predicate.Human(sql.FieldEqualFold(FieldEmail, v))
}

// EmailContainsFold applies the ContainsFold predicate on the "email" field.
func EmailContainsFold(v string) predicate.Human {
	return predicate.Human(sql.FieldContainsFold(FieldEmail, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Human {
	return predicate.Human(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Human {
	return predicate.Human(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Human {
	return predicate.Human(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Human {
	return predicate.Human(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Human {
	return predicate.Human(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Human {
	return predicate.Human(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Human {
	return predicate.Human(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Human {
	return predicate.Human(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Human {
	return predicate.Human(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Human {
	return predicate.Human(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Human {
	return predicate.Human(sql.FieldHasSuffix(FieldName, v))
}

// NameIsNil applies the IsNil predicate on the "name" field.
func NameIsNil() predicate.Human {
	return predicate.Human(sql.FieldIsNull(FieldName))
}

// NameNotNil applies the NotNil predicate on the "name" field.
func NameNotNil() predicate.Human {
	return predicate.Human(sql.FieldNotNull(FieldName))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Human {
	return predicate.Human(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Human {
	return predicate.Human(sql.FieldContainsFold(FieldName, v))
}

// PasswordHashEQ applies the EQ predicate on the "password_hash" field.
func PasswordHashEQ(v string) predicate.Human {
	return predicate.Human(sql.FieldEQ(FieldPasswordHash, v))
}

// PasswordHashNEQ applies the NEQ predicate on the "password_hash" field.
func PasswordHashNEQ(v string) predicate.Human {
	return predicate.Human(sql.FieldNEQ(FieldPasswordHash, v))
}

// PasswordHashIn applies the In predicate on the "password_hash" field.
func PasswordHashIn(vs ...string) predicate.Human {
	return predicate.Human(sql.FieldIn(FieldPasswordHash, vs...))
}

// PasswordHashNotIn applies the NotIn predicate on the "password_hash" field.
func PasswordHashNotIn(vs ...string) predicate.Human {
	return predicate.Human(sql.FieldNotIn(FieldPasswordHash, vs...))
}

// PasswordHashGT applies the GT predicate on the "password_hash" field.
func PasswordHashGT(v string) predicate.Human {
	return predicate.Human(sql.FieldGT(FieldPasswordHash, v))
}

// PasswordHashGTE applies the GTE predicate on the "password_hash" field.
func PasswordHashGTE(v string) predicate.Human {
	return predicate.Human(sql.FieldGTE(FieldPasswordHash, v))
}

// PasswordHashLT applies the LT predicate on the "password_hash" field.
func PasswordHashLT(v string) predicate.Human {
	return predicate.Human(sql.FieldLT(FieldPasswordHash, v))
}

// PasswordHashLTE applies the LTE predicate on the "password_hash" field.
func PasswordHashLTE(v string) predicate.Human {
	return predicate.Human(sql.FieldLTE(FieldPasswordHash, v))
}

// PasswordHashContains applies the Contains predicate on the "password_hash" field.
func PasswordHashContains(v string) predicate.Human {
	return predicate.Human(sql.FieldContains(FieldPasswordHash, v))
}

// PasswordHashHasPrefix applies the HasPrefix predicate on the "password_hash" field.
func PasswordHashHasPrefix(v string) predicate.Human {
	return predicate.Human(sql.FieldHasPrefix(FieldPasswordHash, v))
}

// PasswordHashHasSuffix applies the HasSuffix predicate on the "password_hash" field.
func PasswordHashHasSuffix(v string) predicate.Human {
	return predicate.Human(sql.FieldHasSuffix(FieldPasswordHash, v))
}

// PasswordHashIsNil applies the IsNil predicate on the "password_hash" field.
func PasswordHashIsNil() predicate.Human {
	return predicate.Human(sql.FieldIsNull(FieldPasswordHash))
}

// PasswordHashNotNil applies the NotNil predicate on the "password_hash" field.
func PasswordHashNotNil() predicate.Human {
	return predicate.Human(sql.FieldNotNull(FieldPasswordHash))
}

// PasswordHashEqualFold applies the EqualFold predicate on the "password_hash" field.
func PasswordHashEqualFold(v string) predicate.Human {
	return predicate.Human(sql.FieldEqualFold(FieldPasswordHash, v))
}

// PasswordHashContainsFold applies the ContainsFold predicate on the "password_hash" field.
func PasswordHashContainsFold(v string) predicate.Human {
	return predicate.Human(sql.FieldContainsFold(FieldPasswordHash, v))
}

// AvatarURLEQ applies the EQ predicate on the "avatar_url" field.
func AvatarURLEQ(v string) predicate.Human {
	return predicate.Human(sql.FieldEQ(FieldAvatarURL, v))
}

// AvatarURLNEQ applies the NEQ predicate on the "avatar_url" field.
func AvatarURLNEQ(v string) predicate.Human {
	return predicate.Human(sql.FieldNEQ(FieldAvatarURL, v))
}

// AvatarURLIn applies the In predicate on the "avatar_url" field.
func AvatarURLIn(vs ...string) predicate.Human {
	return predicate.Human(sql.FieldIn(FieldAvatarURL, vs...))
}

// AvatarURLNotIn applies the NotIn predicate on the "avatar_url" field.
func AvatarURLNotIn(vs ...string) predicate.Human {
	return predicate.Human(sql.FieldNotIn(FieldAvatarURL, vs...))
}

// AvatarURLGT applies the GT predicate on the "avatar_url" field.
func AvatarURLGT(v string) predicate.Human {
	return predicate.Human(sql.FieldGT(FieldAvatarURL, v))
}

// AvatarURLGTE applies the GTE predicate on the "avatar_url" field.
func AvatarURLGTE(v string) predicate.Human {
	return predicate.Human(sql.FieldGTE(FieldAvatarURL, v))
}

// AvatarURLLT applies the LT predicate on the "avatar_url" field.
func AvatarURLLT(v string) predicate.Human {
	return predicate.Human(sql.FieldLT(FieldAvatarURL, v))
}

// AvatarURLLTE applies the LTE predicate on the "avatar_url" field.
func AvatarURLLTE(v string) predicate.Human {
	return predicate.Human(sql.FieldLTE(FieldAvatarURL, v))
}

// AvatarURLContains applies the Contains predicate on the "avatar_url" field.
func AvatarURLContains(v string) predicate.Human {
	return predicate.Human(sql.FieldContains(FieldAvatarURL, v))
}

// AvatarURLHasPrefix applies the HasPrefix predicate on the "avatar_url" field.
func AvatarURLHasPrefix(v string) predicate.Human {
	return predicate.Human(sql.FieldHasPrefix(FieldAvatarURL, v))
}

// AvatarURLHasSuffix applies the HasSuffix predicate on the "avatar_url" field.
func AvatarURLHasSuffix(v string) predicate.Human {
	return predicate.Human(sql.FieldHasSuffix(FieldAvatarURL, v))
}

// AvatarURLIsNil applies the IsNil predicate on the "avatar_url" field.
func AvatarURLIsNil() predicate.Human {
	return predicate.Human(sql.FieldIsNull(FieldAvatarURL))
}

// AvatarURLNotNil applies the NotNil predicate on the "avatar_url" field.
func AvatarURLNotNil() predicate.Human {
	return predicate.Human(sql.FieldNotNull(FieldAvatarURL))
}

// AvatarURLEqualFold applies the EqualFold predicate on the "avatar_url" field.
func AvatarURLEqualFold(v string) predicate.Human {
	return predicate.Human(sql.FieldEqualFold(FieldAvatarURL, v))
}

// AvatarURLContainsFold applies the ContainsFold predicate on the "avatar_url" field.
func AvatarURLContainsFold(v string) predicate.Human {
	return predicate.Human(sql.FieldContainsFold(FieldAvatarURL, v))
}

// IsPlatformAdminEQ applies the EQ predicate on the "is_platform_admin" field.
func IsPlatformAdminEQ(v bool) predicate.Human {
	return predicate.Human(sql.FieldEQ(FieldIsPlatformAdmin, v))
}

// IsPlatformAdminNEQ applies the NEQ predicate on the "is_platform_admin" field.
func IsPlatformAdminNEQ(v bool) predicate.Human {
	return predicate.Human(sql.FieldNEQ(FieldIsPlatformAdmin, v))
}

// LastLoginAtEQ applies the EQ predicate on the "last_login_at" field.
func LastLoginAtEQ(v time.Time) predicate.Human {
	return predicate.Human(sql.FieldEQ(FieldLastLoginAt, v))
}

// LastLoginAtNEQ applies the NEQ predicate on the "last_login_at" field.
func LastLoginAtNEQ(v time.Time) predicate.Human {
	return predicate.Human(sql.FieldNEQ(FieldLastLoginAt, v))
}

// LastLoginAtIn applies the In predicate on the "last_login_at" field.
func LastLoginAtIn(vs ...time.Time) predicate.Human {
	return predicate.Human(sql.FieldIn(FieldLastLoginAt, vs...))
}

// LastLoginAtNotIn applies the NotIn predicate on the "last_login_at" field.
func LastLoginAtNotIn(vs ...time.Time) predicate.Human {
	return predicate.Human(sql.FieldNotIn(FieldLastLoginAt, vs...))
}

// LastLoginAtGT applies the GT predicate on the "last_login_at" field.
func LastLoginAtGT(v time.Time) predicate.Human {
	return predicate.Human(sql.FieldGT(FieldLastLoginAt, v))
}

// LastLoginAtGTE applies the GTE predicate on the "last_login_at" field.
func LastLoginAtGTE(v time.Time) predicate.Human {
	return predicate.Human(sql.FieldGTE(FieldLastLoginAt, v))
}

// LastLoginAtLT applies the LT predicate on the "last_login_at" field.
func LastLoginAtLT(v time.Time) predicate.Human {
	return predicate.Human(sql.FieldLT(FieldLastLoginAt, v))
}

// LastLoginAtLTE applies the LTE predicate on the "last_login_at" field.
func LastLoginAtLTE(v time.Time) predicate.Human {
	return predicate.Human(sql.FieldLTE(FieldLastLoginAt, v))
}

// LastLoginAtIsNil applies the IsNil predicate on the "last_login_at" field.
func LastLoginAtIsNil() predicate.Human {
	return predicate.Human(sql.FieldIsNull(FieldLastLoginAt))
}

// LastLoginAtNotNil applies the NotNil predicate on the "last_login_at" field.
func LastLoginAtNotNil() predicate.Human {
	return predicate.Human(sql.FieldNotNull(FieldLastLoginAt))
}

// EmailVerifiedAtEQ applies the EQ predicate on the "email_verified_at" field.
func EmailVerifiedAtEQ(v time.Time) predicate.Human {
	return predicate.Human(sql.FieldEQ(FieldEmailVerifiedAt, v))
}

// EmailVerifiedAtNEQ applies the NEQ predicate on the "email_verified_at" field.
func EmailVerifiedAtNEQ(v time.Time) predicate.Human {
	return predicate.Human(sql.FieldNEQ(FieldEmailVerifiedAt, v))
}

// EmailVerifiedAtIn applies the In predicate on the "email_verified_at" field.
func EmailVerifiedAtIn(vs ...time.Time) predicate.Human {
	return predicate.Human(sql.FieldIn(FieldEmailVerifiedAt, vs...))
}

// EmailVerifiedAtNotIn applies the NotIn predicate on the "email_verified_at" field.
func EmailVerifiedAtNotIn(vs ...time.Time) predicate.Human {
	return predicate.Human(sql.FieldNotIn(FieldEmailVerifiedAt, vs...))
}

// EmailVerifiedAtGT applies the GT predicate on the "email_verified_at" field.
func EmailVerifiedAtGT(v time.Time) predicate.Human {
	return predicate.Human(sql.FieldGT(FieldEmailVerifiedAt, v))
}

// EmailVerifiedAtGTE applies the GTE predicate on the "email_verified_at" field.
func EmailVerifiedAtGTE(v time.Time) predicate.Human {
	return predicate.Human(sql.FieldGTE(FieldEmailVerifiedAt, v))
}

// EmailVerifiedAtLT applies the LT predicate on the "email_verified_at" field.
func EmailVerifiedAtLT(v time.Time) predicate.Human {
	return predicate.Human(sql.FieldLT(FieldEmailVerifiedAt, v))
}

// EmailVerifiedAtLTE applies the LTE predicate on the "email_verified_at" field.
func EmailVerifiedAtLTE(v time.Time) predicate.Human {
	return predicate.Human(sql.FieldLTE(FieldEmailVerifiedAt, v))
}

// EmailVerifiedAtIsNil applies the IsNil predicate on the "email_verified_at" field.
func EmailVerifiedAtIsNil() predicate.Human {
	return predicate.Human(sql.FieldIsNull(FieldEmailVerifiedAt))
}

// EmailVerifiedAtNotNil applies the NotNil predicate on the "email_verified_at" field.
func EmailVerifiedAtNotNil() predicate.Human {
	return predicate.Human(sql.FieldNotNull(FieldEmailVerifiedAt))
}

// SlugEQ applies the EQ predicate on the "slug" field.
func SlugEQ(v string) predicate.Human {
	return predicate.Human(sql.FieldEQ(FieldSlug, v))
}

// SlugNEQ applies the NEQ predicate on the "slug" field.
func SlugNEQ(v string) predicate.Human {
	return predicate.Human(sql.FieldNEQ(FieldSlug, v))
}

// SlugIn applies the In predicate on the "slug" field.
func SlugIn(vs ...string) predicate.Human {
	return predicate.Human(sql.FieldIn(FieldSlug, vs...))
}

// SlugNotIn applies the NotIn predicate on the "slug" field.
func SlugNotIn(vs ...string) predicate.Human {
	return predicate.Human(sql.FieldNotIn(FieldSlug, vs...))
}

// SlugGT applies the GT predicate on the "slug" field.
func SlugGT(v string) predicate.Human {
	return predicate.Human(sql.FieldGT(FieldSlug, v))
}

// SlugGTE applies the GTE predicate on the "slug" field.
func SlugGTE(v string) predicate.Human {
	return predicate.Human(sql.FieldGTE(FieldSlug, v))
}

// SlugLT applies the LT predicate on the "slug" field.
func SlugLT(v string) predicate.Human {
	return predicate.Human(sql.FieldLT(FieldSlug, v))
}

// SlugLTE applies the LTE predicate on the "slug" field.
func SlugLTE(v string) predicate.Human {
	return predicate.Human(sql.FieldLTE(FieldSlug, v))
}

// SlugContains applies the Contains predicate on the "slug" field.
func SlugContains(v string) predicate.Human {
	return predicate.Human(sql.FieldContains(FieldSlug, v))
}

// SlugHasPrefix applies the HasPrefix predicate on the "slug" field.
func SlugHasPrefix(v string) predicate.Human {
	return predicate.Human(sql.FieldHasPrefix(FieldSlug, v))
}

// SlugHasSuffix applies the HasSuffix predicate on the "slug" field.
func SlugHasSuffix(v string) predicate.Human {
	return predicate.Human(sql.FieldHasSuffix(FieldSlug, v))
}

// SlugIsNil applies the IsNil predicate on the "slug" field.
func SlugIsNil() predicate.Human {
	return predicate.Human(sql.FieldIsNull(FieldSlug))
}

// SlugNotNil applies the NotNil predicate on the "slug" field.
func SlugNotNil() predicate.Human {
	return predicate.Human(sql.FieldNotNull(FieldSlug))
}

// SlugEqualFold applies the EqualFold predicate on the "slug" field.
func SlugEqualFold(v string) predicate.Human {
	return predicate.Human(sql.FieldEqualFold(FieldSlug, v))
}

// SlugContainsFold applies the ContainsFold predicate on the "slug" field.
func SlugContainsFold(v string) predicate.Human {
	return predicate.Human(sql.FieldContainsFold(FieldSlug, v))
}

// HeadlineEQ applies the EQ predicate on the "headline" field.
func HeadlineEQ(v string) predicate.Human {
	return predicate.Human(sql.FieldEQ(FieldHeadline, v))
}

// HeadlineNEQ applies the NEQ predicate on the "headline" field.
func HeadlineNEQ(v string) predicate.Human {
	return predicate.Human(sql.FieldNEQ(FieldHeadline, v))
}

// HeadlineIn applies the In predicate on the "headline" field.
func HeadlineIn(vs ...string) predicate.Human {
	return predicate.Human(sql.FieldIn(FieldHeadline, vs...))
}

// HeadlineNotIn applies the NotIn predicate on the "headline" field.
func HeadlineNotIn(vs ...string) predicate.Human {
	return predicate.Human(sql.FieldNotIn(FieldHeadline, vs...))
}

// HeadlineGT applies the GT predicate on the "headline" field.
func HeadlineGT(v string) predicate.Human {
	return predicate.Human(sql.FieldGT(FieldHeadline, v))
}

// HeadlineGTE applies the GTE predicate on the "headline" field.
func HeadlineGTE(v string) predicate.Human {
	return predicate.Human(sql.FieldGTE(FieldHeadline, v))
}

// HeadlineLT applies the LT predicate on the "headline" field.
func HeadlineLT(v string) predicate.Human {
	return predicate.Human(sql.FieldLT(FieldHeadline, v))
}

// HeadlineLTE applies the LTE predicate on the "headline" field.
func HeadlineLTE(v string) predicate.Human {
	return predicate.Human(sql.FieldLTE(FieldHeadline, v))
}

// HeadlineContains applies the Contains predicate on the "headline" field.
func HeadlineContains(v string) predicate.Human {
	return predicate.Human(sql.FieldContains(FieldHeadline, v))
}

// HeadlineHasPrefix applies the HasPrefix predicate on the "headline" field.
func HeadlineHasPrefix(v string) predicate.Human {
	return predicate.Human(sql.FieldHasPrefix(FieldHeadline, v))
}

// HeadlineHasSuffix applies the HasSuffix predicate on the "headline" field.
func HeadlineHasSuffix(v string) predicate.Human {
	return predicate.Human(sql.FieldHasSuffix(FieldHeadline, v))
}

// HeadlineIsNil applies the IsNil predicate on the "headline" field.
func HeadlineIsNil() predicate.Human {
	return predicate.Human(sql.FieldIsNull(FieldHeadline))
}

// HeadlineNotNil applies the NotNil predicate on the "headline" field.
func HeadlineNotNil() predicate.Human {
	return predicate.Human(sql.FieldNotNull(FieldHeadline))
}

// HeadlineEqualFold applies the EqualFold predicate on the "headline" field.
func HeadlineEqualFold(v string) predicate.Human {
	return predicate.Human(sql.FieldEqualFold(FieldHeadline, v))
}

// HeadlineContainsFold applies the ContainsFold predicate on the "headline" field.
func HeadlineContainsFold(v string) predicate.Human {
	return predicate.Human(sql.FieldContainsFold(FieldHeadline, v))
}

// BioEQ applies the EQ predicate on the "bio" field.
func BioEQ(v string) predicate.Human {
	return predicate.Human(sql.FieldEQ(FieldBio, v))
}

// BioNEQ applies the NEQ predicate on the "bio" field.
func BioNEQ(v string) predicate.Human {
	return predicate.Human(sql.FieldNEQ(FieldBio, v))
}

// BioIn applies the In predicate on the "bio" field.
func BioIn(vs ...string) predicate.Human {
	return predicate.Human(sql.FieldIn(FieldBio, vs...))
}

// BioNotIn applies the NotIn predicate on the "bio" field.
func BioNotIn(vs ...string) predicate.Human {
	return predicate.Human(sql.FieldNotIn(FieldBio, vs...))
}

// BioGT applies the GT predicate on the "bio" field.
func BioGT(v string) predicate.Human {
	return predicate.Human(sql.FieldGT(FieldBio, v))
}

// BioGTE applies the GTE predicate on the "bio" field.
func BioGTE(v string) predicate.Human {
	return predicate.Human(sql.FieldGTE(FieldBio, v))
}

// BioLT applies the LT predicate on the "bio" field.
func BioLT(v string) predicate.Human {
	return predicate.Human(sql.FieldLT(FieldBio, v))
}

// BioLTE applies the LTE predicate on the "bio" field.
func BioLTE(v string) predicate.Human {
	return predicate.Human(sql.FieldLTE(FieldBio, v))
}

// BioContains applies the Contains predicate on the "bio" field.
func BioContains(v string) predicate.Human {
	return predicate.Human(sql.FieldContains(FieldBio, v))
}

// BioHasPrefix applies the HasPrefix predicate on the "bio" field.
func BioHasPrefix(v string) predicate.Human {
	return predicate.Human(sql.FieldHasPrefix(FieldBio, v))
}

// BioHasSuffix applies the HasSuffix predicate on the "bio" field.
func BioHasSuffix(v string) predicate.Human {
	return predicate.Human(sql.FieldHasSuffix(FieldBio, v))
}

// BioIsNil applies the IsNil predicate on the "bio" field.
func BioIsNil() predicate.Human {
	return predicate.Human(sql.FieldIsNull(FieldBio))
}

// BioNotNil applies the NotNil predicate on the "bio" field.
func BioNotNil() predicate.Human {
	return predicate.Human(sql.FieldNotNull(FieldBio))
}

// BioEqualFold applies the EqualFold predicate on the "bio" field.
func BioEqualFold(v string) predicate.Human {
	return predicate.Human(sql.FieldEqualFold(FieldBio, v))
}

// BioContainsFold applies the ContainsFold predicate on the "bio" field.
func BioContainsFold(v string) predicate.Human {
	return predicate.Human(sql.FieldContainsFold(FieldBio, v))
}

// LinkedinURLEQ applies the EQ predicate on the "linkedin_url" field.
func LinkedinURLEQ(v string) predicate.Human {
	return predicate.Human(sql.FieldEQ(FieldLinkedinURL, v))
}

// LinkedinURLNEQ applies the NEQ predicate on the "linkedin_url" field.
func LinkedinURLNEQ(v string) predicate.Human {
	return predicate.Human(sql.FieldNEQ(FieldLinkedinURL, v))
}

// LinkedinURLIn applies the In predicate on the "linkedin_url" field.
func LinkedinURLIn(vs ...string) predicate.Human {
	return predicate.Human(sql.FieldIn(FieldLinkedinURL, vs...))
}

// LinkedinURLNotIn applies the NotIn predicate on the "linkedin_url" field.
func LinkedinURLNotIn(vs ...string) predicate.Human {
	return predicate.Human(sql.FieldNotIn(FieldLinkedinURL, vs...))
}

// LinkedinURLGT applies the GT predicate on the "linkedin_url" field.
func LinkedinURLGT(v string) predicate.Human {
	return predicate.Human(sql.FieldGT(FieldLinkedinURL, v))
}

// LinkedinURLGTE applies the GTE predicate on the "linkedin_url" field.
func LinkedinURLGTE(v string) predicate.Human {
	return predicate.Human(sql.FieldGTE(FieldLinkedinURL, v))
}

// LinkedinURLLT applies the LT predicate on the "linkedin_url" field.
func LinkedinURLLT(v string) predicate.Human {
	return predicate.Human(sql.FieldLT(FieldLinkedinURL, v))
}

// LinkedinURLLTE applies the LTE predicate on the "linkedin_url" field.
func LinkedinURLLTE(v string) predicate.Human {
	return predicate.Human(sql.FieldLTE(FieldLinkedinURL, v))
}

// LinkedinURLContains applies the Contains predicate on the "linkedin_url" field.
func LinkedinURLContains(v string) predicate.Human {
	return predicate.Human(sql.FieldContains(FieldLinkedinURL, v))
}

// LinkedinURLHasPrefix applies the HasPrefix predicate on the "linkedin_url" field.
func LinkedinURLHasPrefix(v string) predicate.Human {
	return predicate.Human(sql.FieldHasPrefix(FieldLinkedinURL, v))
}

// LinkedinURLHasSuffix applies the HasSuffix predicate on the "linkedin_url" field.
func LinkedinURLHasSuffix(v string) predicate.Human {
	return predicate.Human(sql.FieldHasSuffix(FieldLinkedinURL, v))
}

// LinkedinURLIsNil applies the IsNil predicate on the "linkedin_url" field.
func LinkedinURLIsNil() predicate.Human {
	return predicate.Human(sql.FieldIsNull(FieldLinkedinURL))
}

// LinkedinURLNotNil applies the NotNil predicate on the "linkedin_url" field.
func LinkedinURLNotNil() predicate.Human {
	return predicate.Human(sql.FieldNotNull(FieldLinkedinURL))
}

// LinkedinURLEqualFold applies the EqualFold predicate on the "linkedin_url" field.
func LinkedinURLEqualFold(v string) predicate.Human {
	return predicate.Human(sql.FieldEqualFold(FieldLinkedinURL, v))
}

// LinkedinURLContainsFold applies the ContainsFold predicate on the "linkedin_url" field.
func LinkedinURLContainsFold(v string) predicate.Human {
	return predicate.Human(sql.FieldContainsFold(FieldLinkedinURL, v))
}

// GithubURLEQ applies the EQ predicate on the "github_url" field.
func GithubURLEQ(v string) predicate.Human {
	return predicate.Human(sql.FieldEQ(FieldGithubURL, v))
}

// GithubURLNEQ applies the NEQ predicate on the "github_url" field.
func GithubURLNEQ(v string) predicate.Human {
	return predicate.Human(sql.FieldNEQ(FieldGithubURL, v))
}

// GithubURLIn applies the In predicate on the "github_url" field.
func GithubURLIn(vs ...string) predicate.Human {
	return predicate.Human(sql.FieldIn(FieldGithubURL, vs...))
}

// GithubURLNotIn applies the NotIn predicate on the "github_url" field.
func GithubURLNotIn(vs ...string) predicate.Human {
	return predicate.Human(sql.FieldNotIn(FieldGithubURL, vs...))
}

// GithubURLGT applies the GT predicate on the "github_url" field.
func GithubURLGT(v string) predicate.Human {
	return predicate.Human(sql.FieldGT(FieldGithubURL, v))
}

// GithubURLGTE applies the GTE predicate on the "github_url" field.
func GithubURLGTE(v string) predicate.Human {
	return predicate.Human(sql.FieldGTE(FieldGithubURL, v))
}

// GithubURLLT applies the LT predicate on the "github_url" field.
func GithubURLLT(v string) predicate.Human {
	return predicate.Human(sql.FieldLT(FieldGithubURL, v))
}

// GithubURLLTE applies the LTE predicate on the "github_url" field.
func GithubURLLTE(v string) predicate.Human {
	return predicate.Human(sql.FieldLTE(FieldGithubURL, v))
}

// GithubURLContains applies the Contains predicate on the "github_url" field.
func GithubURLContains(v string) predicate.Human {
	return predicate.Human(sql.FieldContains(FieldGithubURL, v))
}

// GithubURLHasPrefix applies the HasPrefix predicate on the "github_url" field.
func GithubURLHasPrefix(v string) predicate.Human {
	return predicate.Human(sql.FieldHasPrefix(FieldGithubURL, v))
}

// GithubURLHasSuffix applies the HasSuffix predicate on the "github_url" field.
func GithubURLHasSuffix(v string) predicate.Human {
	return predicate.Human(sql.FieldHasSuffix(FieldGithubURL, v))
}

// GithubURLIsNil applies the IsNil predicate on the "github_url" field.
func GithubURLIsNil() predicate.Human {
	return predicate.Human(sql.FieldIsNull(FieldGithubURL))
}

// GithubURLNotNil applies the NotNil predicate on the "github_url" field.
func GithubURLNotNil() predicate.Human {
	return predicate.Human(sql.FieldNotNull(FieldGithubURL))
}

// GithubURLEqualFold applies the EqualFold predicate on the "github_url" field.
func GithubURLEqualFold(v string) predicate.Human {
	return predicate.Human(sql.FieldEqualFold(FieldGithubURL, v))
}

// GithubURLContainsFold applies the ContainsFold predicate on the "github_url" field.
func GithubURLContainsFold(v string) predicate.Human {
	return predicate.Human(sql.FieldContainsFold(FieldGithubURL, v))
}

// TwitterURLEQ applies the EQ predicate on the "twitter_url" field.
func TwitterURLEQ(v string) predicate.Human {
	return predicate.Human(sql.FieldEQ(FieldTwitterURL, v))
}

// TwitterURLNEQ applies the NEQ predicate on the "twitter_url" field.
func TwitterURLNEQ(v string) predicate.Human {
	return predicate.Human(sql.FieldNEQ(FieldTwitterURL, v))
}

// TwitterURLIn applies the In predicate on the "twitter_url" field.
func TwitterURLIn(vs ...string) predicate.Human {
	return predicate.Human(sql.FieldIn(FieldTwitterURL, vs...))
}

// TwitterURLNotIn applies the NotIn predicate on the "twitter_url" field.
func TwitterURLNotIn(vs ...string) predicate.Human {
	return predicate.Human(sql.FieldNotIn(FieldTwitterURL, vs...))
}

// TwitterURLGT applies the GT predicate on the "twitter_url" field.
func TwitterURLGT(v string) predicate.Human {
	return predicate.Human(sql.FieldGT(FieldTwitterURL, v))
}

// TwitterURLGTE applies the GTE predicate on the "twitter_url" field.
func TwitterURLGTE(v string) predicate.Human {
	return predicate.Human(sql.FieldGTE(FieldTwitterURL, v))
}

// TwitterURLLT applies the LT predicate on the "twitter_url" field.
func TwitterURLLT(v string) predicate.Human {
	return predicate.Human(sql.FieldLT(FieldTwitterURL, v))
}

// TwitterURLLTE applies the LTE predicate on the "twitter_url" field.
func TwitterURLLTE(v string) predicate.Human {
	return predicate.Human(sql.FieldLTE(FieldTwitterURL, v))
}

// TwitterURLContains applies the Contains predicate on the "twitter_url" field.
func TwitterURLContains(v string) predicate.Human {
	return predicate.Human(sql.FieldContains(FieldTwitterURL, v))
}

// TwitterURLHasPrefix applies the HasPrefix predicate on the "twitter_url" field.
func TwitterURLHasPrefix(v string) predicate.Human {
	return predicate.Human(sql.FieldHasPrefix(FieldTwitterURL, v))
}

// TwitterURLHasSuffix applies the HasSuffix predicate on the "twitter_url" field.
func TwitterURLHasSuffix(v string) predicate.Human {
	return predicate.Human(sql.FieldHasSuffix(FieldTwitterURL, v))
}

// TwitterURLIsNil applies the IsNil predicate on the "twitter_url" field.
func TwitterURLIsNil() predicate.Human {
	return predicate.Human(sql.FieldIsNull(FieldTwitterURL))
}

// TwitterURLNotNil applies the NotNil predicate on the "twitter_url" field.
func TwitterURLNotNil() predicate.Human {
	return predicate.Human(sql.FieldNotNull(FieldTwitterURL))
}

// TwitterURLEqualFold applies the EqualFold predicate on the "twitter_url" field.
func TwitterURLEqualFold(v string) predicate.Human {
	return predicate.Human(sql.FieldEqualFold(FieldTwitterURL, v))
}

// TwitterURLContainsFold applies the ContainsFold predicate on the "twitter_url" field.
func TwitterURLContainsFold(v string) predicate.Human {
	return predicate.Human(sql.FieldContainsFold(FieldTwitterURL, v))
}

// WebsiteURLEQ applies the EQ predicate on the "website_url" field.
func WebsiteURLEQ(v string) predicate.Human {
	return predicate.Human(sql.FieldEQ(FieldWebsiteURL, v))
}

// WebsiteURLNEQ applies the NEQ predicate on the "website_url" field.
func WebsiteURLNEQ(v string) predicate.Human {
	return predicate.Human(sql.FieldNEQ(FieldWebsiteURL, v))
}

// WebsiteURLIn applies the In predicate on the "website_url" field.
func WebsiteURLIn(vs ...string) predicate.Human {
	return predicate.Human(sql.FieldIn(FieldWebsiteURL, vs...))
}

// WebsiteURLNotIn applies the NotIn predicate on the "website_url" field.
func WebsiteURLNotIn(vs ...string) predicate.Human {
	return predicate.Human(sql.FieldNotIn(FieldWebsiteURL, vs...))
}

// WebsiteURLGT applies the GT predicate on the "website_url" field.
func WebsiteURLGT(v string) predicate.Human {
	return predicate.Human(sql.FieldGT(FieldWebsiteURL, v))
}

// WebsiteURLGTE applies the GTE predicate on the "website_url" field.
func WebsiteURLGTE(v string) predicate.Human {
	return predicate.Human(sql.FieldGTE(FieldWebsiteURL, v))
}

// WebsiteURLLT applies the LT predicate on the "website_url" field.
func WebsiteURLLT(v string) predicate.Human {
	return predicate.Human(sql.FieldLT(FieldWebsiteURL, v))
}

// WebsiteURLLTE applies the LTE predicate on the "website_url" field.
func WebsiteURLLTE(v string) predicate.Human {
	return predicate.Human(sql.FieldLTE(FieldWebsiteURL, v))
}

// WebsiteURLContains applies the Contains predicate on the "website_url" field.
func WebsiteURLContains(v string) predicate.Human {
	return predicate.Human(sql.FieldContains(FieldWebsiteURL, v))
}

// WebsiteURLHasPrefix applies the HasPrefix predicate on the "website_url" field.
func WebsiteURLHasPrefix(v string) predicate.Human {
	return predicate.Human(sql.FieldHasPrefix(FieldWebsiteURL, v))
}

// WebsiteURLHasSuffix applies the HasSuffix predicate on the "website_url" field.
func WebsiteURLHasSuffix(v string) predicate.Human {
	return predicate.Human(sql.FieldHasSuffix(FieldWebsiteURL, v))
}

// WebsiteURLIsNil applies the IsNil predicate on the "website_url" field.
func WebsiteURLIsNil() predicate.Human {
	return predicate.Human(sql.FieldIsNull(FieldWebsiteURL))
}

// WebsiteURLNotNil applies the NotNil predicate on the "website_url" field.
func WebsiteURLNotNil() predicate.Human {
	return predicate.Human(sql.FieldNotNull(FieldWebsiteURL))
}

// WebsiteURLEqualFold applies the EqualFold predicate on the "website_url" field.
func WebsiteURLEqualFold(v string) predicate.Human {
	return predicate.Human(sql.FieldEqualFold(FieldWebsiteURL, v))
}

// WebsiteURLContainsFold applies the ContainsFold predicate on the "website_url" field.
func WebsiteURLContainsFold(v string) predicate.Human {
	return predicate.Human(sql.FieldContainsFold(FieldWebsiteURL, v))
}

// PublicProfileEQ applies the EQ predicate on the "public_profile" field.
func PublicProfileEQ(v bool) predicate.Human {
	return predicate.Human(sql.FieldEQ(FieldPublicProfile, v))
}

// PublicProfileNEQ applies the NEQ predicate on the "public_profile" field.
func PublicProfileNEQ(v bool) predicate.Human {
	return predicate.Human(sql.FieldNEQ(FieldPublicProfile, v))
}

// HasPrincipal applies the HasEdge predicate on the "principal" edge.
func HasPrincipal() predicate.Human {
	return predicate.Human(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, PrincipalTable, PrincipalColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPrincipalWith applies the HasEdge predicate on the "principal" edge with a given conditions (other predicates).
func HasPrincipalWith(preds ...predicate.Principal) predicate.Human {
	return predicate.Human(func(s *sql.Selector) {
		step := newPrincipalStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Human) predicate.Human {
	return predicate.Human(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Human) predicate.Human {
	return predicate.Human(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Human) predicate.Human {
	return predicate.Human(sql.NotPredicates(p))
}
