// Code generated by ent, DO NOT EDIT.

package savedquery

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/plexusone/dashforge/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldEQ(FieldName, v))
}

// Slug applies equality check predicate on the "slug" field. It's identical to SlugEQ.
func Slug(v string) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldEQ(FieldSlug, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldEQ(FieldDescription, v))
}

// Query applies equality check predicate on the "query" field. It's identical to QueryEQ.
func Query(v string) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldEQ(FieldQuery, v))
}

// DatasourceSlug applies equality check predicate on the "datasource_slug" field. It's identical to DatasourceSlugEQ.
func DatasourceSlug(v string) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldEQ(FieldDatasourceSlug, v))
}

// CacheTTLSeconds applies equality check predicate on the "cache_ttl_seconds" field. It's identical to CacheTTLSecondsEQ.
func CacheTTLSeconds(v int) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldEQ(FieldCacheTTLSeconds, v))
}

// LastRunAt applies equality check predicate on the "last_run_at" field. It's identical to LastRunAtEQ.
func LastRunAt(v time.Time) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldEQ(FieldLastRunAt, v))
}

// LastRunDurationMs applies equality check predicate on the "last_run_duration_ms" field. It's identical to LastRunDurationMsEQ.
func LastRunDurationMs(v int64) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldEQ(FieldLastRunDurationMs, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldEQ(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldContainsFold(FieldName, v))
}

// SlugEQ applies the EQ predicate on the "slug" field.
func SlugEQ(v string) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldEQ(FieldSlug, v))
}

// SlugNEQ applies the NEQ predicate on the "slug" field.
func SlugNEQ(v string) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldNEQ(FieldSlug, v))
}

// SlugIn applies the In predicate on the "slug" field.
func SlugIn(vs ...string) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldIn(FieldSlug, vs...))
}

// SlugNotIn applies the NotIn predicate on the "slug" field.
func SlugNotIn(vs ...string) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldNotIn(FieldSlug, vs...))
}

// SlugGT applies the GT predicate on the "slug" field.
func SlugGT(v string) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldGT(FieldSlug, v))
}

// SlugGTE applies the GTE predicate on the "slug" field.
func SlugGTE(v string) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldGTE(FieldSlug, v))
}

// SlugLT applies the LT predicate on the "slug" field.
func SlugLT(v string) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldLT(FieldSlug, v))
}

// SlugLTE applies the LTE predicate on the "slug" field.
func SlugLTE(v string) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldLTE(FieldSlug, v))
}

// SlugContains applies the Contains predicate on the "slug" field.
func SlugContains(v string) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldContains(FieldSlug, v))
}

// SlugHasPrefix applies the HasPrefix predicate on the "slug" field.
func SlugHasPrefix(v string) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldHasPrefix(FieldSlug, v))
}

// SlugHasSuffix applies the HasSuffix predicate on the "slug" field.
func SlugHasSuffix(v string) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldHasSuffix(FieldSlug, v))
}

// SlugEqualFold applies the EqualFold predicate on the "slug" field.
func SlugEqualFold(v string) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldEqualFold(FieldSlug, v))
}

// SlugContainsFold applies the ContainsFold predicate on the "slug" field.
func SlugContainsFold(v string) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldContainsFold(FieldSlug, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldContainsFold(FieldDescription, v))
}

// QueryEQ applies the EQ predicate on the "query" field.
func QueryEQ(v string) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldEQ(FieldQuery, v))
}

// QueryNEQ applies the NEQ predicate on the "query" field.
func QueryNEQ(v string) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldNEQ(FieldQuery, v))
}

// QueryIn applies the In predicate on the "query" field.
func QueryIn(vs ...string) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldIn(FieldQuery, vs...))
}

// QueryNotIn applies the NotIn predicate on the "query" field.
func QueryNotIn(vs ...string) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldNotIn(FieldQuery, vs...))
}

// QueryGT applies the GT predicate on the "query" field.
func QueryGT(v string) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldGT(FieldQuery, v))
}

// QueryGTE applies the GTE predicate on the "query" field.
func QueryGTE(v string) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldGTE(FieldQuery, v))
}

// QueryLT applies the LT predicate on the "query" field.
func QueryLT(v string) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldLT(FieldQuery, v))
}

// QueryLTE applies the LTE predicate on the "query" field.
func QueryLTE(v string) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldLTE(FieldQuery, v))
}

// QueryContains applies the Contains predicate on the "query" field.
func QueryContains(v string) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldContains(FieldQuery, v))
}

// QueryHasPrefix applies the HasPrefix predicate on the "query" field.
func QueryHasPrefix(v string) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldHasPrefix(FieldQuery, v))
}

// QueryHasSuffix applies the HasSuffix predicate on the "query" field.
func QueryHasSuffix(v string) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldHasSuffix(FieldQuery, v))
}

// QueryEqualFold applies the EqualFold predicate on the "query" field.
func QueryEqualFold(v string) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldEqualFold(FieldQuery, v))
}

// QueryContainsFold applies the ContainsFold predicate on the "query" field.
func QueryContainsFold(v string) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldContainsFold(FieldQuery, v))
}

// DatasourceSlugEQ applies the EQ predicate on the "datasource_slug" field.
func DatasourceSlugEQ(v string) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldEQ(FieldDatasourceSlug, v))
}

// DatasourceSlugNEQ applies the NEQ predicate on the "datasource_slug" field.
func DatasourceSlugNEQ(v string) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldNEQ(FieldDatasourceSlug, v))
}

// DatasourceSlugIn applies the In predicate on the "datasource_slug" field.
func DatasourceSlugIn(vs ...string) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldIn(FieldDatasourceSlug, vs...))
}

// DatasourceSlugNotIn applies the NotIn predicate on the "datasource_slug" field.
func DatasourceSlugNotIn(vs ...string) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldNotIn(FieldDatasourceSlug, vs...))
}

// DatasourceSlugGT applies the GT predicate on the "datasource_slug" field.
func DatasourceSlugGT(v string) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldGT(FieldDatasourceSlug, v))
}

// DatasourceSlugGTE applies the GTE predicate on the "datasource_slug" field.
func DatasourceSlugGTE(v string) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldGTE(FieldDatasourceSlug, v))
}

// DatasourceSlugLT applies the LT predicate on the "datasource_slug" field.
func DatasourceSlugLT(v string) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldLT(FieldDatasourceSlug, v))
}

// DatasourceSlugLTE applies the LTE predicate on the "datasource_slug" field.
func DatasourceSlugLTE(v string) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldLTE(FieldDatasourceSlug, v))
}

// DatasourceSlugContains applies the Contains predicate on the "datasource_slug" field.
func DatasourceSlugContains(v string) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldContains(FieldDatasourceSlug, v))
}

// DatasourceSlugHasPrefix applies the HasPrefix predicate on the "datasource_slug" field.
func DatasourceSlugHasPrefix(v string) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldHasPrefix(FieldDatasourceSlug, v))
}

// DatasourceSlugHasSuffix applies the HasSuffix predicate on the "datasource_slug" field.
func DatasourceSlugHasSuffix(v string) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldHasSuffix(FieldDatasourceSlug, v))
}

// DatasourceSlugEqualFold applies the EqualFold predicate on the "datasource_slug" field.
func DatasourceSlugEqualFold(v string) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldEqualFold(FieldDatasourceSlug, v))
}

// DatasourceSlugContainsFold applies the ContainsFold predicate on the "datasource_slug" field.
func DatasourceSlugContainsFold(v string) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldContainsFold(FieldDatasourceSlug, v))
}

// ParametersIsNil applies the IsNil predicate on the "parameters" field.
func ParametersIsNil() predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldIsNull(FieldParameters))
}

// ParametersNotNil applies the NotNil predicate on the "parameters" field.
func ParametersNotNil() predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldNotNull(FieldParameters))
}

// ResultColumnsIsNil applies the IsNil predicate on the "result_columns" field.
func ResultColumnsIsNil() predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldIsNull(FieldResultColumns))
}

// ResultColumnsNotNil applies the NotNil predicate on the "result_columns" field.
func ResultColumnsNotNil() predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldNotNull(FieldResultColumns))
}

// VisibilityEQ applies the EQ predicate on the "visibility" field.
func VisibilityEQ(v Visibility) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldEQ(FieldVisibility, v))
}

// VisibilityNEQ applies the NEQ predicate on the "visibility" field.
func VisibilityNEQ(v Visibility) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldNEQ(FieldVisibility, v))
}

// VisibilityIn applies the In predicate on the "visibility" field.
func VisibilityIn(vs ...Visibility) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldIn(FieldVisibility, vs...))
}

// VisibilityNotIn applies the NotIn predicate on the "visibility" field.
func VisibilityNotIn(vs ...Visibility) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldNotIn(FieldVisibility, vs...))
}

// CacheTTLSecondsEQ applies the EQ predicate on the "cache_ttl_seconds" field.
func CacheTTLSecondsEQ(v int) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldEQ(FieldCacheTTLSeconds, v))
}

// CacheTTLSecondsNEQ applies the NEQ predicate on the "cache_ttl_seconds" field.
func CacheTTLSecondsNEQ(v int) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldNEQ(FieldCacheTTLSeconds, v))
}

// CacheTTLSecondsIn applies the In predicate on the "cache_ttl_seconds" field.
func CacheTTLSecondsIn(vs ...int) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldIn(FieldCacheTTLSeconds, vs...))
}

// CacheTTLSecondsNotIn applies the NotIn predicate on the "cache_ttl_seconds" field.
func CacheTTLSecondsNotIn(vs ...int) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldNotIn(FieldCacheTTLSeconds, vs...))
}

// CacheTTLSecondsGT applies the GT predicate on the "cache_ttl_seconds" field.
func CacheTTLSecondsGT(v int) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldGT(FieldCacheTTLSeconds, v))
}

// CacheTTLSecondsGTE applies the GTE predicate on the "cache_ttl_seconds" field.
func CacheTTLSecondsGTE(v int) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldGTE(FieldCacheTTLSeconds, v))
}

// CacheTTLSecondsLT applies the LT predicate on the "cache_ttl_seconds" field.
func CacheTTLSecondsLT(v int) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldLT(FieldCacheTTLSeconds, v))
}

// CacheTTLSecondsLTE applies the LTE predicate on the "cache_ttl_seconds" field.
func CacheTTLSecondsLTE(v int) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldLTE(FieldCacheTTLSeconds, v))
}

// LastRunAtEQ applies the EQ predicate on the "last_run_at" field.
func LastRunAtEQ(v time.Time) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldEQ(FieldLastRunAt, v))
}

// LastRunAtNEQ applies the NEQ predicate on the "last_run_at" field.
func LastRunAtNEQ(v time.Time) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldNEQ(FieldLastRunAt, v))
}

// LastRunAtIn applies the In predicate on the "last_run_at" field.
func LastRunAtIn(vs ...time.Time) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldIn(FieldLastRunAt, vs...))
}

// LastRunAtNotIn applies the NotIn predicate on the "last_run_at" field.
func LastRunAtNotIn(vs ...time.Time) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldNotIn(FieldLastRunAt, vs...))
}

// LastRunAtGT applies the GT predicate on the "last_run_at" field.
func LastRunAtGT(v time.Time) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldGT(FieldLastRunAt, v))
}

// LastRunAtGTE applies the GTE predicate on the "last_run_at" field.
func LastRunAtGTE(v time.Time) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldGTE(FieldLastRunAt, v))
}

// LastRunAtLT applies the LT predicate on the "last_run_at" field.
func LastRunAtLT(v time.Time) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldLT(FieldLastRunAt, v))
}

// LastRunAtLTE applies the LTE predicate on the "last_run_at" field.
func LastRunAtLTE(v time.Time) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldLTE(FieldLastRunAt, v))
}

// LastRunAtIsNil applies the IsNil predicate on the "last_run_at" field.
func LastRunAtIsNil() predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldIsNull(FieldLastRunAt))
}

// LastRunAtNotNil applies the NotNil predicate on the "last_run_at" field.
func LastRunAtNotNil() predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldNotNull(FieldLastRunAt))
}

// LastRunDurationMsEQ applies the EQ predicate on the "last_run_duration_ms" field.
func LastRunDurationMsEQ(v int64) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldEQ(FieldLastRunDurationMs, v))
}

// LastRunDurationMsNEQ applies the NEQ predicate on the "last_run_duration_ms" field.
func LastRunDurationMsNEQ(v int64) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldNEQ(FieldLastRunDurationMs, v))
}

// LastRunDurationMsIn applies the In predicate on the "last_run_duration_ms" field.
func LastRunDurationMsIn(vs ...int64) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldIn(FieldLastRunDurationMs, vs...))
}

// LastRunDurationMsNotIn applies the NotIn predicate on the "last_run_duration_ms" field.
func LastRunDurationMsNotIn(vs ...int64) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldNotIn(FieldLastRunDurationMs, vs...))
}

// LastRunDurationMsGT applies the GT predicate on the "last_run_duration_ms" field.
func LastRunDurationMsGT(v int64) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldGT(FieldLastRunDurationMs, v))
}

// LastRunDurationMsGTE applies the GTE predicate on the "last_run_duration_ms" field.
func LastRunDurationMsGTE(v int64) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldGTE(FieldLastRunDurationMs, v))
}

// LastRunDurationMsLT applies the LT predicate on the "last_run_duration_ms" field.
func LastRunDurationMsLT(v int64) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldLT(FieldLastRunDurationMs, v))
}

// LastRunDurationMsLTE applies the LTE predicate on the "last_run_duration_ms" field.
func LastRunDurationMsLTE(v int64) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldLTE(FieldLastRunDurationMs, v))
}

// LastRunDurationMsIsNil applies the IsNil predicate on the "last_run_duration_ms" field.
func LastRunDurationMsIsNil() predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldIsNull(FieldLastRunDurationMs))
}

// LastRunDurationMsNotNil applies the NotNil predicate on the "last_run_duration_ms" field.
func LastRunDurationMsNotNil() predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldNotNull(FieldLastRunDurationMs))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.SavedQuery {
	return predicate.SavedQuery(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasOrganization applies the HasEdge predicate on the "organization" edge.
func HasOrganization() predicate.SavedQuery {
	return predicate.SavedQuery(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, OrganizationTable, OrganizationColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOrganizationWith applies the HasEdge predicate on the "organization" edge with a given conditions (other predicates).
func HasOrganizationWith(preds ...predicate.Organization) predicate.SavedQuery {
	return predicate.SavedQuery(func(s *sql.Selector) {
		step := newOrganizationStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasOwner applies the HasEdge predicate on the "owner" edge.
func HasOwner() predicate.SavedQuery {
	return predicate.SavedQuery(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, OwnerTable, OwnerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOwnerWith applies the HasEdge predicate on the "owner" edge with a given conditions (other predicates).
func HasOwnerWith(preds ...predicate.Principal) predicate.SavedQuery {
	return predicate.SavedQuery(func(s *sql.Selector) {
		step := newOwnerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SavedQuery) predicate.SavedQuery {
	return predicate.SavedQuery(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SavedQuery) predicate.SavedQuery {
	return predicate.SavedQuery(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SavedQuery) predicate.SavedQuery {
	return predicate.SavedQuery(sql.NotPredicates(p))
}
