// Code generated by ent, DO NOT EDIT.

package alertchannel

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/plexusone/dashforge/ent/predicate"
)

// AlertID applies equality check predicate on the "alert_id" field. It's identical to AlertIDEQ.
func AlertID(v int) predicate.AlertChannel {
	return predicate.AlertChannel(sql.FieldEQ(FieldAlertID, v))
}

// IntegrationID applies equality check predicate on the "integration_id" field. It's identical to IntegrationIDEQ.
func IntegrationID(v int) predicate.AlertChannel {
	return predicate.AlertChannel(sql.FieldEQ(FieldIntegrationID, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.AlertChannel {
	return predicate.AlertChannel(sql.FieldEQ(FieldEnabled, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AlertChannel {
	return predicate.AlertChannel(sql.FieldEQ(FieldCreatedAt, v))
}

// AlertIDEQ applies the EQ predicate on the "alert_id" field.
func AlertIDEQ(v int) predicate.AlertChannel {
	return predicate.AlertChannel(sql.FieldEQ(FieldAlertID, v))
}

// AlertIDNEQ applies the NEQ predicate on the "alert_id" field.
func AlertIDNEQ(v int) predicate.AlertChannel {
	return predicate.AlertChannel(sql.FieldNEQ(FieldAlertID, v))
}

// AlertIDIn applies the In predicate on the "alert_id" field.
func AlertIDIn(vs ...int) predicate.AlertChannel {
	return predicate.AlertChannel(sql.FieldIn(FieldAlertID, vs...))
}

// AlertIDNotIn applies the NotIn predicate on the "alert_id" field.
func AlertIDNotIn(vs ...int) predicate.AlertChannel {
	return predicate.AlertChannel(sql.FieldNotIn(FieldAlertID, vs...))
}

// IntegrationIDEQ applies the EQ predicate on the "integration_id" field.
func IntegrationIDEQ(v int) predicate.AlertChannel {
	return predicate.AlertChannel(sql.FieldEQ(FieldIntegrationID, v))
}

// IntegrationIDNEQ applies the NEQ predicate on the "integration_id" field.
func IntegrationIDNEQ(v int) predicate.AlertChannel {
	return predicate.AlertChannel(sql.FieldNEQ(FieldIntegrationID, v))
}

// IntegrationIDIn applies the In predicate on the "integration_id" field.
func IntegrationIDIn(vs ...int) predicate.AlertChannel {
	return predicate.AlertChannel(sql.FieldIn(FieldIntegrationID, vs...))
}

// IntegrationIDNotIn applies the NotIn predicate on the "integration_id" field.
func IntegrationIDNotIn(vs ...int) predicate.AlertChannel {
	return predicate.AlertChannel(sql.FieldNotIn(FieldIntegrationID, vs...))
}

// ChannelConfigIsNil applies the IsNil predicate on the "channel_config" field.
func ChannelConfigIsNil() predicate.AlertChannel {
	return predicate.AlertChannel(sql.FieldIsNull(FieldChannelConfig))
}

// ChannelConfigNotNil applies the NotNil predicate on the "channel_config" field.
func ChannelConfigNotNil() predicate.AlertChannel {
	return predicate.AlertChannel(sql.FieldNotNull(FieldChannelConfig))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.AlertChannel {
	return predicate.AlertChannel(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.AlertChannel {
	return predicate.AlertChannel(sql.FieldNEQ(FieldEnabled, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AlertChannel {
	return predicate.AlertChannel(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AlertChannel {
	return predicate.AlertChannel(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AlertChannel {
	return predicate.AlertChannel(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AlertChannel {
	return predicate.AlertChannel(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AlertChannel {
	return predicate.AlertChannel(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AlertChannel {
	return predicate.AlertChannel(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AlertChannel {
	return predicate.AlertChannel(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AlertChannel {
	return predicate.AlertChannel(sql.FieldLTE(FieldCreatedAt, v))
}

// HasAlert applies the HasEdge predicate on the "alert" edge.
func HasAlert() predicate.AlertChannel {
	return predicate.AlertChannel(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, AlertColumn),
			sqlgraph.Edge(sqlgraph.M2O, false, AlertTable, AlertColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAlertWith applies the HasEdge predicate on the "alert" edge with a given conditions (other predicates).
func HasAlertWith(preds ...predicate.Alert) predicate.AlertChannel {
	return predicate.AlertChannel(func(s *sql.Selector) {
		step := newAlertStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasIntegration applies the HasEdge predicate on the "integration" edge.
func HasIntegration() predicate.AlertChannel {
	return predicate.AlertChannel(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, IntegrationColumn),
			sqlgraph.Edge(sqlgraph.M2O, false, IntegrationTable, IntegrationColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasIntegrationWith applies the HasEdge predicate on the "integration" edge with a given conditions (other predicates).
func HasIntegrationWith(preds ...predicate.Integration) predicate.AlertChannel {
	return predicate.AlertChannel(func(s *sql.Selector) {
		step := newIntegrationStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AlertChannel) predicate.AlertChannel {
	return predicate.AlertChannel(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AlertChannel) predicate.AlertChannel {
	return predicate.AlertChannel(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AlertChannel) predicate.AlertChannel {
	return predicate.AlertChannel(sql.NotPredicates(p))
}
