// Code generated by ent, DO NOT EDIT.

package principal

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/plexusone/dashforge/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Principal {
	return predicate.Principal(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Principal {
	return predicate.Principal(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Principal {
	return predicate.Principal(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Principal {
	return predicate.Principal(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Principal {
	return predicate.Principal(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Principal {
	return predicate.Principal(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Principal {
	return predicate.Principal(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Principal {
	return predicate.Principal(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Principal {
	return predicate.Principal(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Principal {
	return predicate.Principal(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Principal {
	return predicate.Principal(sql.FieldEQ(FieldUpdatedAt, v))
}

// Identifier applies equality check predicate on the "identifier" field. It's identical to IdentifierEQ.
func Identifier(v string) predicate.Principal {
	return predicate.Principal(sql.FieldEQ(FieldIdentifier, v))
}

// DisplayName applies equality check predicate on the "display_name" field. It's identical to DisplayNameEQ.
func DisplayName(v string) predicate.Principal {
	return predicate.Principal(sql.FieldEQ(FieldDisplayName, v))
}

// OrganizationID applies equality check predicate on the "organization_id" field. It's identical to OrganizationIDEQ.
func OrganizationID(v uuid.UUID) predicate.Principal {
	return predicate.Principal(sql.FieldEQ(FieldOrganizationID, v))
}

// Active applies equality check predicate on the "active" field. It's identical to ActiveEQ.
func Active(v bool) predicate.Principal {
	return predicate.Principal(sql.FieldEQ(FieldActive, v))
}

// CoreControlPrincipalID applies equality check predicate on the "core_control_principal_id" field. It's identical to CoreControlPrincipalIDEQ.
func CoreControlPrincipalID(v uuid.UUID) predicate.Principal {
	return predicate.Principal(sql.FieldEQ(FieldCoreControlPrincipalID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Principal {
	return predicate.Principal(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Principal {
	return predicate.Principal(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Principal {
	return predicate.Principal(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Principal {
	return predicate.Principal(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Principal {
	return predicate.Principal(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Principal {
	return predicate.Principal(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Principal {
	return predicate.Principal(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Principal {
	return predicate.Principal(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Principal {
	return predicate.Principal(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Principal {
	return predicate.Principal(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Principal {
	return predicate.Principal(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Principal {
	return predicate.Principal(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Principal {
	return predicate.Principal(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Principal {
	return predicate.Principal(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Principal {
	return predicate.Principal(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Principal {
	return predicate.Principal(sql.FieldLTE(FieldUpdatedAt, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v Type) predicate.Principal {
	return predicate.Principal(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v Type) predicate.Principal {
	return predicate.Principal(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...Type) predicate.Principal {
	return predicate.Principal(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...Type) predicate.Principal {
	return predicate.Principal(sql.FieldNotIn(FieldType, vs...))
}

// IdentifierEQ applies the EQ predicate on the "identifier" field.
func IdentifierEQ(v string) predicate.Principal {
	return predicate.Principal(sql.FieldEQ(FieldIdentifier, v))
}

// IdentifierNEQ applies the NEQ predicate on the "identifier" field.
func IdentifierNEQ(v string) predicate.Principal {
	return predicate.Principal(sql.FieldNEQ(FieldIdentifier, v))
}

// IdentifierIn applies the In predicate on the "identifier" field.
func IdentifierIn(vs ...string) predicate.Principal {
	return predicate.Principal(sql.FieldIn(FieldIdentifier, vs...))
}

// IdentifierNotIn applies the NotIn predicate on the "identifier" field.
func IdentifierNotIn(vs ...string) predicate.Principal {
	return predicate.Principal(sql.FieldNotIn(FieldIdentifier, vs...))
}

// IdentifierGT applies the GT predicate on the "identifier" field.
func IdentifierGT(v string) predicate.Principal {
	return predicate.Principal(sql.FieldGT(FieldIdentifier, v))
}

// IdentifierGTE applies the GTE predicate on the "identifier" field.
func IdentifierGTE(v string) predicate.Principal {
	return predicate.Principal(sql.FieldGTE(FieldIdentifier, v))
}

// IdentifierLT applies the LT predicate on the "identifier" field.
func IdentifierLT(v string) predicate.Principal {
	return predicate.Principal(sql.FieldLT(FieldIdentifier, v))
}

// IdentifierLTE applies the LTE predicate on the "identifier" field.
func IdentifierLTE(v string) predicate.Principal {
	return predicate.Principal(sql.FieldLTE(FieldIdentifier, v))
}

// IdentifierContains applies the Contains predicate on the "identifier" field.
func IdentifierContains(v string) predicate.Principal {
	return predicate.Principal(sql.FieldContains(FieldIdentifier, v))
}

// IdentifierHasPrefix applies the HasPrefix predicate on the "identifier" field.
func IdentifierHasPrefix(v string) predicate.Principal {
	return predicate.Principal(sql.FieldHasPrefix(FieldIdentifier, v))
}

// IdentifierHasSuffix applies the HasSuffix predicate on the "identifier" field.
func IdentifierHasSuffix(v string) predicate.Principal {
	return predicate.Principal(sql.FieldHasSuffix(FieldIdentifier, v))
}

// IdentifierEqualFold applies the EqualFold predicate on the "identifier" field.
func IdentifierEqualFold(v string) predicate.Principal {
	return predicate.Principal(sql.FieldEqualFold(FieldIdentifier, v))
}

// IdentifierContainsFold applies the ContainsFold predicate on the "identifier" field.
func IdentifierContainsFold(v string) predicate.Principal {
	return predicate.Principal(sql.FieldContainsFold(FieldIdentifier, v))
}

// DisplayNameEQ applies the EQ predicate on the "display_name" field.
func DisplayNameEQ(v string) predicate.Principal {
	return predicate.Principal(sql.FieldEQ(FieldDisplayName, v))
}

// DisplayNameNEQ applies the NEQ predicate on the "display_name" field.
func DisplayNameNEQ(v string) predicate.Principal {
	return predicate.Principal(sql.FieldNEQ(FieldDisplayName, v))
}

// DisplayNameIn applies the In predicate on the "display_name" field.
func DisplayNameIn(vs ...string) predicate.Principal {
	return predicate.Principal(sql.FieldIn(FieldDisplayName, vs...))
}

// DisplayNameNotIn applies the NotIn predicate on the "display_name" field.
func DisplayNameNotIn(vs ...string) predicate.Principal {
	return predicate.Principal(sql.FieldNotIn(FieldDisplayName, vs...))
}

// DisplayNameGT applies the GT predicate on the "display_name" field.
func DisplayNameGT(v string) predicate.Principal {
	return predicate.Principal(sql.FieldGT(FieldDisplayName, v))
}

// DisplayNameGTE applies the GTE predicate on the "display_name" field.
func DisplayNameGTE(v string) predicate.Principal {
	return predicate.Principal(sql.FieldGTE(FieldDisplayName, v))
}

// DisplayNameLT applies the LT predicate on the "display_name" field.
func DisplayNameLT(v string) predicate.Principal {
	return predicate.Principal(sql.FieldLT(FieldDisplayName, v))
}

// DisplayNameLTE applies the LTE predicate on the "display_name" field.
func DisplayNameLTE(v string) predicate.Principal {
	return predicate.Principal(sql.FieldLTE(FieldDisplayName, v))
}

// DisplayNameContains applies the Contains predicate on the "display_name" field.
func DisplayNameContains(v string) predicate.Principal {
	return predicate.Principal(sql.FieldContains(FieldDisplayName, v))
}

// DisplayNameHasPrefix applies the HasPrefix predicate on the "display_name" field.
func DisplayNameHasPrefix(v string) predicate.Principal {
	return predicate.Principal(sql.FieldHasPrefix(FieldDisplayName, v))
}

// DisplayNameHasSuffix applies the HasSuffix predicate on the "display_name" field.
func DisplayNameHasSuffix(v string) predicate.Principal {
	return predicate.Principal(sql.FieldHasSuffix(FieldDisplayName, v))
}

// DisplayNameEqualFold applies the EqualFold predicate on the "display_name" field.
func DisplayNameEqualFold(v string) predicate.Principal {
	return predicate.Principal(sql.FieldEqualFold(FieldDisplayName, v))
}

// DisplayNameContainsFold applies the ContainsFold predicate on the "display_name" field.
func DisplayNameContainsFold(v string) predicate.Principal {
	return predicate.Principal(sql.FieldContainsFold(FieldDisplayName, v))
}

// OrganizationIDEQ applies the EQ predicate on the "organization_id" field.
func OrganizationIDEQ(v uuid.UUID) predicate.Principal {
	return predicate.Principal(sql.FieldEQ(FieldOrganizationID, v))
}

// OrganizationIDNEQ applies the NEQ predicate on the "organization_id" field.
func OrganizationIDNEQ(v uuid.UUID) predicate.Principal {
	return predicate.Principal(sql.FieldNEQ(FieldOrganizationID, v))
}

// OrganizationIDIn applies the In predicate on the "organization_id" field.
func OrganizationIDIn(vs ...uuid.UUID) predicate.Principal {
	return predicate.Principal(sql.FieldIn(FieldOrganizationID, vs...))
}

// OrganizationIDNotIn applies the NotIn predicate on the "organization_id" field.
func OrganizationIDNotIn(vs ...uuid.UUID) predicate.Principal {
	return predicate.Principal(sql.FieldNotIn(FieldOrganizationID, vs...))
}

// OrganizationIDIsNil applies the IsNil predicate on the "organization_id" field.
func OrganizationIDIsNil() predicate.Principal {
	return predicate.Principal(sql.FieldIsNull(FieldOrganizationID))
}

// OrganizationIDNotNil applies the NotNil predicate on the "organization_id" field.
func OrganizationIDNotNil() predicate.Principal {
	return predicate.Principal(sql.FieldNotNull(FieldOrganizationID))
}

// ActiveEQ applies the EQ predicate on the "active" field.
func ActiveEQ(v bool) predicate.Principal {
	return predicate.Principal(sql.FieldEQ(FieldActive, v))
}

// ActiveNEQ applies the NEQ predicate on the "active" field.
func ActiveNEQ(v bool) predicate.Principal {
	return predicate.Principal(sql.FieldNEQ(FieldActive, v))
}

// CapabilitiesIsNil applies the IsNil predicate on the "capabilities" field.
func CapabilitiesIsNil() predicate.Principal {
	return predicate.Principal(sql.FieldIsNull(FieldCapabilities))
}

// CapabilitiesNotNil applies the NotNil predicate on the "capabilities" field.
func CapabilitiesNotNil() predicate.Principal {
	return predicate.Principal(sql.FieldNotNull(FieldCapabilities))
}

// AllowedScopesIsNil applies the IsNil predicate on the "allowed_scopes" field.
func AllowedScopesIsNil() predicate.Principal {
	return predicate.Principal(sql.FieldIsNull(FieldAllowedScopes))
}

// AllowedScopesNotNil applies the NotNil predicate on the "allowed_scopes" field.
func AllowedScopesNotNil() predicate.Principal {
	return predicate.Principal(sql.FieldNotNull(FieldAllowedScopes))
}

// MetadataIsNil applies the IsNil predicate on the "metadata" field.
func MetadataIsNil() predicate.Principal {
	return predicate.Principal(sql.FieldIsNull(FieldMetadata))
}

// MetadataNotNil applies the NotNil predicate on the "metadata" field.
func MetadataNotNil() predicate.Principal {
	return predicate.Principal(sql.FieldNotNull(FieldMetadata))
}

// CoreControlPrincipalIDEQ applies the EQ predicate on the "core_control_principal_id" field.
func CoreControlPrincipalIDEQ(v uuid.UUID) predicate.Principal {
	return predicate.Principal(sql.FieldEQ(FieldCoreControlPrincipalID, v))
}

// CoreControlPrincipalIDNEQ applies the NEQ predicate on the "core_control_principal_id" field.
func CoreControlPrincipalIDNEQ(v uuid.UUID) predicate.Principal {
	return predicate.Principal(sql.FieldNEQ(FieldCoreControlPrincipalID, v))
}

// CoreControlPrincipalIDIn applies the In predicate on the "core_control_principal_id" field.
func CoreControlPrincipalIDIn(vs ...uuid.UUID) predicate.Principal {
	return predicate.Principal(sql.FieldIn(FieldCoreControlPrincipalID, vs...))
}

// CoreControlPrincipalIDNotIn applies the NotIn predicate on the "core_control_principal_id" field.
func CoreControlPrincipalIDNotIn(vs ...uuid.UUID) predicate.Principal {
	return predicate.Principal(sql.FieldNotIn(FieldCoreControlPrincipalID, vs...))
}

// CoreControlPrincipalIDGT applies the GT predicate on the "core_control_principal_id" field.
func CoreControlPrincipalIDGT(v uuid.UUID) predicate.Principal {
	return predicate.Principal(sql.FieldGT(FieldCoreControlPrincipalID, v))
}

// CoreControlPrincipalIDGTE applies the GTE predicate on the "core_control_principal_id" field.
func CoreControlPrincipalIDGTE(v uuid.UUID) predicate.Principal {
	return predicate.Principal(sql.FieldGTE(FieldCoreControlPrincipalID, v))
}

// CoreControlPrincipalIDLT applies the LT predicate on the "core_control_principal_id" field.
func CoreControlPrincipalIDLT(v uuid.UUID) predicate.Principal {
	return predicate.Principal(sql.FieldLT(FieldCoreControlPrincipalID, v))
}

// CoreControlPrincipalIDLTE applies the LTE predicate on the "core_control_principal_id" field.
func CoreControlPrincipalIDLTE(v uuid.UUID) predicate.Principal {
	return predicate.Principal(sql.FieldLTE(FieldCoreControlPrincipalID, v))
}

// CoreControlPrincipalIDIsNil applies the IsNil predicate on the "core_control_principal_id" field.
func CoreControlPrincipalIDIsNil() predicate.Principal {
	return predicate.Principal(sql.FieldIsNull(FieldCoreControlPrincipalID))
}

// CoreControlPrincipalIDNotNil applies the NotNil predicate on the "core_control_principal_id" field.
func CoreControlPrincipalIDNotNil() predicate.Principal {
	return predicate.Principal(sql.FieldNotNull(FieldCoreControlPrincipalID))
}

// HasOrganization applies the HasEdge predicate on the "organization" edge.
func HasOrganization() predicate.Principal {
	return predicate.Principal(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, OrganizationTable, OrganizationColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOrganizationWith applies the HasEdge predicate on the "organization" edge with a given conditions (other predicates).
func HasOrganizationWith(preds ...predicate.Organization) predicate.Principal {
	return predicate.Principal(func(s *sql.Selector) {
		step := newOrganizationStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasHuman applies the HasEdge predicate on the "human" edge.
func HasHuman() predicate.Principal {
	return predicate.Principal(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, HumanTable, HumanColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasHumanWith applies the HasEdge predicate on the "human" edge with a given conditions (other predicates).
func HasHumanWith(preds ...predicate.Human) predicate.Principal {
	return predicate.Principal(func(s *sql.Selector) {
		step := newHumanStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasOauthAccounts applies the HasEdge predicate on the "oauth_accounts" edge.
func HasOauthAccounts() predicate.Principal {
	return predicate.Principal(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, OauthAccountsTable, OauthAccountsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOauthAccountsWith applies the HasEdge predicate on the "oauth_accounts" edge with a given conditions (other predicates).
func HasOauthAccountsWith(preds ...predicate.OAuthAccount) predicate.Principal {
	return predicate.Principal(func(s *sql.Selector) {
		step := newOauthAccountsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRefreshTokens applies the HasEdge predicate on the "refresh_tokens" edge.
func HasRefreshTokens() predicate.Principal {
	return predicate.Principal(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, RefreshTokensTable, RefreshTokensColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRefreshTokensWith applies the HasEdge predicate on the "refresh_tokens" edge with a given conditions (other predicates).
func HasRefreshTokensWith(preds ...predicate.RefreshToken) predicate.Principal {
	return predicate.Principal(func(s *sql.Selector) {
		step := newRefreshTokensStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasPrincipalMemberships applies the HasEdge predicate on the "principal_memberships" edge.
func HasPrincipalMemberships() predicate.Principal {
	return predicate.Principal(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, PrincipalMembershipsTable, PrincipalMembershipsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPrincipalMembershipsWith applies the HasEdge predicate on the "principal_memberships" edge with a given conditions (other predicates).
func HasPrincipalMembershipsWith(preds ...predicate.PrincipalMembership) predicate.Principal {
	return predicate.Principal(func(s *sql.Selector) {
		step := newPrincipalMembershipsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasDashboards applies the HasEdge predicate on the "dashboards" edge.
func HasDashboards() predicate.Principal {
	return predicate.Principal(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, DashboardsTable, DashboardsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDashboardsWith applies the HasEdge predicate on the "dashboards" edge with a given conditions (other predicates).
func HasDashboardsWith(preds ...predicate.Dashboard) predicate.Principal {
	return predicate.Principal(func(s *sql.Selector) {
		step := newDashboardsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasQueries applies the HasEdge predicate on the "queries" edge.
func HasQueries() predicate.Principal {
	return predicate.Principal(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, QueriesTable, QueriesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasQueriesWith applies the HasEdge predicate on the "queries" edge with a given conditions (other predicates).
func HasQueriesWith(preds ...predicate.SavedQuery) predicate.Principal {
	return predicate.Principal(func(s *sql.Selector) {
		step := newQueriesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasOwnedListings applies the HasEdge predicate on the "owned_listings" edge.
func HasOwnedListings() predicate.Principal {
	return predicate.Principal(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, OwnedListingsTable, OwnedListingsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOwnedListingsWith applies the HasEdge predicate on the "owned_listings" edge with a given conditions (other predicates).
func HasOwnedListingsWith(preds ...predicate.Listing) predicate.Principal {
	return predicate.Principal(func(s *sql.Selector) {
		step := newOwnedListingsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasPurchasedLicenses applies the HasEdge predicate on the "purchased_licenses" edge.
func HasPurchasedLicenses() predicate.Principal {
	return predicate.Principal(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, PurchasedLicensesTable, PurchasedLicensesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPurchasedLicensesWith applies the HasEdge predicate on the "purchased_licenses" edge with a given conditions (other predicates).
func HasPurchasedLicensesWith(preds ...predicate.License) predicate.Principal {
	return predicate.Principal(func(s *sql.Selector) {
		step := newPurchasedLicensesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSeatAssignments applies the HasEdge predicate on the "seat_assignments" edge.
func HasSeatAssignments() predicate.Principal {
	return predicate.Principal(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, SeatAssignmentsTable, SeatAssignmentsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSeatAssignmentsWith applies the HasEdge predicate on the "seat_assignments" edge with a given conditions (other predicates).
func HasSeatAssignmentsWith(preds ...predicate.SeatAssignment) predicate.Principal {
	return predicate.Principal(func(s *sql.Selector) {
		step := newSeatAssignmentsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAssignedSeats applies the HasEdge predicate on the "assigned_seats" edge.
func HasAssignedSeats() predicate.Principal {
	return predicate.Principal(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AssignedSeatsTable, AssignedSeatsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAssignedSeatsWith applies the HasEdge predicate on the "assigned_seats" edge with a given conditions (other predicates).
func HasAssignedSeatsWith(preds ...predicate.SeatAssignment) predicate.Principal {
	return predicate.Principal(func(s *sql.Selector) {
		step := newAssignedSeatsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Principal) predicate.Principal {
	return predicate.Principal(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Principal) predicate.Principal {
	return predicate.Principal(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Principal) predicate.Principal {
	return predicate.Principal(sql.NotPredicates(p))
}
