// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/plexusone/dashforge/ent/alert"
	"github.com/plexusone/dashforge/ent/alertchannel"
	"github.com/plexusone/dashforge/ent/integration"
)

// AlertChannel is the model entity for the AlertChannel schema.
type AlertChannel struct {
	config `json:"-"`
	// AlertID holds the value of the "alert_id" field.
	AlertID int `json:"alert_id,omitempty"`
	// IntegrationID holds the value of the "integration_id" field.
	IntegrationID int `json:"integration_id,omitempty"`
	// Per-alert channel overrides (e.g., specific Slack channel)
	ChannelConfig map[string]interface{} `json:"channel_config,omitempty"`
	// Whether this channel is enabled for this alert
	Enabled bool `json:"enabled,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AlertChannelQuery when eager-loading is set.
	Edges        AlertChannelEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AlertChannelEdges holds the relations/edges for other nodes in the graph.
type AlertChannelEdges struct {
	// Alert holds the value of the alert edge.
	Alert *Alert `json:"alert,omitempty"`
	// Integration holds the value of the integration edge.
	Integration *Integration `json:"integration,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// AlertOrErr returns the Alert value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AlertChannelEdges) AlertOrErr() (*Alert, error) {
	if e.Alert != nil {
		return e.Alert, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: alert.Label}
	}
	return nil, &NotLoadedError{edge: "alert"}
}

// IntegrationOrErr returns the Integration value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AlertChannelEdges) IntegrationOrErr() (*Integration, error) {
	if e.Integration != nil {
		return e.Integration, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: integration.Label}
	}
	return nil, &NotLoadedError{edge: "integration"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AlertChannel) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case alertchannel.FieldChannelConfig:
			values[i] = new([]byte)
		case alertchannel.FieldEnabled:
			values[i] = new(sql.NullBool)
		case alertchannel.FieldAlertID, alertchannel.FieldIntegrationID:
			values[i] = new(sql.NullInt64)
		case alertchannel.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AlertChannel fields.
func (_m *AlertChannel) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case alertchannel.FieldAlertID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field alert_id", values[i])
			} else if value.Valid {
				_m.AlertID = int(value.Int64)
			}
		case alertchannel.FieldIntegrationID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field integration_id", values[i])
			} else if value.Valid {
				_m.IntegrationID = int(value.Int64)
			}
		case alertchannel.FieldChannelConfig:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field channel_config", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ChannelConfig); err != nil {
					return fmt.Errorf("unmarshal field channel_config: %w", err)
				}
			}
		case alertchannel.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case alertchannel.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AlertChannel.
// This includes values selected through modifiers, order, etc.
func (_m *AlertChannel) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAlert queries the "alert" edge of the AlertChannel entity.
func (_m *AlertChannel) QueryAlert() *AlertQuery {
	return NewAlertChannelClient(_m.config).QueryAlert(_m)
}

// QueryIntegration queries the "integration" edge of the AlertChannel entity.
func (_m *AlertChannel) QueryIntegration() *IntegrationQuery {
	return NewAlertChannelClient(_m.config).QueryIntegration(_m)
}

// Update returns a builder for updating this AlertChannel.
// Note that you need to call AlertChannel.Unwrap() before calling this method if this AlertChannel
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AlertChannel) Update() *AlertChannelUpdateOne {
	return NewAlertChannelClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AlertChannel entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AlertChannel) Unwrap() *AlertChannel {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AlertChannel is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AlertChannel) String() string {
	var builder strings.Builder
	builder.WriteString("AlertChannel(")
	builder.WriteString("alert_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AlertID))
	builder.WriteString(", ")
	builder.WriteString("integration_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.IntegrationID))
	builder.WriteString(", ")
	builder.WriteString("channel_config=")
	builder.WriteString(fmt.Sprintf("%v", _m.ChannelConfig))
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// AlertChannels is a parsable slice of AlertChannel.
type AlertChannels []*AlertChannel
