// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/plexusone/dashforge/ent/alert"
	"github.com/plexusone/dashforge/ent/alertevent"
	"github.com/plexusone/dashforge/ent/dashboard"
	"github.com/plexusone/dashforge/ent/integration"
	"github.com/plexusone/dashforge/ent/organization"
	"github.com/plexusone/dashforge/ent/predicate"
)

// AlertUpdate is the builder for updating Alert entities.
type AlertUpdate struct {
	config
	hooks    []Hook
	mutation *AlertMutation
}

// Where appends a list predicates to the AlertUpdate builder.
func (_u *AlertUpdate) Where(ps ...predicate.Alert) *AlertUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSlug sets the "slug" field.
func (_u *AlertUpdate) SetSlug(v string) *AlertUpdate {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *AlertUpdate) SetNillableSlug(v *string) *AlertUpdate {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *AlertUpdate) SetName(v string) *AlertUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AlertUpdate) SetNillableName(v *string) *AlertUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *AlertUpdate) SetDescription(v string) *AlertUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *AlertUpdate) SetNillableDescription(v *string) *AlertUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *AlertUpdate) ClearDescription() *AlertUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetTriggerType sets the "trigger_type" field.
func (_u *AlertUpdate) SetTriggerType(v alert.TriggerType) *AlertUpdate {
	_u.mutation.SetTriggerType(v)
	return _u
}

// SetNillableTriggerType sets the "trigger_type" field if the given value is not nil.
func (_u *AlertUpdate) SetNillableTriggerType(v *alert.TriggerType) *AlertUpdate {
	if v != nil {
		_u.SetTriggerType(*v)
	}
	return _u
}

// SetTriggerConfig sets the "trigger_config" field.
func (_u *AlertUpdate) SetTriggerConfig(v map[string]interface{}) *AlertUpdate {
	_u.mutation.SetTriggerConfig(v)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *AlertUpdate) SetEnabled(v bool) *AlertUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *AlertUpdate) SetNillableEnabled(v *bool) *AlertUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetCooldownSeconds sets the "cooldown_seconds" field.
func (_u *AlertUpdate) SetCooldownSeconds(v int) *AlertUpdate {
	_u.mutation.ResetCooldownSeconds()
	_u.mutation.SetCooldownSeconds(v)
	return _u
}

// SetNillableCooldownSeconds sets the "cooldown_seconds" field if the given value is not nil.
func (_u *AlertUpdate) SetNillableCooldownSeconds(v *int) *AlertUpdate {
	if v != nil {
		_u.SetCooldownSeconds(*v)
	}
	return _u
}

// AddCooldownSeconds adds value to the "cooldown_seconds" field.
func (_u *AlertUpdate) AddCooldownSeconds(v int) *AlertUpdate {
	_u.mutation.AddCooldownSeconds(v)
	return _u
}

// SetConsecutiveFailures sets the "consecutive_failures" field.
func (_u *AlertUpdate) SetConsecutiveFailures(v int) *AlertUpdate {
	_u.mutation.ResetConsecutiveFailures()
	_u.mutation.SetConsecutiveFailures(v)
	return _u
}

// SetNillableConsecutiveFailures sets the "consecutive_failures" field if the given value is not nil.
func (_u *AlertUpdate) SetNillableConsecutiveFailures(v *int) *AlertUpdate {
	if v != nil {
		_u.SetConsecutiveFailures(*v)
	}
	return _u
}

// AddConsecutiveFailures adds value to the "consecutive_failures" field.
func (_u *AlertUpdate) AddConsecutiveFailures(v int) *AlertUpdate {
	_u.mutation.AddConsecutiveFailures(v)
	return _u
}

// SetLastTriggeredAt sets the "last_triggered_at" field.
func (_u *AlertUpdate) SetLastTriggeredAt(v time.Time) *AlertUpdate {
	_u.mutation.SetLastTriggeredAt(v)
	return _u
}

// SetNillableLastTriggeredAt sets the "last_triggered_at" field if the given value is not nil.
func (_u *AlertUpdate) SetNillableLastTriggeredAt(v *time.Time) *AlertUpdate {
	if v != nil {
		_u.SetLastTriggeredAt(*v)
	}
	return _u
}

// ClearLastTriggeredAt clears the value of the "last_triggered_at" field.
func (_u *AlertUpdate) ClearLastTriggeredAt() *AlertUpdate {
	_u.mutation.ClearLastTriggeredAt()
	return _u
}

// SetLastEvaluatedAt sets the "last_evaluated_at" field.
func (_u *AlertUpdate) SetLastEvaluatedAt(v time.Time) *AlertUpdate {
	_u.mutation.SetLastEvaluatedAt(v)
	return _u
}

// SetNillableLastEvaluatedAt sets the "last_evaluated_at" field if the given value is not nil.
func (_u *AlertUpdate) SetNillableLastEvaluatedAt(v *time.Time) *AlertUpdate {
	if v != nil {
		_u.SetLastEvaluatedAt(*v)
	}
	return _u
}

// ClearLastEvaluatedAt clears the value of the "last_evaluated_at" field.
func (_u *AlertUpdate) ClearLastEvaluatedAt() *AlertUpdate {
	_u.mutation.ClearLastEvaluatedAt()
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *AlertUpdate) SetLastError(v string) *AlertUpdate {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *AlertUpdate) SetNillableLastError(v *string) *AlertUpdate {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// ClearLastError clears the value of the "last_error" field.
func (_u *AlertUpdate) ClearLastError() *AlertUpdate {
	_u.mutation.ClearLastError()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AlertUpdate) SetUpdatedAt(v time.Time) *AlertUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetOrganizationID sets the "organization" edge to the Organization entity by ID.
func (_u *AlertUpdate) SetOrganizationID(id uuid.UUID) *AlertUpdate {
	_u.mutation.SetOrganizationID(id)
	return _u
}

// SetOrganization sets the "organization" edge to the Organization entity.
func (_u *AlertUpdate) SetOrganization(v *Organization) *AlertUpdate {
	return _u.SetOrganizationID(v.ID)
}

// SetDashboardID sets the "dashboard" edge to the Dashboard entity by ID.
func (_u *AlertUpdate) SetDashboardID(id int) *AlertUpdate {
	_u.mutation.SetDashboardID(id)
	return _u
}

// SetNillableDashboardID sets the "dashboard" edge to the Dashboard entity by ID if the given value is not nil.
func (_u *AlertUpdate) SetNillableDashboardID(id *int) *AlertUpdate {
	if id != nil {
		_u = _u.SetDashboardID(*id)
	}
	return _u
}

// SetDashboard sets the "dashboard" edge to the Dashboard entity.
func (_u *AlertUpdate) SetDashboard(v *Dashboard) *AlertUpdate {
	return _u.SetDashboardID(v.ID)
}

// AddChannelIDs adds the "channels" edge to the Integration entity by IDs.
func (_u *AlertUpdate) AddChannelIDs(ids ...int) *AlertUpdate {
	_u.mutation.AddChannelIDs(ids...)
	return _u
}

// AddChannels adds the "channels" edges to the Integration entity.
func (_u *AlertUpdate) AddChannels(v ...*Integration) *AlertUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChannelIDs(ids...)
}

// AddEventIDs adds the "events" edge to the AlertEvent entity by IDs.
func (_u *AlertUpdate) AddEventIDs(ids ...int) *AlertUpdate {
	_u.mutation.AddEventIDs(ids...)
	return _u
}

// AddEvents adds the "events" edges to the AlertEvent entity.
func (_u *AlertUpdate) AddEvents(v ...*AlertEvent) *AlertUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEventIDs(ids...)
}

// Mutation returns the AlertMutation object of the builder.
func (_u *AlertUpdate) Mutation() *AlertMutation {
	return _u.mutation
}

// ClearOrganization clears the "organization" edge to the Organization entity.
func (_u *AlertUpdate) ClearOrganization() *AlertUpdate {
	_u.mutation.ClearOrganization()
	return _u
}

// ClearDashboard clears the "dashboard" edge to the Dashboard entity.
func (_u *AlertUpdate) ClearDashboard() *AlertUpdate {
	_u.mutation.ClearDashboard()
	return _u
}

// ClearChannels clears all "channels" edges to the Integration entity.
func (_u *AlertUpdate) ClearChannels() *AlertUpdate {
	_u.mutation.ClearChannels()
	return _u
}

// RemoveChannelIDs removes the "channels" edge to Integration entities by IDs.
func (_u *AlertUpdate) RemoveChannelIDs(ids ...int) *AlertUpdate {
	_u.mutation.RemoveChannelIDs(ids...)
	return _u
}

// RemoveChannels removes "channels" edges to Integration entities.
func (_u *AlertUpdate) RemoveChannels(v ...*Integration) *AlertUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChannelIDs(ids...)
}

// ClearEvents clears all "events" edges to the AlertEvent entity.
func (_u *AlertUpdate) ClearEvents() *AlertUpdate {
	_u.mutation.ClearEvents()
	return _u
}

// RemoveEventIDs removes the "events" edge to AlertEvent entities by IDs.
func (_u *AlertUpdate) RemoveEventIDs(ids ...int) *AlertUpdate {
	_u.mutation.RemoveEventIDs(ids...)
	return _u
}

// RemoveEvents removes "events" edges to AlertEvent entities.
func (_u *AlertUpdate) RemoveEvents(v ...*AlertEvent) *AlertUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEventIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AlertUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AlertUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AlertUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AlertUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AlertUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := alert.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AlertUpdate) check() error {
	if v, ok := _u.mutation.Slug(); ok {
		if err := alert.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "Alert.slug": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := alert.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Alert.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TriggerType(); ok {
		if err := alert.TriggerTypeValidator(v); err != nil {
			return &ValidationError{Name: "trigger_type", err: fmt.Errorf(`ent: validator failed for field "Alert.trigger_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CooldownSeconds(); ok {
		if err := alert.CooldownSecondsValidator(v); err != nil {
			return &ValidationError{Name: "cooldown_seconds", err: fmt.Errorf(`ent: validator failed for field "Alert.cooldown_seconds": %w`, err)}
		}
	}
	if _u.mutation.OrganizationCleared() && len(_u.mutation.OrganizationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Alert.organization"`)
	}
	return nil
}

func (_u *AlertUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(alert.Table, alert.Columns, sqlgraph.NewFieldSpec(alert.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(alert.FieldSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(alert.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(alert.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(alert.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.TriggerType(); ok {
		_spec.SetField(alert.FieldTriggerType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.TriggerConfig(); ok {
		_spec.SetField(alert.FieldTriggerConfig, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(alert.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CooldownSeconds(); ok {
		_spec.SetField(alert.FieldCooldownSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCooldownSeconds(); ok {
		_spec.AddField(alert.FieldCooldownSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ConsecutiveFailures(); ok {
		_spec.SetField(alert.FieldConsecutiveFailures, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedConsecutiveFailures(); ok {
		_spec.AddField(alert.FieldConsecutiveFailures, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastTriggeredAt(); ok {
		_spec.SetField(alert.FieldLastTriggeredAt, field.TypeTime, value)
	}
	if _u.mutation.LastTriggeredAtCleared() {
		_spec.ClearField(alert.FieldLastTriggeredAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastEvaluatedAt(); ok {
		_spec.SetField(alert.FieldLastEvaluatedAt, field.TypeTime, value)
	}
	if _u.mutation.LastEvaluatedAtCleared() {
		_spec.ClearField(alert.FieldLastEvaluatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(alert.FieldLastError, field.TypeString, value)
	}
	if _u.mutation.LastErrorCleared() {
		_spec.ClearField(alert.FieldLastError, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(alert.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.OrganizationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   alert.OrganizationTable,
			Columns: []string{alert.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrganizationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   alert.OrganizationTable,
			Columns: []string{alert.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DashboardCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   alert.DashboardTable,
			Columns: []string{alert.DashboardColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dashboard.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DashboardIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   alert.DashboardTable,
			Columns: []string{alert.DashboardColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dashboard.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChannelsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   alert.ChannelsTable,
			Columns: alert.ChannelsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(integration.FieldID, field.TypeInt),
			},
		}
		createE := &AlertChannelCreate{config: _u.config, mutation: newAlertChannelMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChannelsIDs(); len(nodes) > 0 && !_u.mutation.ChannelsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   alert.ChannelsTable,
			Columns: alert.ChannelsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(integration.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &AlertChannelCreate{config: _u.config, mutation: newAlertChannelMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChannelsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   alert.ChannelsTable,
			Columns: alert.ChannelsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(integration.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &AlertChannelCreate{config: _u.config, mutation: newAlertChannelMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   alert.EventsTable,
			Columns: []string{alert.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(alertevent.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEventsIDs(); len(nodes) > 0 && !_u.mutation.EventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   alert.EventsTable,
			Columns: []string{alert.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(alertevent.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   alert.EventsTable,
			Columns: []string{alert.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(alertevent.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{alert.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AlertUpdateOne is the builder for updating a single Alert entity.
type AlertUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AlertMutation
}

// SetSlug sets the "slug" field.
func (_u *AlertUpdateOne) SetSlug(v string) *AlertUpdateOne {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *AlertUpdateOne) SetNillableSlug(v *string) *AlertUpdateOne {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *AlertUpdateOne) SetName(v string) *AlertUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AlertUpdateOne) SetNillableName(v *string) *AlertUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *AlertUpdateOne) SetDescription(v string) *AlertUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *AlertUpdateOne) SetNillableDescription(v *string) *AlertUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *AlertUpdateOne) ClearDescription() *AlertUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetTriggerType sets the "trigger_type" field.
func (_u *AlertUpdateOne) SetTriggerType(v alert.TriggerType) *AlertUpdateOne {
	_u.mutation.SetTriggerType(v)
	return _u
}

// SetNillableTriggerType sets the "trigger_type" field if the given value is not nil.
func (_u *AlertUpdateOne) SetNillableTriggerType(v *alert.TriggerType) *AlertUpdateOne {
	if v != nil {
		_u.SetTriggerType(*v)
	}
	return _u
}

// SetTriggerConfig sets the "trigger_config" field.
func (_u *AlertUpdateOne) SetTriggerConfig(v map[string]interface{}) *AlertUpdateOne {
	_u.mutation.SetTriggerConfig(v)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *AlertUpdateOne) SetEnabled(v bool) *AlertUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *AlertUpdateOne) SetNillableEnabled(v *bool) *AlertUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetCooldownSeconds sets the "cooldown_seconds" field.
func (_u *AlertUpdateOne) SetCooldownSeconds(v int) *AlertUpdateOne {
	_u.mutation.ResetCooldownSeconds()
	_u.mutation.SetCooldownSeconds(v)
	return _u
}

// SetNillableCooldownSeconds sets the "cooldown_seconds" field if the given value is not nil.
func (_u *AlertUpdateOne) SetNillableCooldownSeconds(v *int) *AlertUpdateOne {
	if v != nil {
		_u.SetCooldownSeconds(*v)
	}
	return _u
}

// AddCooldownSeconds adds value to the "cooldown_seconds" field.
func (_u *AlertUpdateOne) AddCooldownSeconds(v int) *AlertUpdateOne {
	_u.mutation.AddCooldownSeconds(v)
	return _u
}

// SetConsecutiveFailures sets the "consecutive_failures" field.
func (_u *AlertUpdateOne) SetConsecutiveFailures(v int) *AlertUpdateOne {
	_u.mutation.ResetConsecutiveFailures()
	_u.mutation.SetConsecutiveFailures(v)
	return _u
}

// SetNillableConsecutiveFailures sets the "consecutive_failures" field if the given value is not nil.
func (_u *AlertUpdateOne) SetNillableConsecutiveFailures(v *int) *AlertUpdateOne {
	if v != nil {
		_u.SetConsecutiveFailures(*v)
	}
	return _u
}

// AddConsecutiveFailures adds value to the "consecutive_failures" field.
func (_u *AlertUpdateOne) AddConsecutiveFailures(v int) *AlertUpdateOne {
	_u.mutation.AddConsecutiveFailures(v)
	return _u
}

// SetLastTriggeredAt sets the "last_triggered_at" field.
func (_u *AlertUpdateOne) SetLastTriggeredAt(v time.Time) *AlertUpdateOne {
	_u.mutation.SetLastTriggeredAt(v)
	return _u
}

// SetNillableLastTriggeredAt sets the "last_triggered_at" field if the given value is not nil.
func (_u *AlertUpdateOne) SetNillableLastTriggeredAt(v *time.Time) *AlertUpdateOne {
	if v != nil {
		_u.SetLastTriggeredAt(*v)
	}
	return _u
}

// ClearLastTriggeredAt clears the value of the "last_triggered_at" field.
func (_u *AlertUpdateOne) ClearLastTriggeredAt() *AlertUpdateOne {
	_u.mutation.ClearLastTriggeredAt()
	return _u
}

// SetLastEvaluatedAt sets the "last_evaluated_at" field.
func (_u *AlertUpdateOne) SetLastEvaluatedAt(v time.Time) *AlertUpdateOne {
	_u.mutation.SetLastEvaluatedAt(v)
	return _u
}

// SetNillableLastEvaluatedAt sets the "last_evaluated_at" field if the given value is not nil.
func (_u *AlertUpdateOne) SetNillableLastEvaluatedAt(v *time.Time) *AlertUpdateOne {
	if v != nil {
		_u.SetLastEvaluatedAt(*v)
	}
	return _u
}

// ClearLastEvaluatedAt clears the value of the "last_evaluated_at" field.
func (_u *AlertUpdateOne) ClearLastEvaluatedAt() *AlertUpdateOne {
	_u.mutation.ClearLastEvaluatedAt()
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *AlertUpdateOne) SetLastError(v string) *AlertUpdateOne {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *AlertUpdateOne) SetNillableLastError(v *string) *AlertUpdateOne {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// ClearLastError clears the value of the "last_error" field.
func (_u *AlertUpdateOne) ClearLastError() *AlertUpdateOne {
	_u.mutation.ClearLastError()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AlertUpdateOne) SetUpdatedAt(v time.Time) *AlertUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetOrganizationID sets the "organization" edge to the Organization entity by ID.
func (_u *AlertUpdateOne) SetOrganizationID(id uuid.UUID) *AlertUpdateOne {
	_u.mutation.SetOrganizationID(id)
	return _u
}

// SetOrganization sets the "organization" edge to the Organization entity.
func (_u *AlertUpdateOne) SetOrganization(v *Organization) *AlertUpdateOne {
	return _u.SetOrganizationID(v.ID)
}

// SetDashboardID sets the "dashboard" edge to the Dashboard entity by ID.
func (_u *AlertUpdateOne) SetDashboardID(id int) *AlertUpdateOne {
	_u.mutation.SetDashboardID(id)
	return _u
}

// SetNillableDashboardID sets the "dashboard" edge to the Dashboard entity by ID if the given value is not nil.
func (_u *AlertUpdateOne) SetNillableDashboardID(id *int) *AlertUpdateOne {
	if id != nil {
		_u = _u.SetDashboardID(*id)
	}
	return _u
}

// SetDashboard sets the "dashboard" edge to the Dashboard entity.
func (_u *AlertUpdateOne) SetDashboard(v *Dashboard) *AlertUpdateOne {
	return _u.SetDashboardID(v.ID)
}

// AddChannelIDs adds the "channels" edge to the Integration entity by IDs.
func (_u *AlertUpdateOne) AddChannelIDs(ids ...int) *AlertUpdateOne {
	_u.mutation.AddChannelIDs(ids...)
	return _u
}

// AddChannels adds the "channels" edges to the Integration entity.
func (_u *AlertUpdateOne) AddChannels(v ...*Integration) *AlertUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChannelIDs(ids...)
}

// AddEventIDs adds the "events" edge to the AlertEvent entity by IDs.
func (_u *AlertUpdateOne) AddEventIDs(ids ...int) *AlertUpdateOne {
	_u.mutation.AddEventIDs(ids...)
	return _u
}

// AddEvents adds the "events" edges to the AlertEvent entity.
func (_u *AlertUpdateOne) AddEvents(v ...*AlertEvent) *AlertUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEventIDs(ids...)
}

// Mutation returns the AlertMutation object of the builder.
func (_u *AlertUpdateOne) Mutation() *AlertMutation {
	return _u.mutation
}

// ClearOrganization clears the "organization" edge to the Organization entity.
func (_u *AlertUpdateOne) ClearOrganization() *AlertUpdateOne {
	_u.mutation.ClearOrganization()
	return _u
}

// ClearDashboard clears the "dashboard" edge to the Dashboard entity.
func (_u *AlertUpdateOne) ClearDashboard() *AlertUpdateOne {
	_u.mutation.ClearDashboard()
	return _u
}

// ClearChannels clears all "channels" edges to the Integration entity.
func (_u *AlertUpdateOne) ClearChannels() *AlertUpdateOne {
	_u.mutation.ClearChannels()
	return _u
}

// RemoveChannelIDs removes the "channels" edge to Integration entities by IDs.
func (_u *AlertUpdateOne) RemoveChannelIDs(ids ...int) *AlertUpdateOne {
	_u.mutation.RemoveChannelIDs(ids...)
	return _u
}

// RemoveChannels removes "channels" edges to Integration entities.
func (_u *AlertUpdateOne) RemoveChannels(v ...*Integration) *AlertUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChannelIDs(ids...)
}

// ClearEvents clears all "events" edges to the AlertEvent entity.
func (_u *AlertUpdateOne) ClearEvents() *AlertUpdateOne {
	_u.mutation.ClearEvents()
	return _u
}

// RemoveEventIDs removes the "events" edge to AlertEvent entities by IDs.
func (_u *AlertUpdateOne) RemoveEventIDs(ids ...int) *AlertUpdateOne {
	_u.mutation.RemoveEventIDs(ids...)
	return _u
}

// RemoveEvents removes "events" edges to AlertEvent entities.
func (_u *AlertUpdateOne) RemoveEvents(v ...*AlertEvent) *AlertUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEventIDs(ids...)
}

// Where appends a list predicates to the AlertUpdate builder.
func (_u *AlertUpdateOne) Where(ps ...predicate.Alert) *AlertUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AlertUpdateOne) Select(field string, fields ...string) *AlertUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Alert entity.
func (_u *AlertUpdateOne) Save(ctx context.Context) (*Alert, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AlertUpdateOne) SaveX(ctx context.Context) *Alert {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AlertUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AlertUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AlertUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := alert.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AlertUpdateOne) check() error {
	if v, ok := _u.mutation.Slug(); ok {
		if err := alert.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "Alert.slug": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := alert.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Alert.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TriggerType(); ok {
		if err := alert.TriggerTypeValidator(v); err != nil {
			return &ValidationError{Name: "trigger_type", err: fmt.Errorf(`ent: validator failed for field "Alert.trigger_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CooldownSeconds(); ok {
		if err := alert.CooldownSecondsValidator(v); err != nil {
			return &ValidationError{Name: "cooldown_seconds", err: fmt.Errorf(`ent: validator failed for field "Alert.cooldown_seconds": %w`, err)}
		}
	}
	if _u.mutation.OrganizationCleared() && len(_u.mutation.OrganizationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Alert.organization"`)
	}
	return nil
}

func (_u *AlertUpdateOne) sqlSave(ctx context.Context) (_node *Alert, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(alert.Table, alert.Columns, sqlgraph.NewFieldSpec(alert.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Alert.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, alert.FieldID)
		for _, f := range fields {
			if !alert.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != alert.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(alert.FieldSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(alert.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(alert.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(alert.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.TriggerType(); ok {
		_spec.SetField(alert.FieldTriggerType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.TriggerConfig(); ok {
		_spec.SetField(alert.FieldTriggerConfig, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(alert.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CooldownSeconds(); ok {
		_spec.SetField(alert.FieldCooldownSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCooldownSeconds(); ok {
		_spec.AddField(alert.FieldCooldownSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ConsecutiveFailures(); ok {
		_spec.SetField(alert.FieldConsecutiveFailures, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedConsecutiveFailures(); ok {
		_spec.AddField(alert.FieldConsecutiveFailures, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastTriggeredAt(); ok {
		_spec.SetField(alert.FieldLastTriggeredAt, field.TypeTime, value)
	}
	if _u.mutation.LastTriggeredAtCleared() {
		_spec.ClearField(alert.FieldLastTriggeredAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastEvaluatedAt(); ok {
		_spec.SetField(alert.FieldLastEvaluatedAt, field.TypeTime, value)
	}
	if _u.mutation.LastEvaluatedAtCleared() {
		_spec.ClearField(alert.FieldLastEvaluatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(alert.FieldLastError, field.TypeString, value)
	}
	if _u.mutation.LastErrorCleared() {
		_spec.ClearField(alert.FieldLastError, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(alert.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.OrganizationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   alert.OrganizationTable,
			Columns: []string{alert.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrganizationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   alert.OrganizationTable,
			Columns: []string{alert.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DashboardCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   alert.DashboardTable,
			Columns: []string{alert.DashboardColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dashboard.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DashboardIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   alert.DashboardTable,
			Columns: []string{alert.DashboardColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dashboard.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChannelsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   alert.ChannelsTable,
			Columns: alert.ChannelsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(integration.FieldID, field.TypeInt),
			},
		}
		createE := &AlertChannelCreate{config: _u.config, mutation: newAlertChannelMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChannelsIDs(); len(nodes) > 0 && !_u.mutation.ChannelsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   alert.ChannelsTable,
			Columns: alert.ChannelsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(integration.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &AlertChannelCreate{config: _u.config, mutation: newAlertChannelMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChannelsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   alert.ChannelsTable,
			Columns: alert.ChannelsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(integration.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &AlertChannelCreate{config: _u.config, mutation: newAlertChannelMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   alert.EventsTable,
			Columns: []string{alert.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(alertevent.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEventsIDs(); len(nodes) > 0 && !_u.mutation.EventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   alert.EventsTable,
			Columns: []string{alert.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(alertevent.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   alert.EventsTable,
			Columns: []string{alert.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(alertevent.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Alert{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{alert.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
