// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/plexusone/dashforge/ent/alert"
	"github.com/plexusone/dashforge/ent/dashboard"
	"github.com/plexusone/dashforge/ent/dashboardversion"
	"github.com/plexusone/dashforge/ent/organization"
	"github.com/plexusone/dashforge/ent/predicate"
	"github.com/plexusone/dashforge/ent/principal"
)

// DashboardUpdate is the builder for updating Dashboard entities.
type DashboardUpdate struct {
	config
	hooks    []Hook
	mutation *DashboardMutation
}

// Where appends a list predicates to the DashboardUpdate builder.
func (_u *DashboardUpdate) Where(ps ...predicate.Dashboard) *DashboardUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSlug sets the "slug" field.
func (_u *DashboardUpdate) SetSlug(v string) *DashboardUpdate {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *DashboardUpdate) SetNillableSlug(v *string) *DashboardUpdate {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *DashboardUpdate) SetTitle(v string) *DashboardUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *DashboardUpdate) SetNillableTitle(v *string) *DashboardUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *DashboardUpdate) SetDescription(v string) *DashboardUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *DashboardUpdate) SetNillableDescription(v *string) *DashboardUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *DashboardUpdate) ClearDescription() *DashboardUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetDefinition sets the "definition" field.
func (_u *DashboardUpdate) SetDefinition(v map[string]interface{}) *DashboardUpdate {
	_u.mutation.SetDefinition(v)
	return _u
}

// SetVisibility sets the "visibility" field.
func (_u *DashboardUpdate) SetVisibility(v dashboard.Visibility) *DashboardUpdate {
	_u.mutation.SetVisibility(v)
	return _u
}

// SetNillableVisibility sets the "visibility" field if the given value is not nil.
func (_u *DashboardUpdate) SetNillableVisibility(v *dashboard.Visibility) *DashboardUpdate {
	if v != nil {
		_u.SetVisibility(*v)
	}
	return _u
}

// SetArchived sets the "archived" field.
func (_u *DashboardUpdate) SetArchived(v bool) *DashboardUpdate {
	_u.mutation.SetArchived(v)
	return _u
}

// SetNillableArchived sets the "archived" field if the given value is not nil.
func (_u *DashboardUpdate) SetNillableArchived(v *bool) *DashboardUpdate {
	if v != nil {
		_u.SetArchived(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *DashboardUpdate) SetVersion(v int) *DashboardUpdate {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *DashboardUpdate) SetNillableVersion(v *int) *DashboardUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *DashboardUpdate) AddVersion(v int) *DashboardUpdate {
	_u.mutation.AddVersion(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DashboardUpdate) SetUpdatedAt(v time.Time) *DashboardUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetOrganizationID sets the "organization" edge to the Organization entity by ID.
func (_u *DashboardUpdate) SetOrganizationID(id uuid.UUID) *DashboardUpdate {
	_u.mutation.SetOrganizationID(id)
	return _u
}

// SetOrganization sets the "organization" edge to the Organization entity.
func (_u *DashboardUpdate) SetOrganization(v *Organization) *DashboardUpdate {
	return _u.SetOrganizationID(v.ID)
}

// SetOwnerID sets the "owner" edge to the Principal entity by ID.
func (_u *DashboardUpdate) SetOwnerID(id uuid.UUID) *DashboardUpdate {
	_u.mutation.SetOwnerID(id)
	return _u
}

// SetNillableOwnerID sets the "owner" edge to the Principal entity by ID if the given value is not nil.
func (_u *DashboardUpdate) SetNillableOwnerID(id *uuid.UUID) *DashboardUpdate {
	if id != nil {
		_u = _u.SetOwnerID(*id)
	}
	return _u
}

// SetOwner sets the "owner" edge to the Principal entity.
func (_u *DashboardUpdate) SetOwner(v *Principal) *DashboardUpdate {
	return _u.SetOwnerID(v.ID)
}

// AddVersionIDs adds the "versions" edge to the DashboardVersion entity by IDs.
func (_u *DashboardUpdate) AddVersionIDs(ids ...int) *DashboardUpdate {
	_u.mutation.AddVersionIDs(ids...)
	return _u
}

// AddVersions adds the "versions" edges to the DashboardVersion entity.
func (_u *DashboardUpdate) AddVersions(v ...*DashboardVersion) *DashboardUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddVersionIDs(ids...)
}

// AddAlertIDs adds the "alerts" edge to the Alert entity by IDs.
func (_u *DashboardUpdate) AddAlertIDs(ids ...int) *DashboardUpdate {
	_u.mutation.AddAlertIDs(ids...)
	return _u
}

// AddAlerts adds the "alerts" edges to the Alert entity.
func (_u *DashboardUpdate) AddAlerts(v ...*Alert) *DashboardUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAlertIDs(ids...)
}

// Mutation returns the DashboardMutation object of the builder.
func (_u *DashboardUpdate) Mutation() *DashboardMutation {
	return _u.mutation
}

// ClearOrganization clears the "organization" edge to the Organization entity.
func (_u *DashboardUpdate) ClearOrganization() *DashboardUpdate {
	_u.mutation.ClearOrganization()
	return _u
}

// ClearOwner clears the "owner" edge to the Principal entity.
func (_u *DashboardUpdate) ClearOwner() *DashboardUpdate {
	_u.mutation.ClearOwner()
	return _u
}

// ClearVersions clears all "versions" edges to the DashboardVersion entity.
func (_u *DashboardUpdate) ClearVersions() *DashboardUpdate {
	_u.mutation.ClearVersions()
	return _u
}

// RemoveVersionIDs removes the "versions" edge to DashboardVersion entities by IDs.
func (_u *DashboardUpdate) RemoveVersionIDs(ids ...int) *DashboardUpdate {
	_u.mutation.RemoveVersionIDs(ids...)
	return _u
}

// RemoveVersions removes "versions" edges to DashboardVersion entities.
func (_u *DashboardUpdate) RemoveVersions(v ...*DashboardVersion) *DashboardUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveVersionIDs(ids...)
}

// ClearAlerts clears all "alerts" edges to the Alert entity.
func (_u *DashboardUpdate) ClearAlerts() *DashboardUpdate {
	_u.mutation.ClearAlerts()
	return _u
}

// RemoveAlertIDs removes the "alerts" edge to Alert entities by IDs.
func (_u *DashboardUpdate) RemoveAlertIDs(ids ...int) *DashboardUpdate {
	_u.mutation.RemoveAlertIDs(ids...)
	return _u
}

// RemoveAlerts removes "alerts" edges to Alert entities.
func (_u *DashboardUpdate) RemoveAlerts(v ...*Alert) *DashboardUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAlertIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DashboardUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DashboardUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DashboardUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DashboardUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DashboardUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := dashboard.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DashboardUpdate) check() error {
	if v, ok := _u.mutation.Slug(); ok {
		if err := dashboard.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "Dashboard.slug": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := dashboard.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Dashboard.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Visibility(); ok {
		if err := dashboard.VisibilityValidator(v); err != nil {
			return &ValidationError{Name: "visibility", err: fmt.Errorf(`ent: validator failed for field "Dashboard.visibility": %w`, err)}
		}
	}
	if _u.mutation.OrganizationCleared() && len(_u.mutation.OrganizationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Dashboard.organization"`)
	}
	return nil
}

func (_u *DashboardUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(dashboard.Table, dashboard.Columns, sqlgraph.NewFieldSpec(dashboard.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(dashboard.FieldSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(dashboard.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(dashboard.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(dashboard.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Definition(); ok {
		_spec.SetField(dashboard.FieldDefinition, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Visibility(); ok {
		_spec.SetField(dashboard.FieldVisibility, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Archived(); ok {
		_spec.SetField(dashboard.FieldArchived, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(dashboard.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(dashboard.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(dashboard.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.OrganizationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   dashboard.OrganizationTable,
			Columns: []string{dashboard.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrganizationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   dashboard.OrganizationTable,
			Columns: []string{dashboard.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   dashboard.OwnerTable,
			Columns: []string{dashboard.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(principal.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   dashboard.OwnerTable,
			Columns: []string{dashboard.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(principal.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.VersionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   dashboard.VersionsTable,
			Columns: []string{dashboard.VersionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dashboardversion.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedVersionsIDs(); len(nodes) > 0 && !_u.mutation.VersionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   dashboard.VersionsTable,
			Columns: []string{dashboard.VersionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dashboardversion.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.VersionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   dashboard.VersionsTable,
			Columns: []string{dashboard.VersionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dashboardversion.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AlertsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   dashboard.AlertsTable,
			Columns: []string{dashboard.AlertsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(alert.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAlertsIDs(); len(nodes) > 0 && !_u.mutation.AlertsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   dashboard.AlertsTable,
			Columns: []string{dashboard.AlertsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(alert.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AlertsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   dashboard.AlertsTable,
			Columns: []string{dashboard.AlertsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(alert.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dashboard.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DashboardUpdateOne is the builder for updating a single Dashboard entity.
type DashboardUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DashboardMutation
}

// SetSlug sets the "slug" field.
func (_u *DashboardUpdateOne) SetSlug(v string) *DashboardUpdateOne {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *DashboardUpdateOne) SetNillableSlug(v *string) *DashboardUpdateOne {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *DashboardUpdateOne) SetTitle(v string) *DashboardUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *DashboardUpdateOne) SetNillableTitle(v *string) *DashboardUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *DashboardUpdateOne) SetDescription(v string) *DashboardUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *DashboardUpdateOne) SetNillableDescription(v *string) *DashboardUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *DashboardUpdateOne) ClearDescription() *DashboardUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetDefinition sets the "definition" field.
func (_u *DashboardUpdateOne) SetDefinition(v map[string]interface{}) *DashboardUpdateOne {
	_u.mutation.SetDefinition(v)
	return _u
}

// SetVisibility sets the "visibility" field.
func (_u *DashboardUpdateOne) SetVisibility(v dashboard.Visibility) *DashboardUpdateOne {
	_u.mutation.SetVisibility(v)
	return _u
}

// SetNillableVisibility sets the "visibility" field if the given value is not nil.
func (_u *DashboardUpdateOne) SetNillableVisibility(v *dashboard.Visibility) *DashboardUpdateOne {
	if v != nil {
		_u.SetVisibility(*v)
	}
	return _u
}

// SetArchived sets the "archived" field.
func (_u *DashboardUpdateOne) SetArchived(v bool) *DashboardUpdateOne {
	_u.mutation.SetArchived(v)
	return _u
}

// SetNillableArchived sets the "archived" field if the given value is not nil.
func (_u *DashboardUpdateOne) SetNillableArchived(v *bool) *DashboardUpdateOne {
	if v != nil {
		_u.SetArchived(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *DashboardUpdateOne) SetVersion(v int) *DashboardUpdateOne {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *DashboardUpdateOne) SetNillableVersion(v *int) *DashboardUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *DashboardUpdateOne) AddVersion(v int) *DashboardUpdateOne {
	_u.mutation.AddVersion(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DashboardUpdateOne) SetUpdatedAt(v time.Time) *DashboardUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetOrganizationID sets the "organization" edge to the Organization entity by ID.
func (_u *DashboardUpdateOne) SetOrganizationID(id uuid.UUID) *DashboardUpdateOne {
	_u.mutation.SetOrganizationID(id)
	return _u
}

// SetOrganization sets the "organization" edge to the Organization entity.
func (_u *DashboardUpdateOne) SetOrganization(v *Organization) *DashboardUpdateOne {
	return _u.SetOrganizationID(v.ID)
}

// SetOwnerID sets the "owner" edge to the Principal entity by ID.
func (_u *DashboardUpdateOne) SetOwnerID(id uuid.UUID) *DashboardUpdateOne {
	_u.mutation.SetOwnerID(id)
	return _u
}

// SetNillableOwnerID sets the "owner" edge to the Principal entity by ID if the given value is not nil.
func (_u *DashboardUpdateOne) SetNillableOwnerID(id *uuid.UUID) *DashboardUpdateOne {
	if id != nil {
		_u = _u.SetOwnerID(*id)
	}
	return _u
}

// SetOwner sets the "owner" edge to the Principal entity.
func (_u *DashboardUpdateOne) SetOwner(v *Principal) *DashboardUpdateOne {
	return _u.SetOwnerID(v.ID)
}

// AddVersionIDs adds the "versions" edge to the DashboardVersion entity by IDs.
func (_u *DashboardUpdateOne) AddVersionIDs(ids ...int) *DashboardUpdateOne {
	_u.mutation.AddVersionIDs(ids...)
	return _u
}

// AddVersions adds the "versions" edges to the DashboardVersion entity.
func (_u *DashboardUpdateOne) AddVersions(v ...*DashboardVersion) *DashboardUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddVersionIDs(ids...)
}

// AddAlertIDs adds the "alerts" edge to the Alert entity by IDs.
func (_u *DashboardUpdateOne) AddAlertIDs(ids ...int) *DashboardUpdateOne {
	_u.mutation.AddAlertIDs(ids...)
	return _u
}

// AddAlerts adds the "alerts" edges to the Alert entity.
func (_u *DashboardUpdateOne) AddAlerts(v ...*Alert) *DashboardUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAlertIDs(ids...)
}

// Mutation returns the DashboardMutation object of the builder.
func (_u *DashboardUpdateOne) Mutation() *DashboardMutation {
	return _u.mutation
}

// ClearOrganization clears the "organization" edge to the Organization entity.
func (_u *DashboardUpdateOne) ClearOrganization() *DashboardUpdateOne {
	_u.mutation.ClearOrganization()
	return _u
}

// ClearOwner clears the "owner" edge to the Principal entity.
func (_u *DashboardUpdateOne) ClearOwner() *DashboardUpdateOne {
	_u.mutation.ClearOwner()
	return _u
}

// ClearVersions clears all "versions" edges to the DashboardVersion entity.
func (_u *DashboardUpdateOne) ClearVersions() *DashboardUpdateOne {
	_u.mutation.ClearVersions()
	return _u
}

// RemoveVersionIDs removes the "versions" edge to DashboardVersion entities by IDs.
func (_u *DashboardUpdateOne) RemoveVersionIDs(ids ...int) *DashboardUpdateOne {
	_u.mutation.RemoveVersionIDs(ids...)
	return _u
}

// RemoveVersions removes "versions" edges to DashboardVersion entities.
func (_u *DashboardUpdateOne) RemoveVersions(v ...*DashboardVersion) *DashboardUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveVersionIDs(ids...)
}

// ClearAlerts clears all "alerts" edges to the Alert entity.
func (_u *DashboardUpdateOne) ClearAlerts() *DashboardUpdateOne {
	_u.mutation.ClearAlerts()
	return _u
}

// RemoveAlertIDs removes the "alerts" edge to Alert entities by IDs.
func (_u *DashboardUpdateOne) RemoveAlertIDs(ids ...int) *DashboardUpdateOne {
	_u.mutation.RemoveAlertIDs(ids...)
	return _u
}

// RemoveAlerts removes "alerts" edges to Alert entities.
func (_u *DashboardUpdateOne) RemoveAlerts(v ...*Alert) *DashboardUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAlertIDs(ids...)
}

// Where appends a list predicates to the DashboardUpdate builder.
func (_u *DashboardUpdateOne) Where(ps ...predicate.Dashboard) *DashboardUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DashboardUpdateOne) Select(field string, fields ...string) *DashboardUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Dashboard entity.
func (_u *DashboardUpdateOne) Save(ctx context.Context) (*Dashboard, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DashboardUpdateOne) SaveX(ctx context.Context) *Dashboard {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DashboardUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DashboardUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DashboardUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := dashboard.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DashboardUpdateOne) check() error {
	if v, ok := _u.mutation.Slug(); ok {
		if err := dashboard.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "Dashboard.slug": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := dashboard.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Dashboard.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Visibility(); ok {
		if err := dashboard.VisibilityValidator(v); err != nil {
			return &ValidationError{Name: "visibility", err: fmt.Errorf(`ent: validator failed for field "Dashboard.visibility": %w`, err)}
		}
	}
	if _u.mutation.OrganizationCleared() && len(_u.mutation.OrganizationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Dashboard.organization"`)
	}
	return nil
}

func (_u *DashboardUpdateOne) sqlSave(ctx context.Context) (_node *Dashboard, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(dashboard.Table, dashboard.Columns, sqlgraph.NewFieldSpec(dashboard.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Dashboard.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, dashboard.FieldID)
		for _, f := range fields {
			if !dashboard.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != dashboard.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(dashboard.FieldSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(dashboard.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(dashboard.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(dashboard.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Definition(); ok {
		_spec.SetField(dashboard.FieldDefinition, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Visibility(); ok {
		_spec.SetField(dashboard.FieldVisibility, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Archived(); ok {
		_spec.SetField(dashboard.FieldArchived, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(dashboard.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(dashboard.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(dashboard.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.OrganizationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   dashboard.OrganizationTable,
			Columns: []string{dashboard.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrganizationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   dashboard.OrganizationTable,
			Columns: []string{dashboard.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   dashboard.OwnerTable,
			Columns: []string{dashboard.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(principal.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   dashboard.OwnerTable,
			Columns: []string{dashboard.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(principal.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.VersionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   dashboard.VersionsTable,
			Columns: []string{dashboard.VersionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dashboardversion.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedVersionsIDs(); len(nodes) > 0 && !_u.mutation.VersionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   dashboard.VersionsTable,
			Columns: []string{dashboard.VersionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dashboardversion.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.VersionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   dashboard.VersionsTable,
			Columns: []string{dashboard.VersionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dashboardversion.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AlertsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   dashboard.AlertsTable,
			Columns: []string{dashboard.AlertsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(alert.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAlertsIDs(); len(nodes) > 0 && !_u.mutation.AlertsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   dashboard.AlertsTable,
			Columns: []string{dashboard.AlertsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(alert.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AlertsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   dashboard.AlertsTable,
			Columns: []string{dashboard.AlertsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(alert.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Dashboard{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dashboard.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
