// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/plexusone/dashforge/ent/alert"
	"github.com/plexusone/dashforge/ent/dashboard"
	"github.com/plexusone/dashforge/ent/dashboardversion"
	"github.com/plexusone/dashforge/ent/organization"
	"github.com/plexusone/dashforge/ent/predicate"
	"github.com/plexusone/dashforge/ent/principal"
)

// DashboardQuery is the builder for querying Dashboard entities.
type DashboardQuery struct {
	config
	ctx              *QueryContext
	order            []dashboard.OrderOption
	inters           []Interceptor
	predicates       []predicate.Dashboard
	withOrganization *OrganizationQuery
	withOwner        *PrincipalQuery
	withVersions     *DashboardVersionQuery
	withAlerts       *AlertQuery
	withFKs          bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the DashboardQuery builder.
func (_q *DashboardQuery) Where(ps ...predicate.Dashboard) *DashboardQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *DashboardQuery) Limit(limit int) *DashboardQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *DashboardQuery) Offset(offset int) *DashboardQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *DashboardQuery) Unique(unique bool) *DashboardQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *DashboardQuery) Order(o ...dashboard.OrderOption) *DashboardQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryOrganization chains the current query on the "organization" edge.
func (_q *DashboardQuery) QueryOrganization() *OrganizationQuery {
	query := (&OrganizationClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(dashboard.Table, dashboard.FieldID, selector),
			sqlgraph.To(organization.Table, organization.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, dashboard.OrganizationTable, dashboard.OrganizationColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryOwner chains the current query on the "owner" edge.
func (_q *DashboardQuery) QueryOwner() *PrincipalQuery {
	query := (&PrincipalClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(dashboard.Table, dashboard.FieldID, selector),
			sqlgraph.To(principal.Table, principal.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, dashboard.OwnerTable, dashboard.OwnerColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryVersions chains the current query on the "versions" edge.
func (_q *DashboardQuery) QueryVersions() *DashboardVersionQuery {
	query := (&DashboardVersionClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(dashboard.Table, dashboard.FieldID, selector),
			sqlgraph.To(dashboardversion.Table, dashboardversion.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, dashboard.VersionsTable, dashboard.VersionsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryAlerts chains the current query on the "alerts" edge.
func (_q *DashboardQuery) QueryAlerts() *AlertQuery {
	query := (&AlertClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(dashboard.Table, dashboard.FieldID, selector),
			sqlgraph.To(alert.Table, alert.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, dashboard.AlertsTable, dashboard.AlertsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Dashboard entity from the query.
// Returns a *NotFoundError when no Dashboard was found.
func (_q *DashboardQuery) First(ctx context.Context) (*Dashboard, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{dashboard.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *DashboardQuery) FirstX(ctx context.Context) *Dashboard {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Dashboard ID from the query.
// Returns a *NotFoundError when no Dashboard ID was found.
func (_q *DashboardQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{dashboard.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *DashboardQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Dashboard entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Dashboard entity is found.
// Returns a *NotFoundError when no Dashboard entities are found.
func (_q *DashboardQuery) Only(ctx context.Context) (*Dashboard, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{dashboard.Label}
	default:
		return nil, &NotSingularError{dashboard.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *DashboardQuery) OnlyX(ctx context.Context) *Dashboard {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Dashboard ID in the query.
// Returns a *NotSingularError when more than one Dashboard ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *DashboardQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{dashboard.Label}
	default:
		err = &NotSingularError{dashboard.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *DashboardQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Dashboards.
func (_q *DashboardQuery) All(ctx context.Context) ([]*Dashboard, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Dashboard, *DashboardQuery]()
	return withInterceptors[[]*Dashboard](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *DashboardQuery) AllX(ctx context.Context) []*Dashboard {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Dashboard IDs.
func (_q *DashboardQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(dashboard.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *DashboardQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *DashboardQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*DashboardQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *DashboardQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *DashboardQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *DashboardQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the DashboardQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *DashboardQuery) Clone() *DashboardQuery {
	if _q == nil {
		return nil
	}
	return &DashboardQuery{
		config:           _q.config,
		ctx:              _q.ctx.Clone(),
		order:            append([]dashboard.OrderOption{}, _q.order...),
		inters:           append([]Interceptor{}, _q.inters...),
		predicates:       append([]predicate.Dashboard{}, _q.predicates...),
		withOrganization: _q.withOrganization.Clone(),
		withOwner:        _q.withOwner.Clone(),
		withVersions:     _q.withVersions.Clone(),
		withAlerts:       _q.withAlerts.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithOrganization tells the query-builder to eager-load the nodes that are connected to
// the "organization" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *DashboardQuery) WithOrganization(opts ...func(*OrganizationQuery)) *DashboardQuery {
	query := (&OrganizationClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withOrganization = query
	return _q
}

// WithOwner tells the query-builder to eager-load the nodes that are connected to
// the "owner" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *DashboardQuery) WithOwner(opts ...func(*PrincipalQuery)) *DashboardQuery {
	query := (&PrincipalClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withOwner = query
	return _q
}

// WithVersions tells the query-builder to eager-load the nodes that are connected to
// the "versions" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *DashboardQuery) WithVersions(opts ...func(*DashboardVersionQuery)) *DashboardQuery {
	query := (&DashboardVersionClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withVersions = query
	return _q
}

// WithAlerts tells the query-builder to eager-load the nodes that are connected to
// the "alerts" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *DashboardQuery) WithAlerts(opts ...func(*AlertQuery)) *DashboardQuery {
	query := (&AlertClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withAlerts = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Slug string `json:"slug,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Dashboard.Query().
//		GroupBy(dashboard.FieldSlug).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *DashboardQuery) GroupBy(field string, fields ...string) *DashboardGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &DashboardGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = dashboard.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Slug string `json:"slug,omitempty"`
//	}
//
//	client.Dashboard.Query().
//		Select(dashboard.FieldSlug).
//		Scan(ctx, &v)
func (_q *DashboardQuery) Select(fields ...string) *DashboardSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &DashboardSelect{DashboardQuery: _q}
	sbuild.label = dashboard.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a DashboardSelect configured with the given aggregations.
func (_q *DashboardQuery) Aggregate(fns ...AggregateFunc) *DashboardSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *DashboardQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !dashboard.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *DashboardQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Dashboard, error) {
	var (
		nodes       = []*Dashboard{}
		withFKs     = _q.withFKs
		_spec       = _q.querySpec()
		loadedTypes = [4]bool{
			_q.withOrganization != nil,
			_q.withOwner != nil,
			_q.withVersions != nil,
			_q.withAlerts != nil,
		}
	)
	if _q.withOrganization != nil || _q.withOwner != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, dashboard.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Dashboard).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Dashboard{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withOrganization; query != nil {
		if err := _q.loadOrganization(ctx, query, nodes, nil,
			func(n *Dashboard, e *Organization) { n.Edges.Organization = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withOwner; query != nil {
		if err := _q.loadOwner(ctx, query, nodes, nil,
			func(n *Dashboard, e *Principal) { n.Edges.Owner = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withVersions; query != nil {
		if err := _q.loadVersions(ctx, query, nodes,
			func(n *Dashboard) { n.Edges.Versions = []*DashboardVersion{} },
			func(n *Dashboard, e *DashboardVersion) { n.Edges.Versions = append(n.Edges.Versions, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withAlerts; query != nil {
		if err := _q.loadAlerts(ctx, query, nodes,
			func(n *Dashboard) { n.Edges.Alerts = []*Alert{} },
			func(n *Dashboard, e *Alert) { n.Edges.Alerts = append(n.Edges.Alerts, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *DashboardQuery) loadOrganization(ctx context.Context, query *OrganizationQuery, nodes []*Dashboard, init func(*Dashboard), assign func(*Dashboard, *Organization)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*Dashboard)
	for i := range nodes {
		if nodes[i].organization_dashboards == nil {
			continue
		}
		fk := *nodes[i].organization_dashboards
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(organization.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "organization_dashboards" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *DashboardQuery) loadOwner(ctx context.Context, query *PrincipalQuery, nodes []*Dashboard, init func(*Dashboard), assign func(*Dashboard, *Principal)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*Dashboard)
	for i := range nodes {
		if nodes[i].principal_dashboards == nil {
			continue
		}
		fk := *nodes[i].principal_dashboards
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(principal.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "principal_dashboards" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *DashboardQuery) loadVersions(ctx context.Context, query *DashboardVersionQuery, nodes []*Dashboard, init func(*Dashboard), assign func(*Dashboard, *DashboardVersion)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Dashboard)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.DashboardVersion(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(dashboard.VersionsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.dashboard_versions
		if fk == nil {
			return fmt.Errorf(`foreign-key "dashboard_versions" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "dashboard_versions" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *DashboardQuery) loadAlerts(ctx context.Context, query *AlertQuery, nodes []*Dashboard, init func(*Dashboard), assign func(*Dashboard, *Alert)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Dashboard)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Alert(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(dashboard.AlertsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.dashboard_alerts
		if fk == nil {
			return fmt.Errorf(`foreign-key "dashboard_alerts" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "dashboard_alerts" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *DashboardQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *DashboardQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(dashboard.Table, dashboard.Columns, sqlgraph.NewFieldSpec(dashboard.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, dashboard.FieldID)
		for i := range fields {
			if fields[i] != dashboard.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *DashboardQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(dashboard.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = dashboard.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// DashboardGroupBy is the group-by builder for Dashboard entities.
type DashboardGroupBy struct {
	selector
	build *DashboardQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *DashboardGroupBy) Aggregate(fns ...AggregateFunc) *DashboardGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *DashboardGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DashboardQuery, *DashboardGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *DashboardGroupBy) sqlScan(ctx context.Context, root *DashboardQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// DashboardSelect is the builder for selecting fields of Dashboard entities.
type DashboardSelect struct {
	*DashboardQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *DashboardSelect) Aggregate(fns ...AggregateFunc) *DashboardSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *DashboardSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DashboardQuery, *DashboardSelect](ctx, _s.DashboardQuery, _s, _s.inters, v)
}

func (_s *DashboardSelect) sqlScan(ctx context.Context, root *DashboardQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
