// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/plexusone/dashforge/ent/human"
	"github.com/plexusone/dashforge/ent/principal"
)

// Human is the model entity for the Human schema.
type Human struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Parent Principal ID
	PrincipalID uuid.UUID `json:"principal_id,omitempty"`
	// Primary email address
	Email string `json:"email,omitempty"`
	// Full name for display
	Name string `json:"name,omitempty"`
	// Bcrypt password hash for local auth
	PasswordHash string `json:"-"`
	// Profile avatar URL
	AvatarURL *string `json:"avatar_url,omitempty"`
	// Cross-organization admin access
	IsPlatformAdmin bool `json:"is_platform_admin,omitempty"`
	// Last successful authentication time
	LastLoginAt *time.Time `json:"last_login_at,omitempty"`
	// When email was verified
	EmailVerifiedAt *time.Time `json:"email_verified_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the HumanQuery when eager-loading is set.
	Edges        HumanEdges `json:"edges"`
	selectValues sql.SelectValues
}

// HumanEdges holds the relations/edges for other nodes in the graph.
type HumanEdges struct {
	// Principal holds the value of the principal edge.
	Principal *Principal `json:"principal,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// PrincipalOrErr returns the Principal value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e HumanEdges) PrincipalOrErr() (*Principal, error) {
	if e.Principal != nil {
		return e.Principal, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: principal.Label}
	}
	return nil, &NotLoadedError{edge: "principal"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Human) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case human.FieldIsPlatformAdmin:
			values[i] = new(sql.NullBool)
		case human.FieldEmail, human.FieldName, human.FieldPasswordHash, human.FieldAvatarURL:
			values[i] = new(sql.NullString)
		case human.FieldCreatedAt, human.FieldUpdatedAt, human.FieldLastLoginAt, human.FieldEmailVerifiedAt:
			values[i] = new(sql.NullTime)
		case human.FieldID, human.FieldPrincipalID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Human fields.
func (_m *Human) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case human.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case human.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case human.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case human.FieldPrincipalID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field principal_id", values[i])
			} else if value != nil {
				_m.PrincipalID = *value
			}
		case human.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				_m.Email = value.String
			}
		case human.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case human.FieldPasswordHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field password_hash", values[i])
			} else if value.Valid {
				_m.PasswordHash = value.String
			}
		case human.FieldAvatarURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field avatar_url", values[i])
			} else if value.Valid {
				_m.AvatarURL = new(string)
				*_m.AvatarURL = value.String
			}
		case human.FieldIsPlatformAdmin:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_platform_admin", values[i])
			} else if value.Valid {
				_m.IsPlatformAdmin = value.Bool
			}
		case human.FieldLastLoginAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_login_at", values[i])
			} else if value.Valid {
				_m.LastLoginAt = new(time.Time)
				*_m.LastLoginAt = value.Time
			}
		case human.FieldEmailVerifiedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field email_verified_at", values[i])
			} else if value.Valid {
				_m.EmailVerifiedAt = new(time.Time)
				*_m.EmailVerifiedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Human.
// This includes values selected through modifiers, order, etc.
func (_m *Human) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPrincipal queries the "principal" edge of the Human entity.
func (_m *Human) QueryPrincipal() *PrincipalQuery {
	return NewHumanClient(_m.config).QueryPrincipal(_m)
}

// Update returns a builder for updating this Human.
// Note that you need to call Human.Unwrap() before calling this method if this Human
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Human) Update() *HumanUpdateOne {
	return NewHumanClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Human entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Human) Unwrap() *Human {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Human is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Human) String() string {
	var builder strings.Builder
	builder.WriteString("Human(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("principal_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PrincipalID))
	builder.WriteString(", ")
	builder.WriteString("email=")
	builder.WriteString(_m.Email)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("password_hash=<sensitive>")
	builder.WriteString(", ")
	if v := _m.AvatarURL; v != nil {
		builder.WriteString("avatar_url=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("is_platform_admin=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsPlatformAdmin))
	builder.WriteString(", ")
	if v := _m.LastLoginAt; v != nil {
		builder.WriteString("last_login_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.EmailVerifiedAt; v != nil {
		builder.WriteString("email_verified_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// Humen is a parsable slice of Human.
type Humen []*Human
