// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/plexusone/dashforge/ent/human"
	"github.com/plexusone/dashforge/ent/predicate"
)

// HumanUpdate is the builder for updating Human entities.
type HumanUpdate struct {
	config
	hooks    []Hook
	mutation *HumanMutation
}

// Where appends a list predicates to the HumanUpdate builder.
func (_u *HumanUpdate) Where(ps ...predicate.Human) *HumanUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *HumanUpdate) SetUpdatedAt(v time.Time) *HumanUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetEmail sets the "email" field.
func (_u *HumanUpdate) SetEmail(v string) *HumanUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *HumanUpdate) SetNillableEmail(v *string) *HumanUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *HumanUpdate) SetName(v string) *HumanUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *HumanUpdate) SetNillableName(v *string) *HumanUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *HumanUpdate) ClearName() *HumanUpdate {
	_u.mutation.ClearName()
	return _u
}

// SetPasswordHash sets the "password_hash" field.
func (_u *HumanUpdate) SetPasswordHash(v string) *HumanUpdate {
	_u.mutation.SetPasswordHash(v)
	return _u
}

// SetNillablePasswordHash sets the "password_hash" field if the given value is not nil.
func (_u *HumanUpdate) SetNillablePasswordHash(v *string) *HumanUpdate {
	if v != nil {
		_u.SetPasswordHash(*v)
	}
	return _u
}

// ClearPasswordHash clears the value of the "password_hash" field.
func (_u *HumanUpdate) ClearPasswordHash() *HumanUpdate {
	_u.mutation.ClearPasswordHash()
	return _u
}

// SetAvatarURL sets the "avatar_url" field.
func (_u *HumanUpdate) SetAvatarURL(v string) *HumanUpdate {
	_u.mutation.SetAvatarURL(v)
	return _u
}

// SetNillableAvatarURL sets the "avatar_url" field if the given value is not nil.
func (_u *HumanUpdate) SetNillableAvatarURL(v *string) *HumanUpdate {
	if v != nil {
		_u.SetAvatarURL(*v)
	}
	return _u
}

// ClearAvatarURL clears the value of the "avatar_url" field.
func (_u *HumanUpdate) ClearAvatarURL() *HumanUpdate {
	_u.mutation.ClearAvatarURL()
	return _u
}

// SetIsPlatformAdmin sets the "is_platform_admin" field.
func (_u *HumanUpdate) SetIsPlatformAdmin(v bool) *HumanUpdate {
	_u.mutation.SetIsPlatformAdmin(v)
	return _u
}

// SetNillableIsPlatformAdmin sets the "is_platform_admin" field if the given value is not nil.
func (_u *HumanUpdate) SetNillableIsPlatformAdmin(v *bool) *HumanUpdate {
	if v != nil {
		_u.SetIsPlatformAdmin(*v)
	}
	return _u
}

// SetLastLoginAt sets the "last_login_at" field.
func (_u *HumanUpdate) SetLastLoginAt(v time.Time) *HumanUpdate {
	_u.mutation.SetLastLoginAt(v)
	return _u
}

// SetNillableLastLoginAt sets the "last_login_at" field if the given value is not nil.
func (_u *HumanUpdate) SetNillableLastLoginAt(v *time.Time) *HumanUpdate {
	if v != nil {
		_u.SetLastLoginAt(*v)
	}
	return _u
}

// ClearLastLoginAt clears the value of the "last_login_at" field.
func (_u *HumanUpdate) ClearLastLoginAt() *HumanUpdate {
	_u.mutation.ClearLastLoginAt()
	return _u
}

// SetEmailVerifiedAt sets the "email_verified_at" field.
func (_u *HumanUpdate) SetEmailVerifiedAt(v time.Time) *HumanUpdate {
	_u.mutation.SetEmailVerifiedAt(v)
	return _u
}

// SetNillableEmailVerifiedAt sets the "email_verified_at" field if the given value is not nil.
func (_u *HumanUpdate) SetNillableEmailVerifiedAt(v *time.Time) *HumanUpdate {
	if v != nil {
		_u.SetEmailVerifiedAt(*v)
	}
	return _u
}

// ClearEmailVerifiedAt clears the value of the "email_verified_at" field.
func (_u *HumanUpdate) ClearEmailVerifiedAt() *HumanUpdate {
	_u.mutation.ClearEmailVerifiedAt()
	return _u
}

// SetSlug sets the "slug" field.
func (_u *HumanUpdate) SetSlug(v string) *HumanUpdate {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *HumanUpdate) SetNillableSlug(v *string) *HumanUpdate {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// ClearSlug clears the value of the "slug" field.
func (_u *HumanUpdate) ClearSlug() *HumanUpdate {
	_u.mutation.ClearSlug()
	return _u
}

// SetHeadline sets the "headline" field.
func (_u *HumanUpdate) SetHeadline(v string) *HumanUpdate {
	_u.mutation.SetHeadline(v)
	return _u
}

// SetNillableHeadline sets the "headline" field if the given value is not nil.
func (_u *HumanUpdate) SetNillableHeadline(v *string) *HumanUpdate {
	if v != nil {
		_u.SetHeadline(*v)
	}
	return _u
}

// ClearHeadline clears the value of the "headline" field.
func (_u *HumanUpdate) ClearHeadline() *HumanUpdate {
	_u.mutation.ClearHeadline()
	return _u
}

// SetBio sets the "bio" field.
func (_u *HumanUpdate) SetBio(v string) *HumanUpdate {
	_u.mutation.SetBio(v)
	return _u
}

// SetNillableBio sets the "bio" field if the given value is not nil.
func (_u *HumanUpdate) SetNillableBio(v *string) *HumanUpdate {
	if v != nil {
		_u.SetBio(*v)
	}
	return _u
}

// ClearBio clears the value of the "bio" field.
func (_u *HumanUpdate) ClearBio() *HumanUpdate {
	_u.mutation.ClearBio()
	return _u
}

// SetLinkedinURL sets the "linkedin_url" field.
func (_u *HumanUpdate) SetLinkedinURL(v string) *HumanUpdate {
	_u.mutation.SetLinkedinURL(v)
	return _u
}

// SetNillableLinkedinURL sets the "linkedin_url" field if the given value is not nil.
func (_u *HumanUpdate) SetNillableLinkedinURL(v *string) *HumanUpdate {
	if v != nil {
		_u.SetLinkedinURL(*v)
	}
	return _u
}

// ClearLinkedinURL clears the value of the "linkedin_url" field.
func (_u *HumanUpdate) ClearLinkedinURL() *HumanUpdate {
	_u.mutation.ClearLinkedinURL()
	return _u
}

// SetGithubURL sets the "github_url" field.
func (_u *HumanUpdate) SetGithubURL(v string) *HumanUpdate {
	_u.mutation.SetGithubURL(v)
	return _u
}

// SetNillableGithubURL sets the "github_url" field if the given value is not nil.
func (_u *HumanUpdate) SetNillableGithubURL(v *string) *HumanUpdate {
	if v != nil {
		_u.SetGithubURL(*v)
	}
	return _u
}

// ClearGithubURL clears the value of the "github_url" field.
func (_u *HumanUpdate) ClearGithubURL() *HumanUpdate {
	_u.mutation.ClearGithubURL()
	return _u
}

// SetTwitterURL sets the "twitter_url" field.
func (_u *HumanUpdate) SetTwitterURL(v string) *HumanUpdate {
	_u.mutation.SetTwitterURL(v)
	return _u
}

// SetNillableTwitterURL sets the "twitter_url" field if the given value is not nil.
func (_u *HumanUpdate) SetNillableTwitterURL(v *string) *HumanUpdate {
	if v != nil {
		_u.SetTwitterURL(*v)
	}
	return _u
}

// ClearTwitterURL clears the value of the "twitter_url" field.
func (_u *HumanUpdate) ClearTwitterURL() *HumanUpdate {
	_u.mutation.ClearTwitterURL()
	return _u
}

// SetWebsiteURL sets the "website_url" field.
func (_u *HumanUpdate) SetWebsiteURL(v string) *HumanUpdate {
	_u.mutation.SetWebsiteURL(v)
	return _u
}

// SetNillableWebsiteURL sets the "website_url" field if the given value is not nil.
func (_u *HumanUpdate) SetNillableWebsiteURL(v *string) *HumanUpdate {
	if v != nil {
		_u.SetWebsiteURL(*v)
	}
	return _u
}

// ClearWebsiteURL clears the value of the "website_url" field.
func (_u *HumanUpdate) ClearWebsiteURL() *HumanUpdate {
	_u.mutation.ClearWebsiteURL()
	return _u
}

// SetPublicProfile sets the "public_profile" field.
func (_u *HumanUpdate) SetPublicProfile(v bool) *HumanUpdate {
	_u.mutation.SetPublicProfile(v)
	return _u
}

// SetNillablePublicProfile sets the "public_profile" field if the given value is not nil.
func (_u *HumanUpdate) SetNillablePublicProfile(v *bool) *HumanUpdate {
	if v != nil {
		_u.SetPublicProfile(*v)
	}
	return _u
}

// Mutation returns the HumanMutation object of the builder.
func (_u *HumanUpdate) Mutation() *HumanMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *HumanUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *HumanUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *HumanUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *HumanUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *HumanUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := human.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *HumanUpdate) check() error {
	if v, ok := _u.mutation.Email(); ok {
		if err := human.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "Human.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Slug(); ok {
		if err := human.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "Human.slug": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Headline(); ok {
		if err := human.HeadlineValidator(v); err != nil {
			return &ValidationError{Name: "headline", err: fmt.Errorf(`ent: validator failed for field "Human.headline": %w`, err)}
		}
	}
	if _u.mutation.PrincipalCleared() && len(_u.mutation.PrincipalIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Human.principal"`)
	}
	return nil
}

func (_u *HumanUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(human.Table, human.Columns, sqlgraph.NewFieldSpec(human.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(human.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(human.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(human.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(human.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.PasswordHash(); ok {
		_spec.SetField(human.FieldPasswordHash, field.TypeString, value)
	}
	if _u.mutation.PasswordHashCleared() {
		_spec.ClearField(human.FieldPasswordHash, field.TypeString)
	}
	if value, ok := _u.mutation.AvatarURL(); ok {
		_spec.SetField(human.FieldAvatarURL, field.TypeString, value)
	}
	if _u.mutation.AvatarURLCleared() {
		_spec.ClearField(human.FieldAvatarURL, field.TypeString)
	}
	if value, ok := _u.mutation.IsPlatformAdmin(); ok {
		_spec.SetField(human.FieldIsPlatformAdmin, field.TypeBool, value)
	}
	if value, ok := _u.mutation.LastLoginAt(); ok {
		_spec.SetField(human.FieldLastLoginAt, field.TypeTime, value)
	}
	if _u.mutation.LastLoginAtCleared() {
		_spec.ClearField(human.FieldLastLoginAt, field.TypeTime)
	}
	if value, ok := _u.mutation.EmailVerifiedAt(); ok {
		_spec.SetField(human.FieldEmailVerifiedAt, field.TypeTime, value)
	}
	if _u.mutation.EmailVerifiedAtCleared() {
		_spec.ClearField(human.FieldEmailVerifiedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(human.FieldSlug, field.TypeString, value)
	}
	if _u.mutation.SlugCleared() {
		_spec.ClearField(human.FieldSlug, field.TypeString)
	}
	if value, ok := _u.mutation.Headline(); ok {
		_spec.SetField(human.FieldHeadline, field.TypeString, value)
	}
	if _u.mutation.HeadlineCleared() {
		_spec.ClearField(human.FieldHeadline, field.TypeString)
	}
	if value, ok := _u.mutation.Bio(); ok {
		_spec.SetField(human.FieldBio, field.TypeString, value)
	}
	if _u.mutation.BioCleared() {
		_spec.ClearField(human.FieldBio, field.TypeString)
	}
	if value, ok := _u.mutation.LinkedinURL(); ok {
		_spec.SetField(human.FieldLinkedinURL, field.TypeString, value)
	}
	if _u.mutation.LinkedinURLCleared() {
		_spec.ClearField(human.FieldLinkedinURL, field.TypeString)
	}
	if value, ok := _u.mutation.GithubURL(); ok {
		_spec.SetField(human.FieldGithubURL, field.TypeString, value)
	}
	if _u.mutation.GithubURLCleared() {
		_spec.ClearField(human.FieldGithubURL, field.TypeString)
	}
	if value, ok := _u.mutation.TwitterURL(); ok {
		_spec.SetField(human.FieldTwitterURL, field.TypeString, value)
	}
	if _u.mutation.TwitterURLCleared() {
		_spec.ClearField(human.FieldTwitterURL, field.TypeString)
	}
	if value, ok := _u.mutation.WebsiteURL(); ok {
		_spec.SetField(human.FieldWebsiteURL, field.TypeString, value)
	}
	if _u.mutation.WebsiteURLCleared() {
		_spec.ClearField(human.FieldWebsiteURL, field.TypeString)
	}
	if value, ok := _u.mutation.PublicProfile(); ok {
		_spec.SetField(human.FieldPublicProfile, field.TypeBool, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{human.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// HumanUpdateOne is the builder for updating a single Human entity.
type HumanUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *HumanMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *HumanUpdateOne) SetUpdatedAt(v time.Time) *HumanUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetEmail sets the "email" field.
func (_u *HumanUpdateOne) SetEmail(v string) *HumanUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *HumanUpdateOne) SetNillableEmail(v *string) *HumanUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *HumanUpdateOne) SetName(v string) *HumanUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *HumanUpdateOne) SetNillableName(v *string) *HumanUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *HumanUpdateOne) ClearName() *HumanUpdateOne {
	_u.mutation.ClearName()
	return _u
}

// SetPasswordHash sets the "password_hash" field.
func (_u *HumanUpdateOne) SetPasswordHash(v string) *HumanUpdateOne {
	_u.mutation.SetPasswordHash(v)
	return _u
}

// SetNillablePasswordHash sets the "password_hash" field if the given value is not nil.
func (_u *HumanUpdateOne) SetNillablePasswordHash(v *string) *HumanUpdateOne {
	if v != nil {
		_u.SetPasswordHash(*v)
	}
	return _u
}

// ClearPasswordHash clears the value of the "password_hash" field.
func (_u *HumanUpdateOne) ClearPasswordHash() *HumanUpdateOne {
	_u.mutation.ClearPasswordHash()
	return _u
}

// SetAvatarURL sets the "avatar_url" field.
func (_u *HumanUpdateOne) SetAvatarURL(v string) *HumanUpdateOne {
	_u.mutation.SetAvatarURL(v)
	return _u
}

// SetNillableAvatarURL sets the "avatar_url" field if the given value is not nil.
func (_u *HumanUpdateOne) SetNillableAvatarURL(v *string) *HumanUpdateOne {
	if v != nil {
		_u.SetAvatarURL(*v)
	}
	return _u
}

// ClearAvatarURL clears the value of the "avatar_url" field.
func (_u *HumanUpdateOne) ClearAvatarURL() *HumanUpdateOne {
	_u.mutation.ClearAvatarURL()
	return _u
}

// SetIsPlatformAdmin sets the "is_platform_admin" field.
func (_u *HumanUpdateOne) SetIsPlatformAdmin(v bool) *HumanUpdateOne {
	_u.mutation.SetIsPlatformAdmin(v)
	return _u
}

// SetNillableIsPlatformAdmin sets the "is_platform_admin" field if the given value is not nil.
func (_u *HumanUpdateOne) SetNillableIsPlatformAdmin(v *bool) *HumanUpdateOne {
	if v != nil {
		_u.SetIsPlatformAdmin(*v)
	}
	return _u
}

// SetLastLoginAt sets the "last_login_at" field.
func (_u *HumanUpdateOne) SetLastLoginAt(v time.Time) *HumanUpdateOne {
	_u.mutation.SetLastLoginAt(v)
	return _u
}

// SetNillableLastLoginAt sets the "last_login_at" field if the given value is not nil.
func (_u *HumanUpdateOne) SetNillableLastLoginAt(v *time.Time) *HumanUpdateOne {
	if v != nil {
		_u.SetLastLoginAt(*v)
	}
	return _u
}

// ClearLastLoginAt clears the value of the "last_login_at" field.
func (_u *HumanUpdateOne) ClearLastLoginAt() *HumanUpdateOne {
	_u.mutation.ClearLastLoginAt()
	return _u
}

// SetEmailVerifiedAt sets the "email_verified_at" field.
func (_u *HumanUpdateOne) SetEmailVerifiedAt(v time.Time) *HumanUpdateOne {
	_u.mutation.SetEmailVerifiedAt(v)
	return _u
}

// SetNillableEmailVerifiedAt sets the "email_verified_at" field if the given value is not nil.
func (_u *HumanUpdateOne) SetNillableEmailVerifiedAt(v *time.Time) *HumanUpdateOne {
	if v != nil {
		_u.SetEmailVerifiedAt(*v)
	}
	return _u
}

// ClearEmailVerifiedAt clears the value of the "email_verified_at" field.
func (_u *HumanUpdateOne) ClearEmailVerifiedAt() *HumanUpdateOne {
	_u.mutation.ClearEmailVerifiedAt()
	return _u
}

// SetSlug sets the "slug" field.
func (_u *HumanUpdateOne) SetSlug(v string) *HumanUpdateOne {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *HumanUpdateOne) SetNillableSlug(v *string) *HumanUpdateOne {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// ClearSlug clears the value of the "slug" field.
func (_u *HumanUpdateOne) ClearSlug() *HumanUpdateOne {
	_u.mutation.ClearSlug()
	return _u
}

// SetHeadline sets the "headline" field.
func (_u *HumanUpdateOne) SetHeadline(v string) *HumanUpdateOne {
	_u.mutation.SetHeadline(v)
	return _u
}

// SetNillableHeadline sets the "headline" field if the given value is not nil.
func (_u *HumanUpdateOne) SetNillableHeadline(v *string) *HumanUpdateOne {
	if v != nil {
		_u.SetHeadline(*v)
	}
	return _u
}

// ClearHeadline clears the value of the "headline" field.
func (_u *HumanUpdateOne) ClearHeadline() *HumanUpdateOne {
	_u.mutation.ClearHeadline()
	return _u
}

// SetBio sets the "bio" field.
func (_u *HumanUpdateOne) SetBio(v string) *HumanUpdateOne {
	_u.mutation.SetBio(v)
	return _u
}

// SetNillableBio sets the "bio" field if the given value is not nil.
func (_u *HumanUpdateOne) SetNillableBio(v *string) *HumanUpdateOne {
	if v != nil {
		_u.SetBio(*v)
	}
	return _u
}

// ClearBio clears the value of the "bio" field.
func (_u *HumanUpdateOne) ClearBio() *HumanUpdateOne {
	_u.mutation.ClearBio()
	return _u
}

// SetLinkedinURL sets the "linkedin_url" field.
func (_u *HumanUpdateOne) SetLinkedinURL(v string) *HumanUpdateOne {
	_u.mutation.SetLinkedinURL(v)
	return _u
}

// SetNillableLinkedinURL sets the "linkedin_url" field if the given value is not nil.
func (_u *HumanUpdateOne) SetNillableLinkedinURL(v *string) *HumanUpdateOne {
	if v != nil {
		_u.SetLinkedinURL(*v)
	}
	return _u
}

// ClearLinkedinURL clears the value of the "linkedin_url" field.
func (_u *HumanUpdateOne) ClearLinkedinURL() *HumanUpdateOne {
	_u.mutation.ClearLinkedinURL()
	return _u
}

// SetGithubURL sets the "github_url" field.
func (_u *HumanUpdateOne) SetGithubURL(v string) *HumanUpdateOne {
	_u.mutation.SetGithubURL(v)
	return _u
}

// SetNillableGithubURL sets the "github_url" field if the given value is not nil.
func (_u *HumanUpdateOne) SetNillableGithubURL(v *string) *HumanUpdateOne {
	if v != nil {
		_u.SetGithubURL(*v)
	}
	return _u
}

// ClearGithubURL clears the value of the "github_url" field.
func (_u *HumanUpdateOne) ClearGithubURL() *HumanUpdateOne {
	_u.mutation.ClearGithubURL()
	return _u
}

// SetTwitterURL sets the "twitter_url" field.
func (_u *HumanUpdateOne) SetTwitterURL(v string) *HumanUpdateOne {
	_u.mutation.SetTwitterURL(v)
	return _u
}

// SetNillableTwitterURL sets the "twitter_url" field if the given value is not nil.
func (_u *HumanUpdateOne) SetNillableTwitterURL(v *string) *HumanUpdateOne {
	if v != nil {
		_u.SetTwitterURL(*v)
	}
	return _u
}

// ClearTwitterURL clears the value of the "twitter_url" field.
func (_u *HumanUpdateOne) ClearTwitterURL() *HumanUpdateOne {
	_u.mutation.ClearTwitterURL()
	return _u
}

// SetWebsiteURL sets the "website_url" field.
func (_u *HumanUpdateOne) SetWebsiteURL(v string) *HumanUpdateOne {
	_u.mutation.SetWebsiteURL(v)
	return _u
}

// SetNillableWebsiteURL sets the "website_url" field if the given value is not nil.
func (_u *HumanUpdateOne) SetNillableWebsiteURL(v *string) *HumanUpdateOne {
	if v != nil {
		_u.SetWebsiteURL(*v)
	}
	return _u
}

// ClearWebsiteURL clears the value of the "website_url" field.
func (_u *HumanUpdateOne) ClearWebsiteURL() *HumanUpdateOne {
	_u.mutation.ClearWebsiteURL()
	return _u
}

// SetPublicProfile sets the "public_profile" field.
func (_u *HumanUpdateOne) SetPublicProfile(v bool) *HumanUpdateOne {
	_u.mutation.SetPublicProfile(v)
	return _u
}

// SetNillablePublicProfile sets the "public_profile" field if the given value is not nil.
func (_u *HumanUpdateOne) SetNillablePublicProfile(v *bool) *HumanUpdateOne {
	if v != nil {
		_u.SetPublicProfile(*v)
	}
	return _u
}

// Mutation returns the HumanMutation object of the builder.
func (_u *HumanUpdateOne) Mutation() *HumanMutation {
	return _u.mutation
}

// Where appends a list predicates to the HumanUpdate builder.
func (_u *HumanUpdateOne) Where(ps ...predicate.Human) *HumanUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *HumanUpdateOne) Select(field string, fields ...string) *HumanUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Human entity.
func (_u *HumanUpdateOne) Save(ctx context.Context) (*Human, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *HumanUpdateOne) SaveX(ctx context.Context) *Human {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *HumanUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *HumanUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *HumanUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := human.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *HumanUpdateOne) check() error {
	if v, ok := _u.mutation.Email(); ok {
		if err := human.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "Human.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Slug(); ok {
		if err := human.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "Human.slug": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Headline(); ok {
		if err := human.HeadlineValidator(v); err != nil {
			return &ValidationError{Name: "headline", err: fmt.Errorf(`ent: validator failed for field "Human.headline": %w`, err)}
		}
	}
	if _u.mutation.PrincipalCleared() && len(_u.mutation.PrincipalIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Human.principal"`)
	}
	return nil
}

func (_u *HumanUpdateOne) sqlSave(ctx context.Context) (_node *Human, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(human.Table, human.Columns, sqlgraph.NewFieldSpec(human.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Human.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, human.FieldID)
		for _, f := range fields {
			if !human.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != human.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(human.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(human.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(human.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(human.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.PasswordHash(); ok {
		_spec.SetField(human.FieldPasswordHash, field.TypeString, value)
	}
	if _u.mutation.PasswordHashCleared() {
		_spec.ClearField(human.FieldPasswordHash, field.TypeString)
	}
	if value, ok := _u.mutation.AvatarURL(); ok {
		_spec.SetField(human.FieldAvatarURL, field.TypeString, value)
	}
	if _u.mutation.AvatarURLCleared() {
		_spec.ClearField(human.FieldAvatarURL, field.TypeString)
	}
	if value, ok := _u.mutation.IsPlatformAdmin(); ok {
		_spec.SetField(human.FieldIsPlatformAdmin, field.TypeBool, value)
	}
	if value, ok := _u.mutation.LastLoginAt(); ok {
		_spec.SetField(human.FieldLastLoginAt, field.TypeTime, value)
	}
	if _u.mutation.LastLoginAtCleared() {
		_spec.ClearField(human.FieldLastLoginAt, field.TypeTime)
	}
	if value, ok := _u.mutation.EmailVerifiedAt(); ok {
		_spec.SetField(human.FieldEmailVerifiedAt, field.TypeTime, value)
	}
	if _u.mutation.EmailVerifiedAtCleared() {
		_spec.ClearField(human.FieldEmailVerifiedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(human.FieldSlug, field.TypeString, value)
	}
	if _u.mutation.SlugCleared() {
		_spec.ClearField(human.FieldSlug, field.TypeString)
	}
	if value, ok := _u.mutation.Headline(); ok {
		_spec.SetField(human.FieldHeadline, field.TypeString, value)
	}
	if _u.mutation.HeadlineCleared() {
		_spec.ClearField(human.FieldHeadline, field.TypeString)
	}
	if value, ok := _u.mutation.Bio(); ok {
		_spec.SetField(human.FieldBio, field.TypeString, value)
	}
	if _u.mutation.BioCleared() {
		_spec.ClearField(human.FieldBio, field.TypeString)
	}
	if value, ok := _u.mutation.LinkedinURL(); ok {
		_spec.SetField(human.FieldLinkedinURL, field.TypeString, value)
	}
	if _u.mutation.LinkedinURLCleared() {
		_spec.ClearField(human.FieldLinkedinURL, field.TypeString)
	}
	if value, ok := _u.mutation.GithubURL(); ok {
		_spec.SetField(human.FieldGithubURL, field.TypeString, value)
	}
	if _u.mutation.GithubURLCleared() {
		_spec.ClearField(human.FieldGithubURL, field.TypeString)
	}
	if value, ok := _u.mutation.TwitterURL(); ok {
		_spec.SetField(human.FieldTwitterURL, field.TypeString, value)
	}
	if _u.mutation.TwitterURLCleared() {
		_spec.ClearField(human.FieldTwitterURL, field.TypeString)
	}
	if value, ok := _u.mutation.WebsiteURL(); ok {
		_spec.SetField(human.FieldWebsiteURL, field.TypeString, value)
	}
	if _u.mutation.WebsiteURLCleared() {
		_spec.ClearField(human.FieldWebsiteURL, field.TypeString)
	}
	if value, ok := _u.mutation.PublicProfile(); ok {
		_spec.SetField(human.FieldPublicProfile, field.TypeBool, value)
	}
	_node = &Human{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{human.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
