// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/plexusone/dashforge/ent/dashboardtemplate"
	"github.com/plexusone/dashforge/ent/listing"
	"github.com/plexusone/dashforge/ent/principal"
	"github.com/plexusone/dashforge/ent/publisher"
)

// Listing is the model entity for the Listing schema.
type Listing struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Organization that created this listing
	CreatorOrgID uuid.UUID `json:"creator_org_id,omitempty"`
	// Principal who owns this listing
	OwnerID uuid.UUID `json:"owner_id,omitempty"`
	// Type of product: course, dashboard_template, etc.
	ProductType string `json:"product_type,omitempty"`
	// Reference to the actual product (optional for drafts)
	ProductID *uuid.UUID `json:"product_id,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// PricingModel holds the value of the "pricing_model" field.
	PricingModel listing.PricingModel `json:"pricing_model,omitempty"`
	// Price in cents (0 for free)
	PriceCents int64 `json:"price_cents,omitempty"`
	// ISO 4217 currency code
	Currency string `json:"currency,omitempty"`
	// Status holds the value of the "status" field.
	Status listing.Status `json:"status,omitempty"`
	// App-specific metadata
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// When the listing was published
	PublishedAt *time.Time `json:"published_at,omitempty"`
	// Allow preview of template before purchase
	PreviewEnabled bool `json:"preview_enabled,omitempty"`
	// Searchable tags for marketplace discovery
	Tags []string `json:"tags,omitempty"`
	// Listing category
	Category string `json:"category,omitempty"`
	// Number of times this template has been installed
	InstallCount int `json:"install_count,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ListingQuery when eager-loading is set.
	Edges        ListingEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ListingEdges holds the relations/edges for other nodes in the graph.
type ListingEdges struct {
	// Publisher holds the value of the publisher edge.
	Publisher *Publisher `json:"publisher,omitempty"`
	// Owner holds the value of the owner edge.
	Owner *Principal `json:"owner,omitempty"`
	// Template holds the value of the template edge.
	Template *DashboardTemplate `json:"template,omitempty"`
	// Licenses holds the value of the licenses edge.
	Licenses []*License `json:"licenses,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// PublisherOrErr returns the Publisher value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ListingEdges) PublisherOrErr() (*Publisher, error) {
	if e.Publisher != nil {
		return e.Publisher, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: publisher.Label}
	}
	return nil, &NotLoadedError{edge: "publisher"}
}

// OwnerOrErr returns the Owner value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ListingEdges) OwnerOrErr() (*Principal, error) {
	if e.Owner != nil {
		return e.Owner, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: principal.Label}
	}
	return nil, &NotLoadedError{edge: "owner"}
}

// TemplateOrErr returns the Template value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ListingEdges) TemplateOrErr() (*DashboardTemplate, error) {
	if e.Template != nil {
		return e.Template, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: dashboardtemplate.Label}
	}
	return nil, &NotLoadedError{edge: "template"}
}

// LicensesOrErr returns the Licenses value or an error if the edge
// was not loaded in eager-loading.
func (e ListingEdges) LicensesOrErr() ([]*License, error) {
	if e.loadedTypes[3] {
		return e.Licenses, nil
	}
	return nil, &NotLoadedError{edge: "licenses"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Listing) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case listing.FieldProductID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case listing.FieldMetadata, listing.FieldTags:
			values[i] = new([]byte)
		case listing.FieldPreviewEnabled:
			values[i] = new(sql.NullBool)
		case listing.FieldPriceCents, listing.FieldInstallCount:
			values[i] = new(sql.NullInt64)
		case listing.FieldProductType, listing.FieldTitle, listing.FieldDescription, listing.FieldPricingModel, listing.FieldCurrency, listing.FieldStatus, listing.FieldCategory:
			values[i] = new(sql.NullString)
		case listing.FieldCreatedAt, listing.FieldUpdatedAt, listing.FieldPublishedAt:
			values[i] = new(sql.NullTime)
		case listing.FieldID, listing.FieldCreatorOrgID, listing.FieldOwnerID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Listing fields.
func (_m *Listing) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case listing.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case listing.FieldCreatorOrgID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field creator_org_id", values[i])
			} else if value != nil {
				_m.CreatorOrgID = *value
			}
		case listing.FieldOwnerID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field owner_id", values[i])
			} else if value != nil {
				_m.OwnerID = *value
			}
		case listing.FieldProductType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field product_type", values[i])
			} else if value.Valid {
				_m.ProductType = value.String
			}
		case listing.FieldProductID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field product_id", values[i])
			} else if value.Valid {
				_m.ProductID = new(uuid.UUID)
				*_m.ProductID = *value.S.(*uuid.UUID)
			}
		case listing.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case listing.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case listing.FieldPricingModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field pricing_model", values[i])
			} else if value.Valid {
				_m.PricingModel = listing.PricingModel(value.String)
			}
		case listing.FieldPriceCents:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field price_cents", values[i])
			} else if value.Valid {
				_m.PriceCents = value.Int64
			}
		case listing.FieldCurrency:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field currency", values[i])
			} else if value.Valid {
				_m.Currency = value.String
			}
		case listing.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = listing.Status(value.String)
			}
		case listing.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		case listing.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case listing.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case listing.FieldPublishedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field published_at", values[i])
			} else if value.Valid {
				_m.PublishedAt = new(time.Time)
				*_m.PublishedAt = value.Time
			}
		case listing.FieldPreviewEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field preview_enabled", values[i])
			} else if value.Valid {
				_m.PreviewEnabled = value.Bool
			}
		case listing.FieldTags:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field tags", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Tags); err != nil {
					return fmt.Errorf("unmarshal field tags: %w", err)
				}
			}
		case listing.FieldCategory:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field category", values[i])
			} else if value.Valid {
				_m.Category = value.String
			}
		case listing.FieldInstallCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field install_count", values[i])
			} else if value.Valid {
				_m.InstallCount = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Listing.
// This includes values selected through modifiers, order, etc.
func (_m *Listing) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPublisher queries the "publisher" edge of the Listing entity.
func (_m *Listing) QueryPublisher() *PublisherQuery {
	return NewListingClient(_m.config).QueryPublisher(_m)
}

// QueryOwner queries the "owner" edge of the Listing entity.
func (_m *Listing) QueryOwner() *PrincipalQuery {
	return NewListingClient(_m.config).QueryOwner(_m)
}

// QueryTemplate queries the "template" edge of the Listing entity.
func (_m *Listing) QueryTemplate() *DashboardTemplateQuery {
	return NewListingClient(_m.config).QueryTemplate(_m)
}

// QueryLicenses queries the "licenses" edge of the Listing entity.
func (_m *Listing) QueryLicenses() *LicenseQuery {
	return NewListingClient(_m.config).QueryLicenses(_m)
}

// Update returns a builder for updating this Listing.
// Note that you need to call Listing.Unwrap() before calling this method if this Listing
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Listing) Update() *ListingUpdateOne {
	return NewListingClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Listing entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Listing) Unwrap() *Listing {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Listing is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Listing) String() string {
	var builder strings.Builder
	builder.WriteString("Listing(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("creator_org_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreatorOrgID))
	builder.WriteString(", ")
	builder.WriteString("owner_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.OwnerID))
	builder.WriteString(", ")
	builder.WriteString("product_type=")
	builder.WriteString(_m.ProductType)
	builder.WriteString(", ")
	if v := _m.ProductID; v != nil {
		builder.WriteString("product_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("pricing_model=")
	builder.WriteString(fmt.Sprintf("%v", _m.PricingModel))
	builder.WriteString(", ")
	builder.WriteString("price_cents=")
	builder.WriteString(fmt.Sprintf("%v", _m.PriceCents))
	builder.WriteString(", ")
	builder.WriteString("currency=")
	builder.WriteString(_m.Currency)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.Metadata))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.PublishedAt; v != nil {
		builder.WriteString("published_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("preview_enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.PreviewEnabled))
	builder.WriteString(", ")
	builder.WriteString("tags=")
	builder.WriteString(fmt.Sprintf("%v", _m.Tags))
	builder.WriteString(", ")
	builder.WriteString("category=")
	builder.WriteString(_m.Category)
	builder.WriteString(", ")
	builder.WriteString("install_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.InstallCount))
	builder.WriteByte(')')
	return builder.String()
}

// Listings is a parsable slice of Listing.
type Listings []*Listing
