// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/plexusone/dashforge/ent/organization"
	"github.com/plexusone/dashforge/ent/predicate"
	"github.com/plexusone/dashforge/ent/subscription"
)

// SubscriptionUpdate is the builder for updating Subscription entities.
type SubscriptionUpdate struct {
	config
	hooks    []Hook
	mutation *SubscriptionMutation
}

// Where appends a list predicates to the SubscriptionUpdate builder.
func (_u *SubscriptionUpdate) Where(ps ...predicate.Subscription) *SubscriptionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetOrganizationID sets the "organization_id" field.
func (_u *SubscriptionUpdate) SetOrganizationID(v uuid.UUID) *SubscriptionUpdate {
	_u.mutation.SetOrganizationID(v)
	return _u
}

// SetNillableOrganizationID sets the "organization_id" field if the given value is not nil.
func (_u *SubscriptionUpdate) SetNillableOrganizationID(v *uuid.UUID) *SubscriptionUpdate {
	if v != nil {
		_u.SetOrganizationID(*v)
	}
	return _u
}

// SetPlanTier sets the "plan_tier" field.
func (_u *SubscriptionUpdate) SetPlanTier(v string) *SubscriptionUpdate {
	_u.mutation.SetPlanTier(v)
	return _u
}

// SetNillablePlanTier sets the "plan_tier" field if the given value is not nil.
func (_u *SubscriptionUpdate) SetNillablePlanTier(v *string) *SubscriptionUpdate {
	if v != nil {
		_u.SetPlanTier(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *SubscriptionUpdate) SetStatus(v subscription.Status) *SubscriptionUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SubscriptionUpdate) SetNillableStatus(v *subscription.Status) *SubscriptionUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCurrentPeriodStart sets the "current_period_start" field.
func (_u *SubscriptionUpdate) SetCurrentPeriodStart(v time.Time) *SubscriptionUpdate {
	_u.mutation.SetCurrentPeriodStart(v)
	return _u
}

// SetNillableCurrentPeriodStart sets the "current_period_start" field if the given value is not nil.
func (_u *SubscriptionUpdate) SetNillableCurrentPeriodStart(v *time.Time) *SubscriptionUpdate {
	if v != nil {
		_u.SetCurrentPeriodStart(*v)
	}
	return _u
}

// SetCurrentPeriodEnd sets the "current_period_end" field.
func (_u *SubscriptionUpdate) SetCurrentPeriodEnd(v time.Time) *SubscriptionUpdate {
	_u.mutation.SetCurrentPeriodEnd(v)
	return _u
}

// SetNillableCurrentPeriodEnd sets the "current_period_end" field if the given value is not nil.
func (_u *SubscriptionUpdate) SetNillableCurrentPeriodEnd(v *time.Time) *SubscriptionUpdate {
	if v != nil {
		_u.SetCurrentPeriodEnd(*v)
	}
	return _u
}

// SetStripeSubscriptionID sets the "stripe_subscription_id" field.
func (_u *SubscriptionUpdate) SetStripeSubscriptionID(v string) *SubscriptionUpdate {
	_u.mutation.SetStripeSubscriptionID(v)
	return _u
}

// SetNillableStripeSubscriptionID sets the "stripe_subscription_id" field if the given value is not nil.
func (_u *SubscriptionUpdate) SetNillableStripeSubscriptionID(v *string) *SubscriptionUpdate {
	if v != nil {
		_u.SetStripeSubscriptionID(*v)
	}
	return _u
}

// ClearStripeSubscriptionID clears the value of the "stripe_subscription_id" field.
func (_u *SubscriptionUpdate) ClearStripeSubscriptionID() *SubscriptionUpdate {
	_u.mutation.ClearStripeSubscriptionID()
	return _u
}

// SetStripeCustomerID sets the "stripe_customer_id" field.
func (_u *SubscriptionUpdate) SetStripeCustomerID(v string) *SubscriptionUpdate {
	_u.mutation.SetStripeCustomerID(v)
	return _u
}

// SetNillableStripeCustomerID sets the "stripe_customer_id" field if the given value is not nil.
func (_u *SubscriptionUpdate) SetNillableStripeCustomerID(v *string) *SubscriptionUpdate {
	if v != nil {
		_u.SetStripeCustomerID(*v)
	}
	return _u
}

// ClearStripeCustomerID clears the value of the "stripe_customer_id" field.
func (_u *SubscriptionUpdate) ClearStripeCustomerID() *SubscriptionUpdate {
	_u.mutation.ClearStripeCustomerID()
	return _u
}

// SetCancelAtPeriodEnd sets the "cancel_at_period_end" field.
func (_u *SubscriptionUpdate) SetCancelAtPeriodEnd(v bool) *SubscriptionUpdate {
	_u.mutation.SetCancelAtPeriodEnd(v)
	return _u
}

// SetNillableCancelAtPeriodEnd sets the "cancel_at_period_end" field if the given value is not nil.
func (_u *SubscriptionUpdate) SetNillableCancelAtPeriodEnd(v *bool) *SubscriptionUpdate {
	if v != nil {
		_u.SetCancelAtPeriodEnd(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SubscriptionUpdate) SetUpdatedAt(v time.Time) *SubscriptionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetMaxDashboards sets the "max_dashboards" field.
func (_u *SubscriptionUpdate) SetMaxDashboards(v int) *SubscriptionUpdate {
	_u.mutation.ResetMaxDashboards()
	_u.mutation.SetMaxDashboards(v)
	return _u
}

// SetNillableMaxDashboards sets the "max_dashboards" field if the given value is not nil.
func (_u *SubscriptionUpdate) SetNillableMaxDashboards(v *int) *SubscriptionUpdate {
	if v != nil {
		_u.SetMaxDashboards(*v)
	}
	return _u
}

// AddMaxDashboards adds value to the "max_dashboards" field.
func (_u *SubscriptionUpdate) AddMaxDashboards(v int) *SubscriptionUpdate {
	_u.mutation.AddMaxDashboards(v)
	return _u
}

// ClearMaxDashboards clears the value of the "max_dashboards" field.
func (_u *SubscriptionUpdate) ClearMaxDashboards() *SubscriptionUpdate {
	_u.mutation.ClearMaxDashboards()
	return _u
}

// SetMaxDatasources sets the "max_datasources" field.
func (_u *SubscriptionUpdate) SetMaxDatasources(v int) *SubscriptionUpdate {
	_u.mutation.ResetMaxDatasources()
	_u.mutation.SetMaxDatasources(v)
	return _u
}

// SetNillableMaxDatasources sets the "max_datasources" field if the given value is not nil.
func (_u *SubscriptionUpdate) SetNillableMaxDatasources(v *int) *SubscriptionUpdate {
	if v != nil {
		_u.SetMaxDatasources(*v)
	}
	return _u
}

// AddMaxDatasources adds value to the "max_datasources" field.
func (_u *SubscriptionUpdate) AddMaxDatasources(v int) *SubscriptionUpdate {
	_u.mutation.AddMaxDatasources(v)
	return _u
}

// ClearMaxDatasources clears the value of the "max_datasources" field.
func (_u *SubscriptionUpdate) ClearMaxDatasources() *SubscriptionUpdate {
	_u.mutation.ClearMaxDatasources()
	return _u
}

// SetMaxQueries sets the "max_queries" field.
func (_u *SubscriptionUpdate) SetMaxQueries(v int) *SubscriptionUpdate {
	_u.mutation.ResetMaxQueries()
	_u.mutation.SetMaxQueries(v)
	return _u
}

// SetNillableMaxQueries sets the "max_queries" field if the given value is not nil.
func (_u *SubscriptionUpdate) SetNillableMaxQueries(v *int) *SubscriptionUpdate {
	if v != nil {
		_u.SetMaxQueries(*v)
	}
	return _u
}

// AddMaxQueries adds value to the "max_queries" field.
func (_u *SubscriptionUpdate) AddMaxQueries(v int) *SubscriptionUpdate {
	_u.mutation.AddMaxQueries(v)
	return _u
}

// ClearMaxQueries clears the value of the "max_queries" field.
func (_u *SubscriptionUpdate) ClearMaxQueries() *SubscriptionUpdate {
	_u.mutation.ClearMaxQueries()
	return _u
}

// SetMaxAlerts sets the "max_alerts" field.
func (_u *SubscriptionUpdate) SetMaxAlerts(v int) *SubscriptionUpdate {
	_u.mutation.ResetMaxAlerts()
	_u.mutation.SetMaxAlerts(v)
	return _u
}

// SetNillableMaxAlerts sets the "max_alerts" field if the given value is not nil.
func (_u *SubscriptionUpdate) SetNillableMaxAlerts(v *int) *SubscriptionUpdate {
	if v != nil {
		_u.SetMaxAlerts(*v)
	}
	return _u
}

// AddMaxAlerts adds value to the "max_alerts" field.
func (_u *SubscriptionUpdate) AddMaxAlerts(v int) *SubscriptionUpdate {
	_u.mutation.AddMaxAlerts(v)
	return _u
}

// ClearMaxAlerts clears the value of the "max_alerts" field.
func (_u *SubscriptionUpdate) ClearMaxAlerts() *SubscriptionUpdate {
	_u.mutation.ClearMaxAlerts()
	return _u
}

// SetMaxTeamMembers sets the "max_team_members" field.
func (_u *SubscriptionUpdate) SetMaxTeamMembers(v int) *SubscriptionUpdate {
	_u.mutation.ResetMaxTeamMembers()
	_u.mutation.SetMaxTeamMembers(v)
	return _u
}

// SetNillableMaxTeamMembers sets the "max_team_members" field if the given value is not nil.
func (_u *SubscriptionUpdate) SetNillableMaxTeamMembers(v *int) *SubscriptionUpdate {
	if v != nil {
		_u.SetMaxTeamMembers(*v)
	}
	return _u
}

// AddMaxTeamMembers adds value to the "max_team_members" field.
func (_u *SubscriptionUpdate) AddMaxTeamMembers(v int) *SubscriptionUpdate {
	_u.mutation.AddMaxTeamMembers(v)
	return _u
}

// ClearMaxTeamMembers clears the value of the "max_team_members" field.
func (_u *SubscriptionUpdate) ClearMaxTeamMembers() *SubscriptionUpdate {
	_u.mutation.ClearMaxTeamMembers()
	return _u
}

// SetCustomDomainEnabled sets the "custom_domain_enabled" field.
func (_u *SubscriptionUpdate) SetCustomDomainEnabled(v bool) *SubscriptionUpdate {
	_u.mutation.SetCustomDomainEnabled(v)
	return _u
}

// SetNillableCustomDomainEnabled sets the "custom_domain_enabled" field if the given value is not nil.
func (_u *SubscriptionUpdate) SetNillableCustomDomainEnabled(v *bool) *SubscriptionUpdate {
	if v != nil {
		_u.SetCustomDomainEnabled(*v)
	}
	return _u
}

// SetWhiteLabelEnabled sets the "white_label_enabled" field.
func (_u *SubscriptionUpdate) SetWhiteLabelEnabled(v bool) *SubscriptionUpdate {
	_u.mutation.SetWhiteLabelEnabled(v)
	return _u
}

// SetNillableWhiteLabelEnabled sets the "white_label_enabled" field if the given value is not nil.
func (_u *SubscriptionUpdate) SetNillableWhiteLabelEnabled(v *bool) *SubscriptionUpdate {
	if v != nil {
		_u.SetWhiteLabelEnabled(*v)
	}
	return _u
}

// SetAPIAccessEnabled sets the "api_access_enabled" field.
func (_u *SubscriptionUpdate) SetAPIAccessEnabled(v bool) *SubscriptionUpdate {
	_u.mutation.SetAPIAccessEnabled(v)
	return _u
}

// SetNillableAPIAccessEnabled sets the "api_access_enabled" field if the given value is not nil.
func (_u *SubscriptionUpdate) SetNillableAPIAccessEnabled(v *bool) *SubscriptionUpdate {
	if v != nil {
		_u.SetAPIAccessEnabled(*v)
	}
	return _u
}

// SetRealtimeEnabled sets the "realtime_enabled" field.
func (_u *SubscriptionUpdate) SetRealtimeEnabled(v bool) *SubscriptionUpdate {
	_u.mutation.SetRealtimeEnabled(v)
	return _u
}

// SetNillableRealtimeEnabled sets the "realtime_enabled" field if the given value is not nil.
func (_u *SubscriptionUpdate) SetNillableRealtimeEnabled(v *bool) *SubscriptionUpdate {
	if v != nil {
		_u.SetRealtimeEnabled(*v)
	}
	return _u
}

// SetDataRetentionDays sets the "data_retention_days" field.
func (_u *SubscriptionUpdate) SetDataRetentionDays(v int) *SubscriptionUpdate {
	_u.mutation.ResetDataRetentionDays()
	_u.mutation.SetDataRetentionDays(v)
	return _u
}

// SetNillableDataRetentionDays sets the "data_retention_days" field if the given value is not nil.
func (_u *SubscriptionUpdate) SetNillableDataRetentionDays(v *int) *SubscriptionUpdate {
	if v != nil {
		_u.SetDataRetentionDays(*v)
	}
	return _u
}

// AddDataRetentionDays adds value to the "data_retention_days" field.
func (_u *SubscriptionUpdate) AddDataRetentionDays(v int) *SubscriptionUpdate {
	_u.mutation.AddDataRetentionDays(v)
	return _u
}

// ClearDataRetentionDays clears the value of the "data_retention_days" field.
func (_u *SubscriptionUpdate) ClearDataRetentionDays() *SubscriptionUpdate {
	_u.mutation.ClearDataRetentionDays()
	return _u
}

// SetOrganization sets the "organization" edge to the Organization entity.
func (_u *SubscriptionUpdate) SetOrganization(v *Organization) *SubscriptionUpdate {
	return _u.SetOrganizationID(v.ID)
}

// Mutation returns the SubscriptionMutation object of the builder.
func (_u *SubscriptionUpdate) Mutation() *SubscriptionMutation {
	return _u.mutation
}

// ClearOrganization clears the "organization" edge to the Organization entity.
func (_u *SubscriptionUpdate) ClearOrganization() *SubscriptionUpdate {
	_u.mutation.ClearOrganization()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SubscriptionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubscriptionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SubscriptionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubscriptionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SubscriptionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := subscription.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SubscriptionUpdate) check() error {
	if v, ok := _u.mutation.PlanTier(); ok {
		if err := subscription.PlanTierValidator(v); err != nil {
			return &ValidationError{Name: "plan_tier", err: fmt.Errorf(`ent: validator failed for field "Subscription.plan_tier": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := subscription.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Subscription.status": %w`, err)}
		}
	}
	if _u.mutation.OrganizationCleared() && len(_u.mutation.OrganizationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Subscription.organization"`)
	}
	return nil
}

func (_u *SubscriptionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(subscription.Table, subscription.Columns, sqlgraph.NewFieldSpec(subscription.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PlanTier(); ok {
		_spec.SetField(subscription.FieldPlanTier, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(subscription.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.CurrentPeriodStart(); ok {
		_spec.SetField(subscription.FieldCurrentPeriodStart, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CurrentPeriodEnd(); ok {
		_spec.SetField(subscription.FieldCurrentPeriodEnd, field.TypeTime, value)
	}
	if value, ok := _u.mutation.StripeSubscriptionID(); ok {
		_spec.SetField(subscription.FieldStripeSubscriptionID, field.TypeString, value)
	}
	if _u.mutation.StripeSubscriptionIDCleared() {
		_spec.ClearField(subscription.FieldStripeSubscriptionID, field.TypeString)
	}
	if value, ok := _u.mutation.StripeCustomerID(); ok {
		_spec.SetField(subscription.FieldStripeCustomerID, field.TypeString, value)
	}
	if _u.mutation.StripeCustomerIDCleared() {
		_spec.ClearField(subscription.FieldStripeCustomerID, field.TypeString)
	}
	if value, ok := _u.mutation.CancelAtPeriodEnd(); ok {
		_spec.SetField(subscription.FieldCancelAtPeriodEnd, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(subscription.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.MaxDashboards(); ok {
		_spec.SetField(subscription.FieldMaxDashboards, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxDashboards(); ok {
		_spec.AddField(subscription.FieldMaxDashboards, field.TypeInt, value)
	}
	if _u.mutation.MaxDashboardsCleared() {
		_spec.ClearField(subscription.FieldMaxDashboards, field.TypeInt)
	}
	if value, ok := _u.mutation.MaxDatasources(); ok {
		_spec.SetField(subscription.FieldMaxDatasources, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxDatasources(); ok {
		_spec.AddField(subscription.FieldMaxDatasources, field.TypeInt, value)
	}
	if _u.mutation.MaxDatasourcesCleared() {
		_spec.ClearField(subscription.FieldMaxDatasources, field.TypeInt)
	}
	if value, ok := _u.mutation.MaxQueries(); ok {
		_spec.SetField(subscription.FieldMaxQueries, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxQueries(); ok {
		_spec.AddField(subscription.FieldMaxQueries, field.TypeInt, value)
	}
	if _u.mutation.MaxQueriesCleared() {
		_spec.ClearField(subscription.FieldMaxQueries, field.TypeInt)
	}
	if value, ok := _u.mutation.MaxAlerts(); ok {
		_spec.SetField(subscription.FieldMaxAlerts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxAlerts(); ok {
		_spec.AddField(subscription.FieldMaxAlerts, field.TypeInt, value)
	}
	if _u.mutation.MaxAlertsCleared() {
		_spec.ClearField(subscription.FieldMaxAlerts, field.TypeInt)
	}
	if value, ok := _u.mutation.MaxTeamMembers(); ok {
		_spec.SetField(subscription.FieldMaxTeamMembers, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxTeamMembers(); ok {
		_spec.AddField(subscription.FieldMaxTeamMembers, field.TypeInt, value)
	}
	if _u.mutation.MaxTeamMembersCleared() {
		_spec.ClearField(subscription.FieldMaxTeamMembers, field.TypeInt)
	}
	if value, ok := _u.mutation.CustomDomainEnabled(); ok {
		_spec.SetField(subscription.FieldCustomDomainEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.WhiteLabelEnabled(); ok {
		_spec.SetField(subscription.FieldWhiteLabelEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.APIAccessEnabled(); ok {
		_spec.SetField(subscription.FieldAPIAccessEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.RealtimeEnabled(); ok {
		_spec.SetField(subscription.FieldRealtimeEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.DataRetentionDays(); ok {
		_spec.SetField(subscription.FieldDataRetentionDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDataRetentionDays(); ok {
		_spec.AddField(subscription.FieldDataRetentionDays, field.TypeInt, value)
	}
	if _u.mutation.DataRetentionDaysCleared() {
		_spec.ClearField(subscription.FieldDataRetentionDays, field.TypeInt)
	}
	if _u.mutation.OrganizationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   subscription.OrganizationTable,
			Columns: []string{subscription.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrganizationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   subscription.OrganizationTable,
			Columns: []string{subscription.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subscription.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SubscriptionUpdateOne is the builder for updating a single Subscription entity.
type SubscriptionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SubscriptionMutation
}

// SetOrganizationID sets the "organization_id" field.
func (_u *SubscriptionUpdateOne) SetOrganizationID(v uuid.UUID) *SubscriptionUpdateOne {
	_u.mutation.SetOrganizationID(v)
	return _u
}

// SetNillableOrganizationID sets the "organization_id" field if the given value is not nil.
func (_u *SubscriptionUpdateOne) SetNillableOrganizationID(v *uuid.UUID) *SubscriptionUpdateOne {
	if v != nil {
		_u.SetOrganizationID(*v)
	}
	return _u
}

// SetPlanTier sets the "plan_tier" field.
func (_u *SubscriptionUpdateOne) SetPlanTier(v string) *SubscriptionUpdateOne {
	_u.mutation.SetPlanTier(v)
	return _u
}

// SetNillablePlanTier sets the "plan_tier" field if the given value is not nil.
func (_u *SubscriptionUpdateOne) SetNillablePlanTier(v *string) *SubscriptionUpdateOne {
	if v != nil {
		_u.SetPlanTier(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *SubscriptionUpdateOne) SetStatus(v subscription.Status) *SubscriptionUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SubscriptionUpdateOne) SetNillableStatus(v *subscription.Status) *SubscriptionUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCurrentPeriodStart sets the "current_period_start" field.
func (_u *SubscriptionUpdateOne) SetCurrentPeriodStart(v time.Time) *SubscriptionUpdateOne {
	_u.mutation.SetCurrentPeriodStart(v)
	return _u
}

// SetNillableCurrentPeriodStart sets the "current_period_start" field if the given value is not nil.
func (_u *SubscriptionUpdateOne) SetNillableCurrentPeriodStart(v *time.Time) *SubscriptionUpdateOne {
	if v != nil {
		_u.SetCurrentPeriodStart(*v)
	}
	return _u
}

// SetCurrentPeriodEnd sets the "current_period_end" field.
func (_u *SubscriptionUpdateOne) SetCurrentPeriodEnd(v time.Time) *SubscriptionUpdateOne {
	_u.mutation.SetCurrentPeriodEnd(v)
	return _u
}

// SetNillableCurrentPeriodEnd sets the "current_period_end" field if the given value is not nil.
func (_u *SubscriptionUpdateOne) SetNillableCurrentPeriodEnd(v *time.Time) *SubscriptionUpdateOne {
	if v != nil {
		_u.SetCurrentPeriodEnd(*v)
	}
	return _u
}

// SetStripeSubscriptionID sets the "stripe_subscription_id" field.
func (_u *SubscriptionUpdateOne) SetStripeSubscriptionID(v string) *SubscriptionUpdateOne {
	_u.mutation.SetStripeSubscriptionID(v)
	return _u
}

// SetNillableStripeSubscriptionID sets the "stripe_subscription_id" field if the given value is not nil.
func (_u *SubscriptionUpdateOne) SetNillableStripeSubscriptionID(v *string) *SubscriptionUpdateOne {
	if v != nil {
		_u.SetStripeSubscriptionID(*v)
	}
	return _u
}

// ClearStripeSubscriptionID clears the value of the "stripe_subscription_id" field.
func (_u *SubscriptionUpdateOne) ClearStripeSubscriptionID() *SubscriptionUpdateOne {
	_u.mutation.ClearStripeSubscriptionID()
	return _u
}

// SetStripeCustomerID sets the "stripe_customer_id" field.
func (_u *SubscriptionUpdateOne) SetStripeCustomerID(v string) *SubscriptionUpdateOne {
	_u.mutation.SetStripeCustomerID(v)
	return _u
}

// SetNillableStripeCustomerID sets the "stripe_customer_id" field if the given value is not nil.
func (_u *SubscriptionUpdateOne) SetNillableStripeCustomerID(v *string) *SubscriptionUpdateOne {
	if v != nil {
		_u.SetStripeCustomerID(*v)
	}
	return _u
}

// ClearStripeCustomerID clears the value of the "stripe_customer_id" field.
func (_u *SubscriptionUpdateOne) ClearStripeCustomerID() *SubscriptionUpdateOne {
	_u.mutation.ClearStripeCustomerID()
	return _u
}

// SetCancelAtPeriodEnd sets the "cancel_at_period_end" field.
func (_u *SubscriptionUpdateOne) SetCancelAtPeriodEnd(v bool) *SubscriptionUpdateOne {
	_u.mutation.SetCancelAtPeriodEnd(v)
	return _u
}

// SetNillableCancelAtPeriodEnd sets the "cancel_at_period_end" field if the given value is not nil.
func (_u *SubscriptionUpdateOne) SetNillableCancelAtPeriodEnd(v *bool) *SubscriptionUpdateOne {
	if v != nil {
		_u.SetCancelAtPeriodEnd(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SubscriptionUpdateOne) SetUpdatedAt(v time.Time) *SubscriptionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetMaxDashboards sets the "max_dashboards" field.
func (_u *SubscriptionUpdateOne) SetMaxDashboards(v int) *SubscriptionUpdateOne {
	_u.mutation.ResetMaxDashboards()
	_u.mutation.SetMaxDashboards(v)
	return _u
}

// SetNillableMaxDashboards sets the "max_dashboards" field if the given value is not nil.
func (_u *SubscriptionUpdateOne) SetNillableMaxDashboards(v *int) *SubscriptionUpdateOne {
	if v != nil {
		_u.SetMaxDashboards(*v)
	}
	return _u
}

// AddMaxDashboards adds value to the "max_dashboards" field.
func (_u *SubscriptionUpdateOne) AddMaxDashboards(v int) *SubscriptionUpdateOne {
	_u.mutation.AddMaxDashboards(v)
	return _u
}

// ClearMaxDashboards clears the value of the "max_dashboards" field.
func (_u *SubscriptionUpdateOne) ClearMaxDashboards() *SubscriptionUpdateOne {
	_u.mutation.ClearMaxDashboards()
	return _u
}

// SetMaxDatasources sets the "max_datasources" field.
func (_u *SubscriptionUpdateOne) SetMaxDatasources(v int) *SubscriptionUpdateOne {
	_u.mutation.ResetMaxDatasources()
	_u.mutation.SetMaxDatasources(v)
	return _u
}

// SetNillableMaxDatasources sets the "max_datasources" field if the given value is not nil.
func (_u *SubscriptionUpdateOne) SetNillableMaxDatasources(v *int) *SubscriptionUpdateOne {
	if v != nil {
		_u.SetMaxDatasources(*v)
	}
	return _u
}

// AddMaxDatasources adds value to the "max_datasources" field.
func (_u *SubscriptionUpdateOne) AddMaxDatasources(v int) *SubscriptionUpdateOne {
	_u.mutation.AddMaxDatasources(v)
	return _u
}

// ClearMaxDatasources clears the value of the "max_datasources" field.
func (_u *SubscriptionUpdateOne) ClearMaxDatasources() *SubscriptionUpdateOne {
	_u.mutation.ClearMaxDatasources()
	return _u
}

// SetMaxQueries sets the "max_queries" field.
func (_u *SubscriptionUpdateOne) SetMaxQueries(v int) *SubscriptionUpdateOne {
	_u.mutation.ResetMaxQueries()
	_u.mutation.SetMaxQueries(v)
	return _u
}

// SetNillableMaxQueries sets the "max_queries" field if the given value is not nil.
func (_u *SubscriptionUpdateOne) SetNillableMaxQueries(v *int) *SubscriptionUpdateOne {
	if v != nil {
		_u.SetMaxQueries(*v)
	}
	return _u
}

// AddMaxQueries adds value to the "max_queries" field.
func (_u *SubscriptionUpdateOne) AddMaxQueries(v int) *SubscriptionUpdateOne {
	_u.mutation.AddMaxQueries(v)
	return _u
}

// ClearMaxQueries clears the value of the "max_queries" field.
func (_u *SubscriptionUpdateOne) ClearMaxQueries() *SubscriptionUpdateOne {
	_u.mutation.ClearMaxQueries()
	return _u
}

// SetMaxAlerts sets the "max_alerts" field.
func (_u *SubscriptionUpdateOne) SetMaxAlerts(v int) *SubscriptionUpdateOne {
	_u.mutation.ResetMaxAlerts()
	_u.mutation.SetMaxAlerts(v)
	return _u
}

// SetNillableMaxAlerts sets the "max_alerts" field if the given value is not nil.
func (_u *SubscriptionUpdateOne) SetNillableMaxAlerts(v *int) *SubscriptionUpdateOne {
	if v != nil {
		_u.SetMaxAlerts(*v)
	}
	return _u
}

// AddMaxAlerts adds value to the "max_alerts" field.
func (_u *SubscriptionUpdateOne) AddMaxAlerts(v int) *SubscriptionUpdateOne {
	_u.mutation.AddMaxAlerts(v)
	return _u
}

// ClearMaxAlerts clears the value of the "max_alerts" field.
func (_u *SubscriptionUpdateOne) ClearMaxAlerts() *SubscriptionUpdateOne {
	_u.mutation.ClearMaxAlerts()
	return _u
}

// SetMaxTeamMembers sets the "max_team_members" field.
func (_u *SubscriptionUpdateOne) SetMaxTeamMembers(v int) *SubscriptionUpdateOne {
	_u.mutation.ResetMaxTeamMembers()
	_u.mutation.SetMaxTeamMembers(v)
	return _u
}

// SetNillableMaxTeamMembers sets the "max_team_members" field if the given value is not nil.
func (_u *SubscriptionUpdateOne) SetNillableMaxTeamMembers(v *int) *SubscriptionUpdateOne {
	if v != nil {
		_u.SetMaxTeamMembers(*v)
	}
	return _u
}

// AddMaxTeamMembers adds value to the "max_team_members" field.
func (_u *SubscriptionUpdateOne) AddMaxTeamMembers(v int) *SubscriptionUpdateOne {
	_u.mutation.AddMaxTeamMembers(v)
	return _u
}

// ClearMaxTeamMembers clears the value of the "max_team_members" field.
func (_u *SubscriptionUpdateOne) ClearMaxTeamMembers() *SubscriptionUpdateOne {
	_u.mutation.ClearMaxTeamMembers()
	return _u
}

// SetCustomDomainEnabled sets the "custom_domain_enabled" field.
func (_u *SubscriptionUpdateOne) SetCustomDomainEnabled(v bool) *SubscriptionUpdateOne {
	_u.mutation.SetCustomDomainEnabled(v)
	return _u
}

// SetNillableCustomDomainEnabled sets the "custom_domain_enabled" field if the given value is not nil.
func (_u *SubscriptionUpdateOne) SetNillableCustomDomainEnabled(v *bool) *SubscriptionUpdateOne {
	if v != nil {
		_u.SetCustomDomainEnabled(*v)
	}
	return _u
}

// SetWhiteLabelEnabled sets the "white_label_enabled" field.
func (_u *SubscriptionUpdateOne) SetWhiteLabelEnabled(v bool) *SubscriptionUpdateOne {
	_u.mutation.SetWhiteLabelEnabled(v)
	return _u
}

// SetNillableWhiteLabelEnabled sets the "white_label_enabled" field if the given value is not nil.
func (_u *SubscriptionUpdateOne) SetNillableWhiteLabelEnabled(v *bool) *SubscriptionUpdateOne {
	if v != nil {
		_u.SetWhiteLabelEnabled(*v)
	}
	return _u
}

// SetAPIAccessEnabled sets the "api_access_enabled" field.
func (_u *SubscriptionUpdateOne) SetAPIAccessEnabled(v bool) *SubscriptionUpdateOne {
	_u.mutation.SetAPIAccessEnabled(v)
	return _u
}

// SetNillableAPIAccessEnabled sets the "api_access_enabled" field if the given value is not nil.
func (_u *SubscriptionUpdateOne) SetNillableAPIAccessEnabled(v *bool) *SubscriptionUpdateOne {
	if v != nil {
		_u.SetAPIAccessEnabled(*v)
	}
	return _u
}

// SetRealtimeEnabled sets the "realtime_enabled" field.
func (_u *SubscriptionUpdateOne) SetRealtimeEnabled(v bool) *SubscriptionUpdateOne {
	_u.mutation.SetRealtimeEnabled(v)
	return _u
}

// SetNillableRealtimeEnabled sets the "realtime_enabled" field if the given value is not nil.
func (_u *SubscriptionUpdateOne) SetNillableRealtimeEnabled(v *bool) *SubscriptionUpdateOne {
	if v != nil {
		_u.SetRealtimeEnabled(*v)
	}
	return _u
}

// SetDataRetentionDays sets the "data_retention_days" field.
func (_u *SubscriptionUpdateOne) SetDataRetentionDays(v int) *SubscriptionUpdateOne {
	_u.mutation.ResetDataRetentionDays()
	_u.mutation.SetDataRetentionDays(v)
	return _u
}

// SetNillableDataRetentionDays sets the "data_retention_days" field if the given value is not nil.
func (_u *SubscriptionUpdateOne) SetNillableDataRetentionDays(v *int) *SubscriptionUpdateOne {
	if v != nil {
		_u.SetDataRetentionDays(*v)
	}
	return _u
}

// AddDataRetentionDays adds value to the "data_retention_days" field.
func (_u *SubscriptionUpdateOne) AddDataRetentionDays(v int) *SubscriptionUpdateOne {
	_u.mutation.AddDataRetentionDays(v)
	return _u
}

// ClearDataRetentionDays clears the value of the "data_retention_days" field.
func (_u *SubscriptionUpdateOne) ClearDataRetentionDays() *SubscriptionUpdateOne {
	_u.mutation.ClearDataRetentionDays()
	return _u
}

// SetOrganization sets the "organization" edge to the Organization entity.
func (_u *SubscriptionUpdateOne) SetOrganization(v *Organization) *SubscriptionUpdateOne {
	return _u.SetOrganizationID(v.ID)
}

// Mutation returns the SubscriptionMutation object of the builder.
func (_u *SubscriptionUpdateOne) Mutation() *SubscriptionMutation {
	return _u.mutation
}

// ClearOrganization clears the "organization" edge to the Organization entity.
func (_u *SubscriptionUpdateOne) ClearOrganization() *SubscriptionUpdateOne {
	_u.mutation.ClearOrganization()
	return _u
}

// Where appends a list predicates to the SubscriptionUpdate builder.
func (_u *SubscriptionUpdateOne) Where(ps ...predicate.Subscription) *SubscriptionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SubscriptionUpdateOne) Select(field string, fields ...string) *SubscriptionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Subscription entity.
func (_u *SubscriptionUpdateOne) Save(ctx context.Context) (*Subscription, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubscriptionUpdateOne) SaveX(ctx context.Context) *Subscription {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SubscriptionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubscriptionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SubscriptionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := subscription.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SubscriptionUpdateOne) check() error {
	if v, ok := _u.mutation.PlanTier(); ok {
		if err := subscription.PlanTierValidator(v); err != nil {
			return &ValidationError{Name: "plan_tier", err: fmt.Errorf(`ent: validator failed for field "Subscription.plan_tier": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := subscription.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Subscription.status": %w`, err)}
		}
	}
	if _u.mutation.OrganizationCleared() && len(_u.mutation.OrganizationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Subscription.organization"`)
	}
	return nil
}

func (_u *SubscriptionUpdateOne) sqlSave(ctx context.Context) (_node *Subscription, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(subscription.Table, subscription.Columns, sqlgraph.NewFieldSpec(subscription.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Subscription.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, subscription.FieldID)
		for _, f := range fields {
			if !subscription.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != subscription.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PlanTier(); ok {
		_spec.SetField(subscription.FieldPlanTier, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(subscription.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.CurrentPeriodStart(); ok {
		_spec.SetField(subscription.FieldCurrentPeriodStart, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CurrentPeriodEnd(); ok {
		_spec.SetField(subscription.FieldCurrentPeriodEnd, field.TypeTime, value)
	}
	if value, ok := _u.mutation.StripeSubscriptionID(); ok {
		_spec.SetField(subscription.FieldStripeSubscriptionID, field.TypeString, value)
	}
	if _u.mutation.StripeSubscriptionIDCleared() {
		_spec.ClearField(subscription.FieldStripeSubscriptionID, field.TypeString)
	}
	if value, ok := _u.mutation.StripeCustomerID(); ok {
		_spec.SetField(subscription.FieldStripeCustomerID, field.TypeString, value)
	}
	if _u.mutation.StripeCustomerIDCleared() {
		_spec.ClearField(subscription.FieldStripeCustomerID, field.TypeString)
	}
	if value, ok := _u.mutation.CancelAtPeriodEnd(); ok {
		_spec.SetField(subscription.FieldCancelAtPeriodEnd, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(subscription.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.MaxDashboards(); ok {
		_spec.SetField(subscription.FieldMaxDashboards, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxDashboards(); ok {
		_spec.AddField(subscription.FieldMaxDashboards, field.TypeInt, value)
	}
	if _u.mutation.MaxDashboardsCleared() {
		_spec.ClearField(subscription.FieldMaxDashboards, field.TypeInt)
	}
	if value, ok := _u.mutation.MaxDatasources(); ok {
		_spec.SetField(subscription.FieldMaxDatasources, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxDatasources(); ok {
		_spec.AddField(subscription.FieldMaxDatasources, field.TypeInt, value)
	}
	if _u.mutation.MaxDatasourcesCleared() {
		_spec.ClearField(subscription.FieldMaxDatasources, field.TypeInt)
	}
	if value, ok := _u.mutation.MaxQueries(); ok {
		_spec.SetField(subscription.FieldMaxQueries, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxQueries(); ok {
		_spec.AddField(subscription.FieldMaxQueries, field.TypeInt, value)
	}
	if _u.mutation.MaxQueriesCleared() {
		_spec.ClearField(subscription.FieldMaxQueries, field.TypeInt)
	}
	if value, ok := _u.mutation.MaxAlerts(); ok {
		_spec.SetField(subscription.FieldMaxAlerts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxAlerts(); ok {
		_spec.AddField(subscription.FieldMaxAlerts, field.TypeInt, value)
	}
	if _u.mutation.MaxAlertsCleared() {
		_spec.ClearField(subscription.FieldMaxAlerts, field.TypeInt)
	}
	if value, ok := _u.mutation.MaxTeamMembers(); ok {
		_spec.SetField(subscription.FieldMaxTeamMembers, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxTeamMembers(); ok {
		_spec.AddField(subscription.FieldMaxTeamMembers, field.TypeInt, value)
	}
	if _u.mutation.MaxTeamMembersCleared() {
		_spec.ClearField(subscription.FieldMaxTeamMembers, field.TypeInt)
	}
	if value, ok := _u.mutation.CustomDomainEnabled(); ok {
		_spec.SetField(subscription.FieldCustomDomainEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.WhiteLabelEnabled(); ok {
		_spec.SetField(subscription.FieldWhiteLabelEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.APIAccessEnabled(); ok {
		_spec.SetField(subscription.FieldAPIAccessEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.RealtimeEnabled(); ok {
		_spec.SetField(subscription.FieldRealtimeEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.DataRetentionDays(); ok {
		_spec.SetField(subscription.FieldDataRetentionDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDataRetentionDays(); ok {
		_spec.AddField(subscription.FieldDataRetentionDays, field.TypeInt, value)
	}
	if _u.mutation.DataRetentionDaysCleared() {
		_spec.ClearField(subscription.FieldDataRetentionDays, field.TypeInt)
	}
	if _u.mutation.OrganizationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   subscription.OrganizationTable,
			Columns: []string{subscription.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrganizationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   subscription.OrganizationTable,
			Columns: []string{subscription.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Subscription{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subscription.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
