// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/plexusone/dashforge/ent/user"
)

// User is the model entity for the User schema.
type User struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Email holds the value of the "email" field.
	Email string `json:"email,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// PasswordHash holds the value of the "password_hash" field.
	PasswordHash string `json:"-"`
	// AvatarURL holds the value of the "avatar_url" field.
	AvatarURL string `json:"avatar_url,omitempty"`
	// Cross-org admin access
	IsPlatformAdmin bool `json:"is_platform_admin,omitempty"`
	// CoreControl Principal ID for SSO
	CoreControlPrincipalID *uuid.UUID `json:"core_control_principal_id,omitempty"`
	// Active holds the value of the "active" field.
	Active bool `json:"active,omitempty"`
	// LastLoginAt holds the value of the "last_login_at" field.
	LastLoginAt *time.Time `json:"last_login_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserQuery when eager-loading is set.
	Edges        UserEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UserEdges holds the relations/edges for other nodes in the graph.
type UserEdges struct {
	// Memberships holds the value of the memberships edge.
	Memberships []*Membership `json:"memberships,omitempty"`
	// Dashboards holds the value of the dashboards edge.
	Dashboards []*Dashboard `json:"dashboards,omitempty"`
	// Queries holds the value of the queries edge.
	Queries []*SavedQuery `json:"queries,omitempty"`
	// OauthAccounts holds the value of the oauth_accounts edge.
	OauthAccounts []*OAuthAccount `json:"oauth_accounts,omitempty"`
	// RefreshTokens holds the value of the refresh_tokens edge.
	RefreshTokens []*RefreshToken `json:"refresh_tokens,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [5]bool
}

// MembershipsOrErr returns the Memberships value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) MembershipsOrErr() ([]*Membership, error) {
	if e.loadedTypes[0] {
		return e.Memberships, nil
	}
	return nil, &NotLoadedError{edge: "memberships"}
}

// DashboardsOrErr returns the Dashboards value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) DashboardsOrErr() ([]*Dashboard, error) {
	if e.loadedTypes[1] {
		return e.Dashboards, nil
	}
	return nil, &NotLoadedError{edge: "dashboards"}
}

// QueriesOrErr returns the Queries value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) QueriesOrErr() ([]*SavedQuery, error) {
	if e.loadedTypes[2] {
		return e.Queries, nil
	}
	return nil, &NotLoadedError{edge: "queries"}
}

// OauthAccountsOrErr returns the OauthAccounts value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) OauthAccountsOrErr() ([]*OAuthAccount, error) {
	if e.loadedTypes[3] {
		return e.OauthAccounts, nil
	}
	return nil, &NotLoadedError{edge: "oauth_accounts"}
}

// RefreshTokensOrErr returns the RefreshTokens value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) RefreshTokensOrErr() ([]*RefreshToken, error) {
	if e.loadedTypes[4] {
		return e.RefreshTokens, nil
	}
	return nil, &NotLoadedError{edge: "refresh_tokens"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*User) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case user.FieldCoreControlPrincipalID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case user.FieldIsPlatformAdmin, user.FieldActive:
			values[i] = new(sql.NullBool)
		case user.FieldEmail, user.FieldName, user.FieldPasswordHash, user.FieldAvatarURL:
			values[i] = new(sql.NullString)
		case user.FieldLastLoginAt, user.FieldCreatedAt, user.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case user.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the User fields.
func (_m *User) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case user.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case user.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				_m.Email = value.String
			}
		case user.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case user.FieldPasswordHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field password_hash", values[i])
			} else if value.Valid {
				_m.PasswordHash = value.String
			}
		case user.FieldAvatarURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field avatar_url", values[i])
			} else if value.Valid {
				_m.AvatarURL = value.String
			}
		case user.FieldIsPlatformAdmin:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_platform_admin", values[i])
			} else if value.Valid {
				_m.IsPlatformAdmin = value.Bool
			}
		case user.FieldCoreControlPrincipalID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field core_control_principal_id", values[i])
			} else if value.Valid {
				_m.CoreControlPrincipalID = new(uuid.UUID)
				*_m.CoreControlPrincipalID = *value.S.(*uuid.UUID)
			}
		case user.FieldActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field active", values[i])
			} else if value.Valid {
				_m.Active = value.Bool
			}
		case user.FieldLastLoginAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_login_at", values[i])
			} else if value.Valid {
				_m.LastLoginAt = new(time.Time)
				*_m.LastLoginAt = value.Time
			}
		case user.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case user.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the User.
// This includes values selected through modifiers, order, etc.
func (_m *User) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryMemberships queries the "memberships" edge of the User entity.
func (_m *User) QueryMemberships() *MembershipQuery {
	return NewUserClient(_m.config).QueryMemberships(_m)
}

// QueryDashboards queries the "dashboards" edge of the User entity.
func (_m *User) QueryDashboards() *DashboardQuery {
	return NewUserClient(_m.config).QueryDashboards(_m)
}

// QueryQueries queries the "queries" edge of the User entity.
func (_m *User) QueryQueries() *SavedQueryQuery {
	return NewUserClient(_m.config).QueryQueries(_m)
}

// QueryOauthAccounts queries the "oauth_accounts" edge of the User entity.
func (_m *User) QueryOauthAccounts() *OAuthAccountQuery {
	return NewUserClient(_m.config).QueryOauthAccounts(_m)
}

// QueryRefreshTokens queries the "refresh_tokens" edge of the User entity.
func (_m *User) QueryRefreshTokens() *RefreshTokenQuery {
	return NewUserClient(_m.config).QueryRefreshTokens(_m)
}

// Update returns a builder for updating this User.
// Note that you need to call User.Unwrap() before calling this method if this User
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *User) Update() *UserUpdateOne {
	return NewUserClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the User entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *User) Unwrap() *User {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: User is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *User) String() string {
	var builder strings.Builder
	builder.WriteString("User(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("email=")
	builder.WriteString(_m.Email)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("password_hash=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("avatar_url=")
	builder.WriteString(_m.AvatarURL)
	builder.WriteString(", ")
	builder.WriteString("is_platform_admin=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsPlatformAdmin))
	builder.WriteString(", ")
	if v := _m.CoreControlPrincipalID; v != nil {
		builder.WriteString("core_control_principal_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("active=")
	builder.WriteString(fmt.Sprintf("%v", _m.Active))
	builder.WriteString(", ")
	if v := _m.LastLoginAt; v != nil {
		builder.WriteString("last_login_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Users is a parsable slice of User.
type Users []*User
