// Code generated by ent, DO NOT EDIT.

package alertevent

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/plexusone/dashforge/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.AlertEvent {
	return predicate.AlertEvent(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.AlertEvent {
	return predicate.AlertEvent(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.AlertEvent {
	return predicate.AlertEvent(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.AlertEvent {
	return predicate.AlertEvent(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.AlertEvent {
	return predicate.AlertEvent(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.AlertEvent {
	return predicate.AlertEvent(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.AlertEvent {
	return predicate.AlertEvent(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.AlertEvent {
	return predicate.AlertEvent(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.AlertEvent {
	return predicate.AlertEvent(sql.FieldLTE(FieldID, id))
}

// ChannelsSuccess applies equality check predicate on the "channels_success" field. It's identical to ChannelsSuccessEQ.
func ChannelsSuccess(v int) predicate.AlertEvent {
	return predicate.AlertEvent(sql.FieldEQ(FieldChannelsSuccess, v))
}

// ChannelsFailed applies equality check predicate on the "channels_failed" field. It's identical to ChannelsFailedEQ.
func ChannelsFailed(v int) predicate.AlertEvent {
	return predicate.AlertEvent(sql.FieldEQ(FieldChannelsFailed, v))
}

// ErrorMessage applies equality check predicate on the "error_message" field. It's identical to ErrorMessageEQ.
func ErrorMessage(v string) predicate.AlertEvent {
	return predicate.AlertEvent(sql.FieldEQ(FieldErrorMessage, v))
}

// AcknowledgedBy applies equality check predicate on the "acknowledged_by" field. It's identical to AcknowledgedByEQ.
func AcknowledgedBy(v string) predicate.AlertEvent {
	return predicate.AlertEvent(sql.FieldEQ(FieldAcknowledgedBy, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AlertEvent {
	return predicate.AlertEvent(sql.FieldEQ(FieldCreatedAt, v))
}

// EventTypeEQ applies the EQ predicate on the "event_type" field.
func EventTypeEQ(v EventType) predicate.AlertEvent {
	return predicate.AlertEvent(sql.FieldEQ(FieldEventType, v))
}

// EventTypeNEQ applies the NEQ predicate on the "event_type" field.
func EventTypeNEQ(v EventType) predicate.AlertEvent {
	return predicate.AlertEvent(sql.FieldNEQ(FieldEventType, v))
}

// EventTypeIn applies the In predicate on the "event_type" field.
func EventTypeIn(vs ...EventType) predicate.AlertEvent {
	return predicate.AlertEvent(sql.FieldIn(FieldEventType, vs...))
}

// EventTypeNotIn applies the NotIn predicate on the "event_type" field.
func EventTypeNotIn(vs ...EventType) predicate.AlertEvent {
	return predicate.AlertEvent(sql.FieldNotIn(FieldEventType, vs...))
}

// TriggerDataIsNil applies the IsNil predicate on the "trigger_data" field.
func TriggerDataIsNil() predicate.AlertEvent {
	return predicate.AlertEvent(sql.FieldIsNull(FieldTriggerData))
}

// TriggerDataNotNil applies the NotNil predicate on the "trigger_data" field.
func TriggerDataNotNil() predicate.AlertEvent {
	return predicate.AlertEvent(sql.FieldNotNull(FieldTriggerData))
}

// ChannelsNotifiedIsNil applies the IsNil predicate on the "channels_notified" field.
func ChannelsNotifiedIsNil() predicate.AlertEvent {
	return predicate.AlertEvent(sql.FieldIsNull(FieldChannelsNotified))
}

// ChannelsNotifiedNotNil applies the NotNil predicate on the "channels_notified" field.
func ChannelsNotifiedNotNil() predicate.AlertEvent {
	return predicate.AlertEvent(sql.FieldNotNull(FieldChannelsNotified))
}

// ChannelsSuccessEQ applies the EQ predicate on the "channels_success" field.
func ChannelsSuccessEQ(v int) predicate.AlertEvent {
	return predicate.AlertEvent(sql.FieldEQ(FieldChannelsSuccess, v))
}

// ChannelsSuccessNEQ applies the NEQ predicate on the "channels_success" field.
func ChannelsSuccessNEQ(v int) predicate.AlertEvent {
	return predicate.AlertEvent(sql.FieldNEQ(FieldChannelsSuccess, v))
}

// ChannelsSuccessIn applies the In predicate on the "channels_success" field.
func ChannelsSuccessIn(vs ...int) predicate.AlertEvent {
	return predicate.AlertEvent(sql.FieldIn(FieldChannelsSuccess, vs...))
}

// ChannelsSuccessNotIn applies the NotIn predicate on the "channels_success" field.
func ChannelsSuccessNotIn(vs ...int) predicate.AlertEvent {
	return predicate.AlertEvent(sql.FieldNotIn(FieldChannelsSuccess, vs...))
}

// ChannelsSuccessGT applies the GT predicate on the "channels_success" field.
func ChannelsSuccessGT(v int) predicate.AlertEvent {
	return predicate.AlertEvent(sql.FieldGT(FieldChannelsSuccess, v))
}

// ChannelsSuccessGTE applies the GTE predicate on the "channels_success" field.
func ChannelsSuccessGTE(v int) predicate.AlertEvent {
	return predicate.AlertEvent(sql.FieldGTE(FieldChannelsSuccess, v))
}

// ChannelsSuccessLT applies the LT predicate on the "channels_success" field.
func ChannelsSuccessLT(v int) predicate.AlertEvent {
	return predicate.AlertEvent(sql.FieldLT(FieldChannelsSuccess, v))
}

// ChannelsSuccessLTE applies the LTE predicate on the "channels_success" field.
func ChannelsSuccessLTE(v int) predicate.AlertEvent {
	return predicate.AlertEvent(sql.FieldLTE(FieldChannelsSuccess, v))
}

// ChannelsFailedEQ applies the EQ predicate on the "channels_failed" field.
func ChannelsFailedEQ(v int) predicate.AlertEvent {
	return predicate.AlertEvent(sql.FieldEQ(FieldChannelsFailed, v))
}

// ChannelsFailedNEQ applies the NEQ predicate on the "channels_failed" field.
func ChannelsFailedNEQ(v int) predicate.AlertEvent {
	return predicate.AlertEvent(sql.FieldNEQ(FieldChannelsFailed, v))
}

// ChannelsFailedIn applies the In predicate on the "channels_failed" field.
func ChannelsFailedIn(vs ...int) predicate.AlertEvent {
	return predicate.AlertEvent(sql.FieldIn(FieldChannelsFailed, vs...))
}

// ChannelsFailedNotIn applies the NotIn predicate on the "channels_failed" field.
func ChannelsFailedNotIn(vs ...int) predicate.AlertEvent {
	return predicate.AlertEvent(sql.FieldNotIn(FieldChannelsFailed, vs...))
}

// ChannelsFailedGT applies the GT predicate on the "channels_failed" field.
func ChannelsFailedGT(v int) predicate.AlertEvent {
	return predicate.AlertEvent(sql.FieldGT(FieldChannelsFailed, v))
}

// ChannelsFailedGTE applies the GTE predicate on the "channels_failed" field.
func ChannelsFailedGTE(v int) predicate.AlertEvent {
	return predicate.AlertEvent(sql.FieldGTE(FieldChannelsFailed, v))
}

// ChannelsFailedLT applies the LT predicate on the "channels_failed" field.
func ChannelsFailedLT(v int) predicate.AlertEvent {
	return predicate.AlertEvent(sql.FieldLT(FieldChannelsFailed, v))
}

// ChannelsFailedLTE applies the LTE predicate on the "channels_failed" field.
func ChannelsFailedLTE(v int) predicate.AlertEvent {
	return predicate.AlertEvent(sql.FieldLTE(FieldChannelsFailed, v))
}

// ErrorMessageEQ applies the EQ predicate on the "error_message" field.
func ErrorMessageEQ(v string) predicate.AlertEvent {
	return predicate.AlertEvent(sql.FieldEQ(FieldErrorMessage, v))
}

// ErrorMessageNEQ applies the NEQ predicate on the "error_message" field.
func ErrorMessageNEQ(v string) predicate.AlertEvent {
	return predicate.AlertEvent(sql.FieldNEQ(FieldErrorMessage, v))
}

// ErrorMessageIn applies the In predicate on the "error_message" field.
func ErrorMessageIn(vs ...string) predicate.AlertEvent {
	return predicate.AlertEvent(sql.FieldIn(FieldErrorMessage, vs...))
}

// ErrorMessageNotIn applies the NotIn predicate on the "error_message" field.
func ErrorMessageNotIn(vs ...string) predicate.AlertEvent {
	return predicate.AlertEvent(sql.FieldNotIn(FieldErrorMessage, vs...))
}

// ErrorMessageGT applies the GT predicate on the "error_message" field.
func ErrorMessageGT(v string) predicate.AlertEvent {
	return predicate.AlertEvent(sql.FieldGT(FieldErrorMessage, v))
}

// ErrorMessageGTE applies the GTE predicate on the "error_message" field.
func ErrorMessageGTE(v string) predicate.AlertEvent {
	return predicate.AlertEvent(sql.FieldGTE(FieldErrorMessage, v))
}

// ErrorMessageLT applies the LT predicate on the "error_message" field.
func ErrorMessageLT(v string) predicate.AlertEvent {
	return predicate.AlertEvent(sql.FieldLT(FieldErrorMessage, v))
}

// ErrorMessageLTE applies the LTE predicate on the "error_message" field.
func ErrorMessageLTE(v string) predicate.AlertEvent {
	return predicate.AlertEvent(sql.FieldLTE(FieldErrorMessage, v))
}

// ErrorMessageContains applies the Contains predicate on the "error_message" field.
func ErrorMessageContains(v string) predicate.AlertEvent {
	return predicate.AlertEvent(sql.FieldContains(FieldErrorMessage, v))
}

// ErrorMessageHasPrefix applies the HasPrefix predicate on the "error_message" field.
func ErrorMessageHasPrefix(v string) predicate.AlertEvent {
	return predicate.AlertEvent(sql.FieldHasPrefix(FieldErrorMessage, v))
}

// ErrorMessageHasSuffix applies the HasSuffix predicate on the "error_message" field.
func ErrorMessageHasSuffix(v string) predicate.AlertEvent {
	return predicate.AlertEvent(sql.FieldHasSuffix(FieldErrorMessage, v))
}

// ErrorMessageIsNil applies the IsNil predicate on the "error_message" field.
func ErrorMessageIsNil() predicate.AlertEvent {
	return predicate.AlertEvent(sql.FieldIsNull(FieldErrorMessage))
}

// ErrorMessageNotNil applies the NotNil predicate on the "error_message" field.
func ErrorMessageNotNil() predicate.AlertEvent {
	return predicate.AlertEvent(sql.FieldNotNull(FieldErrorMessage))
}

// ErrorMessageEqualFold applies the EqualFold predicate on the "error_message" field.
func ErrorMessageEqualFold(v string) predicate.AlertEvent {
	return predicate.AlertEvent(sql.FieldEqualFold(FieldErrorMessage, v))
}

// ErrorMessageContainsFold applies the ContainsFold predicate on the "error_message" field.
func ErrorMessageContainsFold(v string) predicate.AlertEvent {
	return predicate.AlertEvent(sql.FieldContainsFold(FieldErrorMessage, v))
}

// AcknowledgedByEQ applies the EQ predicate on the "acknowledged_by" field.
func AcknowledgedByEQ(v string) predicate.AlertEvent {
	return predicate.AlertEvent(sql.FieldEQ(FieldAcknowledgedBy, v))
}

// AcknowledgedByNEQ applies the NEQ predicate on the "acknowledged_by" field.
func AcknowledgedByNEQ(v string) predicate.AlertEvent {
	return predicate.AlertEvent(sql.FieldNEQ(FieldAcknowledgedBy, v))
}

// AcknowledgedByIn applies the In predicate on the "acknowledged_by" field.
func AcknowledgedByIn(vs ...string) predicate.AlertEvent {
	return predicate.AlertEvent(sql.FieldIn(FieldAcknowledgedBy, vs...))
}

// AcknowledgedByNotIn applies the NotIn predicate on the "acknowledged_by" field.
func AcknowledgedByNotIn(vs ...string) predicate.AlertEvent {
	return predicate.AlertEvent(sql.FieldNotIn(FieldAcknowledgedBy, vs...))
}

// AcknowledgedByGT applies the GT predicate on the "acknowledged_by" field.
func AcknowledgedByGT(v string) predicate.AlertEvent {
	return predicate.AlertEvent(sql.FieldGT(FieldAcknowledgedBy, v))
}

// AcknowledgedByGTE applies the GTE predicate on the "acknowledged_by" field.
func AcknowledgedByGTE(v string) predicate.AlertEvent {
	return predicate.AlertEvent(sql.FieldGTE(FieldAcknowledgedBy, v))
}

// AcknowledgedByLT applies the LT predicate on the "acknowledged_by" field.
func AcknowledgedByLT(v string) predicate.AlertEvent {
	return predicate.AlertEvent(sql.FieldLT(FieldAcknowledgedBy, v))
}

// AcknowledgedByLTE applies the LTE predicate on the "acknowledged_by" field.
func AcknowledgedByLTE(v string) predicate.AlertEvent {
	return predicate.AlertEvent(sql.FieldLTE(FieldAcknowledgedBy, v))
}

// AcknowledgedByContains applies the Contains predicate on the "acknowledged_by" field.
func AcknowledgedByContains(v string) predicate.AlertEvent {
	return predicate.AlertEvent(sql.FieldContains(FieldAcknowledgedBy, v))
}

// AcknowledgedByHasPrefix applies the HasPrefix predicate on the "acknowledged_by" field.
func AcknowledgedByHasPrefix(v string) predicate.AlertEvent {
	return predicate.AlertEvent(sql.FieldHasPrefix(FieldAcknowledgedBy, v))
}

// AcknowledgedByHasSuffix applies the HasSuffix predicate on the "acknowledged_by" field.
func AcknowledgedByHasSuffix(v string) predicate.AlertEvent {
	return predicate.AlertEvent(sql.FieldHasSuffix(FieldAcknowledgedBy, v))
}

// AcknowledgedByIsNil applies the IsNil predicate on the "acknowledged_by" field.
func AcknowledgedByIsNil() predicate.AlertEvent {
	return predicate.AlertEvent(sql.FieldIsNull(FieldAcknowledgedBy))
}

// AcknowledgedByNotNil applies the NotNil predicate on the "acknowledged_by" field.
func AcknowledgedByNotNil() predicate.AlertEvent {
	return predicate.AlertEvent(sql.FieldNotNull(FieldAcknowledgedBy))
}

// AcknowledgedByEqualFold applies the EqualFold predicate on the "acknowledged_by" field.
func AcknowledgedByEqualFold(v string) predicate.AlertEvent {
	return predicate.AlertEvent(sql.FieldEqualFold(FieldAcknowledgedBy, v))
}

// AcknowledgedByContainsFold applies the ContainsFold predicate on the "acknowledged_by" field.
func AcknowledgedByContainsFold(v string) predicate.AlertEvent {
	return predicate.AlertEvent(sql.FieldContainsFold(FieldAcknowledgedBy, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AlertEvent {
	return predicate.AlertEvent(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AlertEvent {
	return predicate.AlertEvent(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AlertEvent {
	return predicate.AlertEvent(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AlertEvent {
	return predicate.AlertEvent(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AlertEvent {
	return predicate.AlertEvent(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AlertEvent {
	return predicate.AlertEvent(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AlertEvent {
	return predicate.AlertEvent(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AlertEvent {
	return predicate.AlertEvent(sql.FieldLTE(FieldCreatedAt, v))
}

// HasAlert applies the HasEdge predicate on the "alert" edge.
func HasAlert() predicate.AlertEvent {
	return predicate.AlertEvent(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AlertTable, AlertColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAlertWith applies the HasEdge predicate on the "alert" edge with a given conditions (other predicates).
func HasAlertWith(preds ...predicate.Alert) predicate.AlertEvent {
	return predicate.AlertEvent(func(s *sql.Selector) {
		step := newAlertStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AlertEvent) predicate.AlertEvent {
	return predicate.AlertEvent(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AlertEvent) predicate.AlertEvent {
	return predicate.AlertEvent(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AlertEvent) predicate.AlertEvent {
	return predicate.AlertEvent(sql.NotPredicates(p))
}
