// Code generated by ent, DO NOT EDIT.

package alert

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the alert type in the database.
	Label = "alert"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSlug holds the string denoting the slug field in the database.
	FieldSlug = "slug"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldTriggerType holds the string denoting the trigger_type field in the database.
	FieldTriggerType = "trigger_type"
	// FieldTriggerConfig holds the string denoting the trigger_config field in the database.
	FieldTriggerConfig = "trigger_config"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldCooldownSeconds holds the string denoting the cooldown_seconds field in the database.
	FieldCooldownSeconds = "cooldown_seconds"
	// FieldConsecutiveFailures holds the string denoting the consecutive_failures field in the database.
	FieldConsecutiveFailures = "consecutive_failures"
	// FieldLastTriggeredAt holds the string denoting the last_triggered_at field in the database.
	FieldLastTriggeredAt = "last_triggered_at"
	// FieldLastEvaluatedAt holds the string denoting the last_evaluated_at field in the database.
	FieldLastEvaluatedAt = "last_evaluated_at"
	// FieldLastError holds the string denoting the last_error field in the database.
	FieldLastError = "last_error"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeOrganization holds the string denoting the organization edge name in mutations.
	EdgeOrganization = "organization"
	// EdgeDashboard holds the string denoting the dashboard edge name in mutations.
	EdgeDashboard = "dashboard"
	// EdgeChannels holds the string denoting the channels edge name in mutations.
	EdgeChannels = "channels"
	// EdgeEvents holds the string denoting the events edge name in mutations.
	EdgeEvents = "events"
	// EdgeAlertChannels holds the string denoting the alert_channels edge name in mutations.
	EdgeAlertChannels = "alert_channels"
	// Table holds the table name of the alert in the database.
	Table = "alerts"
	// OrganizationTable is the table that holds the organization relation/edge.
	OrganizationTable = "alerts"
	// OrganizationInverseTable is the table name for the Organization entity.
	// It exists in this package in order to avoid circular dependency with the "organization" package.
	OrganizationInverseTable = "organizations"
	// OrganizationColumn is the table column denoting the organization relation/edge.
	OrganizationColumn = "organization_alerts"
	// DashboardTable is the table that holds the dashboard relation/edge.
	DashboardTable = "alerts"
	// DashboardInverseTable is the table name for the Dashboard entity.
	// It exists in this package in order to avoid circular dependency with the "dashboard" package.
	DashboardInverseTable = "dashboards"
	// DashboardColumn is the table column denoting the dashboard relation/edge.
	DashboardColumn = "dashboard_alerts"
	// ChannelsTable is the table that holds the channels relation/edge. The primary key declared below.
	ChannelsTable = "alert_channels"
	// ChannelsInverseTable is the table name for the Integration entity.
	// It exists in this package in order to avoid circular dependency with the "integration" package.
	ChannelsInverseTable = "integrations"
	// EventsTable is the table that holds the events relation/edge.
	EventsTable = "alert_events"
	// EventsInverseTable is the table name for the AlertEvent entity.
	// It exists in this package in order to avoid circular dependency with the "alertevent" package.
	EventsInverseTable = "alert_events"
	// EventsColumn is the table column denoting the events relation/edge.
	EventsColumn = "alert_events"
	// AlertChannelsTable is the table that holds the alert_channels relation/edge.
	AlertChannelsTable = "alert_channels"
	// AlertChannelsInverseTable is the table name for the AlertChannel entity.
	// It exists in this package in order to avoid circular dependency with the "alertchannel" package.
	AlertChannelsInverseTable = "alert_channels"
	// AlertChannelsColumn is the table column denoting the alert_channels relation/edge.
	AlertChannelsColumn = "alert_id"
)

// Columns holds all SQL columns for alert fields.
var Columns = []string{
	FieldID,
	FieldSlug,
	FieldName,
	FieldDescription,
	FieldTriggerType,
	FieldTriggerConfig,
	FieldEnabled,
	FieldCooldownSeconds,
	FieldConsecutiveFailures,
	FieldLastTriggeredAt,
	FieldLastEvaluatedAt,
	FieldLastError,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "alerts"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"dashboard_alerts",
	"organization_alerts",
}

var (
	// ChannelsPrimaryKey and ChannelsColumn2 are the table columns denoting the
	// primary key for the channels relation (M2M).
	ChannelsPrimaryKey = []string{"alert_id", "integration_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	SlugValidator func(string) error
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// DefaultCooldownSeconds holds the default value on creation for the "cooldown_seconds" field.
	DefaultCooldownSeconds int
	// CooldownSecondsValidator is a validator for the "cooldown_seconds" field. It is called by the builders before save.
	CooldownSecondsValidator func(int) error
	// DefaultConsecutiveFailures holds the default value on creation for the "consecutive_failures" field.
	DefaultConsecutiveFailures int
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// TriggerType defines the type for the "trigger_type" enum field.
type TriggerType string

// TriggerType values.
const (
	TriggerTypeThreshold  TriggerType = "threshold"
	TriggerTypeSchedule   TriggerType = "schedule"
	TriggerTypeDataChange TriggerType = "data_change"
)

func (tt TriggerType) String() string {
	return string(tt)
}

// TriggerTypeValidator is a validator for the "trigger_type" field enum values. It is called by the builders before save.
func TriggerTypeValidator(tt TriggerType) error {
	switch tt {
	case TriggerTypeThreshold, TriggerTypeSchedule, TriggerTypeDataChange:
		return nil
	default:
		return fmt.Errorf("alert: invalid enum value for trigger_type field: %q", tt)
	}
}

// OrderOption defines the ordering options for the Alert queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySlug orders the results by the slug field.
func BySlug(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSlug, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByTriggerType orders the results by the trigger_type field.
func ByTriggerType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTriggerType, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByCooldownSeconds orders the results by the cooldown_seconds field.
func ByCooldownSeconds(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCooldownSeconds, opts...).ToFunc()
}

// ByConsecutiveFailures orders the results by the consecutive_failures field.
func ByConsecutiveFailures(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConsecutiveFailures, opts...).ToFunc()
}

// ByLastTriggeredAt orders the results by the last_triggered_at field.
func ByLastTriggeredAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastTriggeredAt, opts...).ToFunc()
}

// ByLastEvaluatedAt orders the results by the last_evaluated_at field.
func ByLastEvaluatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastEvaluatedAt, opts...).ToFunc()
}

// ByLastError orders the results by the last_error field.
func ByLastError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastError, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByOrganizationField orders the results by organization field.
func ByOrganizationField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOrganizationStep(), sql.OrderByField(field, opts...))
	}
}

// ByDashboardField orders the results by dashboard field.
func ByDashboardField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDashboardStep(), sql.OrderByField(field, opts...))
	}
}

// ByChannelsCount orders the results by channels count.
func ByChannelsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newChannelsStep(), opts...)
	}
}

// ByChannels orders the results by channels terms.
func ByChannels(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newChannelsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByEventsCount orders the results by events count.
func ByEventsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newEventsStep(), opts...)
	}
}

// ByEvents orders the results by events terms.
func ByEvents(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newEventsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByAlertChannelsCount orders the results by alert_channels count.
func ByAlertChannelsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAlertChannelsStep(), opts...)
	}
}

// ByAlertChannels orders the results by alert_channels terms.
func ByAlertChannels(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAlertChannelsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newOrganizationStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OrganizationInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, OrganizationTable, OrganizationColumn),
	)
}
func newDashboardStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DashboardInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, DashboardTable, DashboardColumn),
	)
}
func newChannelsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ChannelsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, false, ChannelsTable, ChannelsPrimaryKey...),
	)
}
func newEventsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(EventsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, EventsTable, EventsColumn),
	)
}
func newAlertChannelsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AlertChannelsInverseTable, AlertChannelsColumn),
		sqlgraph.Edge(sqlgraph.O2M, true, AlertChannelsTable, AlertChannelsColumn),
	)
}
